DROP TABLE IF EXISTS `dbc_Spell`;
CREATE TABLE `dbc_Spell` (
	`m_ID` INT NOT NULL DEFAULT '0',
	`m_attributes` INT UNSIGNED NOT NULL DEFAULT '0',
	`m_attributesEx` INT UNSIGNED NOT NULL DEFAULT '0',
	`m_attributesExB` INT UNSIGNED NOT NULL DEFAULT '0',
	`m_attributesExC` INT UNSIGNED NOT NULL DEFAULT '0',
	`m_attributesExD` INT UNSIGNED NOT NULL DEFAULT '0',
	`m_attributesExE` INT UNSIGNED NOT NULL DEFAULT '0',
	`m_attributesExF` INT UNSIGNED NOT NULL DEFAULT '0',
	`m_attributesExG` INT UNSIGNED NOT NULL DEFAULT '0',
	`m_attributesExH` INT UNSIGNED NOT NULL DEFAULT '0',
	`m_unk_400_1` INT UNSIGNED NOT NULL DEFAULT '0',
	`m_castingTimeIndex` INT NOT NULL DEFAULT '0',
	`m_durationIndex` INT NOT NULL DEFAULT '0',
	`m_powerType` INT NOT NULL DEFAULT '0',
	`m_rangeIndex` INT NOT NULL DEFAULT '0',
	`m_speed` FLOAT NOT NULL DEFAULT '0',
	`m_spellVisualID_1` INT UNSIGNED NOT NULL DEFAULT '0',
	`m_spellVisualID_2` INT UNSIGNED NOT NULL DEFAULT '0',
	`m_spellIconID` INT NOT NULL DEFAULT '0',
	`m_activeIconID` INT NOT NULL DEFAULT '0',
	`m_name` TEXT NOT NULL,
	`m_nameSubtext` TEXT NOT NULL,
	`m_description` TEXT NOT NULL,
	`m_auraDescription` TEXT NOT NULL,
	`m_schoolMask` INT NOT NULL DEFAULT '0',
	`m_runeCostID` INT NOT NULL DEFAULT '0',
	`m_spellMissileID` INT NOT NULL DEFAULT '0',
	`m_spellDescriptionVariableID` INT NOT NULL DEFAULT '0',
	`m_spellDifficultyID` INT NOT NULL DEFAULT '0',
	`m_unk_f1` FLOAT NOT NULL DEFAULT '0',
	`m_spellScalingID` INT NOT NULL DEFAULT '0',
	`m_SpellAuraOptionsId` INT NOT NULL DEFAULT '0',
	`m_SpellAuraRestrictionsId` INT NOT NULL DEFAULT '0',
	`m_SpellCastingRequirementsId` INT NOT NULL DEFAULT '0',
	`m_SpellCategoriesId` INT NOT NULL DEFAULT '0',
	`m_SpellClassOptionsId` INT NOT NULL DEFAULT '0',
	`m_SpellCooldownsId` INT NOT NULL DEFAULT '0',
	`m_unk_i1` INT NOT NULL DEFAULT '0',
	`m_SpellEquippedItemsId` INT NOT NULL DEFAULT '0',
	`m_SpellInterruptsId` INT NOT NULL DEFAULT '0',
	`m_SpellLevelsId` INT NOT NULL DEFAULT '0',
	`m_SpellPowerId` INT NOT NULL DEFAULT '0',
	`m_SpellReagentsId` INT NOT NULL DEFAULT '0',
	`m_SpellShapeshiftId` INT NOT NULL DEFAULT '0',
	`m_SpellTargetRestrictionsId` INT NOT NULL DEFAULT '0',
	`m_SpellTotemsId` INT NOT NULL DEFAULT '0',
	`m_ResearchId` INT NOT NULL DEFAULT '0',
	PRIMARY KEY (`m_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Export of Spell.dbc';
