ALTER TABLE  `game_event` CHANGE  `entry`  `eventEntry` MEDIUMINT(8) UNSIGNED NOT NULL;
ALTER TABLE  `game_event_creature` CHANGE  `event`  `eventEntry` SMALLINT(6) NOT NULL;
ALTER TABLE  `game_event_gameobject` CHANGE  `event`  `eventEntry` SMALLINT(6) NOT NULL;
ALTER TABLE  `game_event_prerequisite` CHANGE  `event_id`  `eventEntry` MEDIUMINT(8) UNSIGNED NOT NULL;
ALTER TABLE  `game_event_model_equip` CHANGE  `event`  `eventEntry` SMALLINT(5) UNSIGNED NOT NULL;
ALTER TABLE  `game_event_creature_quest` CHANGE  `event`  `eventEntry` SMALLINT(5) UNSIGNED NOT NULL;
ALTER TABLE  `game_event_gameobject_quest` CHANGE  `event`  `eventEntry` SMALLINT(5) UNSIGNED NOT NULL;
ALTER TABLE  `game_event_quest_condition` CHANGE  `event_id`  `eventEntry` MEDIUMINT(8) UNSIGNED NOT NULL;
ALTER TABLE  `game_event_condition` CHANGE  `event_id`  `eventEntry` MEDIUMINT(8) UNSIGNED NOT NULL;
ALTER TABLE  `game_event_npc_vendor` CHANGE  `event`  `eventEntry` MEDIUMINT(8) UNSIGNED NOT NULL;
ALTER TABLE  `game_event_battleground_holiday` CHANGE  `event`  `eventEntry` INT(10) UNSIGNED NOT NULL;
ALTER TABLE  `game_event_pool` CHANGE  `event`  `eventEntry` SMALLINT(6) NOT NULL;
ALTER TABLE  `game_event_npcflag` CHANGE  `event_id`  `eventEntry` MEDIUMINT(8) UNSIGNED NOT NULL;