/*
 * Copyright (C) 2011      TrilliumEMU <http://www.trilliumemu.com/>
 * Copyright (C) 2008-2011 TrinityCore <http://www.trinitycore.org/>
 * Copyright (C) 2005-2011 MaNGOS      <http://getmangos.com/>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/// \addtogroup u2w
/// @{
/// \file

#ifndef _OPCODES_H
#define _OPCODES_H

#include "Common.h"

// Note: this include need for be sure have full definition of class WorldSession
//       if this class definition not complite then VS for x64 release use different size for
//       struct OpcodeHandler in this header and Opcode.cpp and get totally wrong data from
//       table opcodeTable in source when Opcode.h included but WorldSession.h not included
#include "WorldSession.h"

/// List of Opcodes
enum Opcodes
{
/*  NAME                                              OPC       VERSION*/
    MSG_NULL_ACTION                                 = 0x000, //
    CMSG_BOOTME                                     = 0x001, //
    CMSG_DBLOOKUP                                   = 0x002, //
    SMSG_DBLOOKUP                                   = 0x003, //
    CMSG_QUERY_OBJECT_POSITION                      = 0x004, //
    SMSG_QUERY_OBJECT_POSITION                      = 0x005, //
    CMSG_QUERY_OBJECT_ROTATION                      = 0x006, //
    SMSG_QUERY_OBJECT_ROTATION                      = 0x007, //
    CMSG_WORLD_TELEPORT                             = 0x8581, // 4.0.6a
    CMSG_TELEPORT_TO_UNIT                           = 0xE1AC, // 4.0.6a
    CMSG_ZONE_MAP                                   = 0x00A, //
    SMSG_ZONE_MAP                                   = 0x00B, //
    CMSG_DEBUG_CHANGECELLZONE                       = 0x00C, //
    CMSG_MOVE_CHARACTER_CHEAT                       = 0x00D, //
    SMSG_MOVE_CHARACTER_CHEAT                       = 0x00E, //
    CMSG_RECHARGE                                   = 0x00F, //
    CMSG_LEARN_SPELL                                = 0x010, //
    CMSG_CREATEMONSTER                              = 0x011, //
    CMSG_DESTROYMONSTER                             = 0x012, //
    CMSG_CREATEITEM                                 = 0x013, //
    CMSG_CREATEGAMEOBJECT                           = 0x014, //
    SMSG_CHECK_FOR_BOTS                             = 0xFEC8, // 4.0.6a
    CMSG_MAKEMONSTERATTACKGUID                      = 0x016, //
    CMSG_BOT_DETECTED2                              = 0x017, //
    CMSG_FORCEACTION                                = 0x018, //
    CMSG_FORCEACTIONONOTHER                         = 0x019, //
    CMSG_FORCEACTIONSHOW                            = 0x01A, //
    SMSG_FORCEACTIONSHOW                            = 0xAC84, // 4.0.6a
    CMSG_PETGODMODE                                 = 0x01C, //
    SMSG_PETGODMODE                                 = 0xF2CC, // 4.0.6a
    SMSG_REFER_A_FRIEND_EXPIRED                     = 0x01E, //
    CMSG_WEATHER_SPEED_CHEAT                        = 0x01F, //
    CMSG_UNDRESSPLAYER                              = 0x020, //
    CMSG_BEASTMASTER                                = 0x021, //
    CMSG_GODMODE                                    = 0x022, //
    SMSG_GODMODE                                    = 0x23EC, // 4.0.6a
    CMSG_CHEAT_SETMONEY                             = 0x024, //
    CMSG_LEVEL_CHEAT                                = 0x025, //
    CMSG_PET_LEVEL_CHEAT                            = 0x026, //
    CMSG_SET_WORLDSTATE                             = 0x027, //
    CMSG_COOLDOWN_CHEAT                             = 0x028, //
    CMSG_USE_SKILL_CHEAT                            = 0x029, //
    CMSG_FLAG_QUEST                                 = 0x02A, //
    CMSG_FLAG_QUEST_FINISH                          = 0x02B, //
    CMSG_CLEAR_QUEST                                = 0x02C, //
    CMSG_SEND_EVENT                                 = 0x02D, //
    CMSG_DEBUG_AISTATE                              = 0x02E, //
    SMSG_DEBUG_AISTATE                              = 0x02F, //
    CMSG_DISABLE_PVP_CHEAT                          = 0x030, //
    CMSG_ADVANCE_SPAWN_TIME                         = 0x031, //
    SMSG_DESTRUCTIBLE_BUILDING_DAMAGE               = 0xA0E0, // 4.0.6a
    CMSG_AUTH_SRP6_BEGIN                            = 0x033, //
    CMSG_AUTH_SRP6_PROOF                            = 0x034, //
    CMSG_AUTH_SRP6_RECODE                           = 0x035, //
    CMSG_CHAR_CREATE                                = 0x7EEC, // 4.0.6a
    CMSG_CHAR_ENUM                                  = 0x6AA4, // 4.0.6a
    CMSG_CHAR_DELETE                                = 0x3B84, // 4.0.6a
    SMSG_AUTH_SRP6_RESPONSE                         = 0x039, //
    SMSG_CHAR_CREATE                                = 0xF7EC, // 4.0.6a
    SMSG_CHAR_ENUM                                  = 0xECCC, // 4.0.6a
    SMSG_CHAR_DELETE                                = 0xBC80, // 4.0.6a
    CMSG_PLAYER_LOGIN                               = 0x8180, // 4.0.6a
    SMSG_NEW_WORLD                                  = 0x451E, // 4.0.6a
    SMSG_TRANSFER_PENDING                           = 0x7BE0, // 4.0.6a
    SMSG_TRANSFER_ABORTED                           = 0x2BE0, // 4.0.6a
    SMSG_CHARACTER_LOGIN_FAILED                     = 0x7ACC, // 4.0.6a
    SMSG_LOGIN_SETTIMESPEED                         = 0x39AC, // 4.0.6a
    SMSG_GAMETIME_UPDATE                            = 0xF1EC, // 4.0.6a
    CMSG_GAMETIME_SET                               = 0x20C4, // 4.0.6a
    SMSG_GAMETIME_SET                               = 0x7888, // 4.0.6a
    CMSG_GAMESPEED_SET                              = 0x2084, // 4.0.6a
    SMSG_GAMESPEED_SET                              = 0x3EC0, // 4.0.6a
    CMSG_SERVERTIME                                 = 0x048, //
    SMSG_SERVERTIME                                 = 0x23A4, // 4.0.6a
    CMSG_PLAYER_LOGOUT                              = 0xF78C, // 4.0.6a
    CMSG_LOGOUT_REQUEST                             = 0xA7A8, // 4.0.6a
    SMSG_LOGOUT_RESPONSE                            = 0xF788, // 4.0.6a
    SMSG_LOGOUT_COMPLETE                            = 0xA0A4, // 4.0.6a
    CMSG_LOGOUT_CANCEL                              = 0x39E8, // 4.0.6a
    SMSG_LOGOUT_CANCEL_ACK                          = 0xEE88, // 4.0.6a
    CMSG_NAME_QUERY                                 = 0x7AAC, // 4.0.6a
    SMSG_NAME_QUERY_RESPONSE                        = 0x7BC8, // 4.0.6a
    CMSG_PET_NAME_QUERY                             = 0xF180, // 4.0.6a
    SMSG_PET_NAME_QUERY_RESPONSE                    = 0x68AC, // 4.0.6a
    CMSG_GUILD_QUERY                                = 0xAFC4, // 4.0.6a
    SMSG_GUILD_QUERY_RESPONSE                       = 0x3F80, // 4.0.6a
    CMSG_ITEM_QUERY_SINGLE                          = 0x056, //
    CMSG_ITEM_QUERY_MULTIPLE                        = 0x057, //
    SMSG_ITEM_QUERY_SINGLE_RESPONSE                 = 0x0C4E, // 4.0.6a
    SMSG_ITEM_QUERY_MULTIPLE_RESPONSE               = 0x059, //
    CMSG_PAGE_TEXT_QUERY                            = 0xAC8C, // 4.0.6a
    SMSG_PAGE_TEXT_QUERY_RESPONSE                   = 0xB084, // 4.0.6a
    CMSG_QUEST_QUERY                                = 0xEFE8, // 4.0.6a
    SMSG_QUEST_QUERY_RESPONSE                       = 0x7BA0, // 4.0.6a
    CMSG_GAMEOBJECT_QUERY                           = 0x72A0, // 4.0.6a
    SMSG_GAMEOBJECT_QUERY_RESPONSE                  = 0xF4E8, // 4.0.6a
    CMSG_CREATURE_QUERY                             = 0x268C, // 4.0.6a
    SMSG_CREATURE_QUERY_RESPONSE                    = 0xE6AC, // 4.0.6a
    CMSG_WHO                                        = 0xA4CC, // 4.0.6a
    SMSG_WHO                                        = 0xBE8C, // 4.0.6a
    CMSG_WHOIS                                      = 0x2180, // 4.0.6a
    SMSG_WHOIS                                      = 0xB1A4, // 4.0.6a
    CMSG_CONTACT_LIST                               = 0xEAA4, // 4.0.6a
    SMSG_CONTACT_LIST                               = 0x748C, // 4.0.6a
    SMSG_FRIEND_STATUS                              = 0xF68C, // 4.0.6a
    CMSG_ADD_FRIEND                                 = 0x3980, // 4.0.6a
    CMSG_DEL_FRIEND                                 = 0x2980, // 4.0.6a
    CMSG_SET_CONTACT_NOTES                          = 0x7DCC, // 4.0.6a
    CMSG_ADD_IGNORE                                 = 0x6780, // 4.0.6a
    CMSG_DEL_IGNORE                                 = 0xF384, // 4.0.6a
    CMSG_GROUP_INVITE                               = 0x27C0, // 4.0.6a
    SMSG_GROUP_INVITE                               = 0xA8A8, // 4.0.6a
    CMSG_GROUP_CANCEL                               = 0x070, //
    SMSG_GROUP_CANCEL                               = 0x6AAC, // 4.0.6a
    CMSG_GROUP_ACCEPT                               = 0x368C, // 4.0.6a
    CMSG_GROUP_DECLINE                              = 0xB4CC, // 4.0.6a
    SMSG_GROUP_DECLINE                              = 0xABAC, // 4.0.6a
    CMSG_GROUP_UNINVITE                             = 0x4F74, // 4.0.6a
    CMSG_GROUP_UNINVITE_GUID                        = 0xE3C8, // 4.0.6a
    SMSG_GROUP_UNINVITE                             = 0x3ACC, // 4.0.6a
    CMSG_GROUP_SET_LEADER                           = 0xB6E0, // 4.0.6a
    SMSG_GROUP_SET_LEADER                           = 0xE88C, // 4.0.6a
    CMSG_LOOT_METHOD                                = 0xFCCC, // 4.0.6a
    CMSG_GROUP_DISBAND                              = 0xBE88, // 4.0.6a
    SMSG_GROUP_DESTROYED                            = 0x22CC, // 4.0.6a
    SMSG_GROUP_LIST                                 = 0x6D8C, // 4.0.6a
    SMSG_PARTY_MEMBER_STATS                         = 0x29AC, // 4.0.6a
    SMSG_PARTY_COMMAND_RESULT                       = 0x26E0, // 4.0.6a
    UMSG_UPDATE_GROUP_MEMBERS                       = 0x080, //
    CMSG_GUILD_CREATE                               = 0x2219, // 4.0.6a
    CMSG_GUILD_INVITE                               = 0x2DA8, // 4.0.6a
    SMSG_GUILD_INVITE                               = 0x010C, // 4.0.6a
    CMSG_GUILD_ACCEPT                               = 0x3729, // 4.0.6a
    CMSG_GUILD_DECLINE                              = 0x352D, // 4.0.6a
    SMSG_GUILD_DECLINE                              = 0x7DEC, // 4.0.6a
    CMSG_GUILD_INFO                                 = 0x6884, // 4.0.6a
    SMSG_GUILD_INFO                                 = 0x20A8, // 4.0.6a
    CMSG_GUILD_ROSTER                               = 0xB2A4, // 4.0.6a
    SMSG_GUILD_ROSTER                               = 0x4D5C, // 4.0.6a
    CMSG_GUILD_PROMOTE                              = 0x2109, // 4.0.6a
    CMSG_GUILD_DEMOTE                               = 0x330D, // 4.0.6a
    CMSG_GUILD_LEAVE                                = 0x3329, // 4.0.6a
    CMSG_GUILD_REMOVE                               = 0x312D, // 4.0.6a
    CMSG_GUILD_DISBAND                              = 0x372D, // 4.0.6a
    CMSG_GUILD_LEADER                               = 0x2650, // 4.0.6a
    CMSG_GUILD_MOTD                                 = 0x272D, // 4.0.6a
    SMSG_GUILD_EVENT                                = 0xB7C4, // 4.0.6a
    SMSG_GUILD_COMMAND_RESULT                       = 0x23C0, // 4.0.6a
    UMSG_UPDATE_GUILD                               = 0x094, // (OUTDATED)
    CMSG_MESSAGECHAT                                = 0x095, //
    SMSG_MESSAGECHAT                                = 0x61E4, // 4.0.6a
    CMSG_JOIN_CHANNEL                               = 0x0002, // 4.0.6a
    CMSG_LEAVE_CHANNEL                              = 0x000B, // 4.0.6a
    SMSG_CHANNEL_NOTIFY                             = 0x7CAC, // 4.0.6a
    CMSG_CHANNEL_LIST                               = 0x7FE0, // 4.0.6a
    SMSG_CHANNEL_LIST                               = 0x69E0, // 4.0.6a
    CMSG_CHANNEL_PASSWORD                           = 0x080A, // 4.0.6a
    CMSG_CHANNEL_SET_OWNER                          = 0x0800, // 4.0.6a
    CMSG_CHANNEL_OWNER                              = 0x0848, // 4.0.6a
    CMSG_CHANNEL_MODERATOR                          = 0x0828, // 4.0.6a
    CMSG_CHANNEL_UNMODERATOR                        = 0x0809, // 4.0.6a
    CMSG_CHANNEL_MUTE                               = 0x0023, // 4.0.6a
    CMSG_CHANNEL_UNMUTE                             = 0x0841, // 4.0.6a
    CMSG_CHANNEL_INVITE                             = 0x0020, // 4.0.6a
    CMSG_CHANNEL_KICK                               = 0x0068, // 4.0.6a
    CMSG_CHANNEL_BAN                                = 0x000A, // 4.0.6a
    CMSG_CHANNEL_UNBAN                              = 0x0048, // 4.0.6a
    CMSG_CHANNEL_ANNOUNCEMENTS                      = 0x004B, // 4.0.6a
    CMSG_CHANNEL_MODERATE                           = 0x0A8, //
    SMSG_UPDATE_OBJECT                              = 0x3780, // 4.0.6a
    SMSG_DESTROY_OBJECT                             = 0x2AA0, // 4.0.6a
    CMSG_USE_ITEM                                   = 0x7080, // 4.0.6a
    CMSG_OPEN_ITEM                                  = 0xA2A8, // 4.0.6a
    CMSG_READ_ITEM                                  = 0xF3C0, // 4.0.6a
    SMSG_READ_ITEM_OK                               = 0xA988, // 4.0.6a
    SMSG_READ_ITEM_FAILED                           = 0xA4EC, // 4.0.6a
    SMSG_ITEM_COOLDOWN                              = 0x6CC8, // 4.0.6a
    CMSG_GAMEOBJ_USE                                = 0x29E4, // 4.0.6a
    CMSG_DESTROY_ITEMS                              = 0xB8A8, // 4.0.6a
    SMSG_GAMEOBJECT_CUSTOM_ANIM                     = 0x36A0, // 4.0.6a
    CMSG_AREATRIGGER                                = 0xADA8, // 4.0.6a
    MSG_MOVE_START_FORWARD                          = 0xEBAC, // 4.0.6a
    MSG_MOVE_START_BACKWARD                         = 0x72E4, // 4.0.6a
    MSG_MOVE_STOP                                   = 0x34E0, // 4.0.6a
    MSG_MOVE_START_STRAFE_LEFT                      = 0x60E8, // 4.0.6a
    MSG_MOVE_START_STRAFE_RIGHT                     = 0x7DA4, // 4.0.6a
    MSG_MOVE_STOP_STRAFE                            = 0xF9A8, // 4.0.6a
    MSG_MOVE_JUMP                                   = 0x65AC, // 4.0.6a
    MSG_MOVE_START_TURN_LEFT                        = 0xB8C8, // 4.0.6a
    MSG_MOVE_START_TURN_RIGHT                       = 0xF9E4, // 4.0.6a
    MSG_MOVE_STOP_TURN                              = 0xE2E8, // 4.0.6a
    MSG_MOVE_START_PITCH_UP                         = 0x60E4, // 4.0.6a
    MSG_MOVE_START_PITCH_DOWN                       = 0xADC4, // 4.0.6a
    MSG_MOVE_STOP_PITCH                             = 0x28E8, // 4.0.6a
    MSG_MOVE_SET_RUN_MODE                           = 0xE7A8, // 4.0.6a
    MSG_MOVE_SET_WALK_MODE                          = 0x3FAC, // 4.0.6a
    MSG_MOVE_TOGGLE_LOGGING                         = 0x0C4, //
    MSG_MOVE_TELEPORT                               = 0x24E4, // 4.0.6a
    MSG_MOVE_TELEPORT_CHEAT                         = 0xE7EC, // 4.0.6a
    MSG_MOVE_TELEPORT_ACK                           = 0x6DAC, // 4.0.6a
    MSG_MOVE_TOGGLE_FALL_LOGGING                    = 0x0C8, //
    MSG_MOVE_FALL_LAND                              = 0xAFAC, // 4.0.6a
    MSG_MOVE_START_SWIM                             = 0x26C0, // 4.0.6a
    MSG_MOVE_STOP_SWIM                              = 0xFDE8, // 4.0.6a
    MSG_MOVE_SET_RUN_SPEED_CHEAT                    = 0x0CC, //
    MSG_MOVE_SET_RUN_SPEED                          = 0x64A0, // 4.0.6a
    MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT               = 0x0CE, //
    MSG_MOVE_SET_RUN_BACK_SPEED                     = 0xB5EC, // 4.0.6a
    MSG_MOVE_SET_WALK_SPEED_CHEAT                   = 0x0D0, //
    MSG_MOVE_SET_WALK_SPEED                         = 0xF284, // 4.0.6a
    MSG_MOVE_SET_SWIM_SPEED_CHEAT                   = 0x0D2, //
    MSG_MOVE_SET_SWIM_SPEED                         = 0x2380, // 4.0.6a
    MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT              = 0x0D4, //
    MSG_MOVE_SET_SWIM_BACK_SPEED                    = 0xB0AC, // 4.0.6a
    MSG_MOVE_SET_ALL_SPEED_CHEAT                    = 0x0D6, //
    MSG_MOVE_SET_TURN_RATE_CHEAT                    = 0x0D7, //
    MSG_MOVE_SET_TURN_RATE                          = 0xA3A8, // 4.0.6a
    MSG_MOVE_TOGGLE_COLLISION_CHEAT                 = 0x0028, // ???
    MSG_MOVE_SET_FACING                             = 0xABC4, // 4.0.6a
    MSG_MOVE_SET_PITCH                              = 0xEBA0, // 4.0.6a
    MSG_MOVE_WORLDPORT_ACK                          = 0x2FC0, // 4.0.6a
    SMSG_MONSTER_MOVE                               = 0xF1A4, // 4.0.6a
    SMSG_MOVE_WATER_WALK                            = 0x2E84, // 4.0.6a
    SMSG_MOVE_LAND_WALK                             = 0x2084, // 4.0.6a
    MSG_MOVE_SET_RAW_POSITION_ACK                   = 0xF4A0, // 4.0.6a
    CMSG_MOVE_SET_RAW_POSITION                      = 0xF0C8, // 4.0.6a
    SMSG_FORCE_RUN_SPEED_CHANGE                     = 0xF1CC, // 4.0.6a
    CMSG_FORCE_RUN_SPEED_CHANGE_ACK                 = 0x26C8, // 4.0.6a
    SMSG_FORCE_RUN_BACK_SPEED_CHANGE                = 0x0E4, //
    CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK            = 0x78E4, // 4.0.6a
    SMSG_FORCE_SWIM_SPEED_CHANGE                    = 0xF5A0, // 4.0.6a
    CMSG_FORCE_SWIM_SPEED_CHANGE_ACK                = 0xB1A0, // 4.0.6a
    SMSG_FORCE_MOVE_ROOT                            = 0x2F88, // 4.0.6a
    CMSG_FORCE_MOVE_ROOT_ACK                        = 0x7184, // 4.0.6a
    SMSG_FORCE_MOVE_UNROOT                          = 0x30A0, // 4.0.6a
    CMSG_FORCE_MOVE_UNROOT_ACK                      = 0x7FA8, // 4.0.6a
    MSG_MOVE_ROOT                                   = 0xABA8, // 4.0.6a
    MSG_MOVE_UNROOT                                 = 0x2088, // 4.0.6a
    MSG_MOVE_HEARTBEAT                              = 0x22EC, // 4.0.6a
    SMSG_MOVE_KNOCK_BACK                            = 0xB180, // 4.0.6a
    CMSG_MOVE_KNOCK_BACK_ACK                        = 0xF580, // 4.0.6a
    MSG_MOVE_KNOCK_BACK                             = 0xB0E8, // 4.0.6a
    SMSG_MOVE_FEATHER_FALL                          = 0x6088, // 4.0.6a
    SMSG_MOVE_NORMAL_FALL                           = 0x6CE0, // 4.0.6a
    SMSG_MOVE_SET_HOVER                             = 0x6AE0, // 4.0.6a
    SMSG_MOVE_UNSET_HOVER                           = 0x3FE0, // 4.0.6a
    CMSG_MOVE_HOVER_ACK                             = 0xF4CC, // 4.0.6a
    MSG_MOVE_HOVER                                  = 0x2FCC, // 4.0.6a
    CMSG_TRIGGER_CINEMATIC_CHEAT                    = 0x0F8, //
    CMSG_OPENING_CINEMATIC                          = 0xB1E8, // 4.0.6a
    SMSG_TRIGGER_CINEMATIC                          = 0x73A4, // 4.0.6a
    CMSG_NEXT_CINEMATIC_CAMERA                      = 0xB2CC, // 4.0.6a
    CMSG_COMPLETE_CINEMATIC                         = 0x2ACC, // 4.0.6a
    SMSG_TUTORIAL_FLAGS                             = 0x3384, // 4.0.6a
    CMSG_TUTORIAL_FLAG                              = 0xE4CC, // 4.0.6a
    CMSG_TUTORIAL_CLEAR                             = 0xA5E4, // 4.0.6a
    CMSG_TUTORIAL_RESET                             = 0xDE75, // 4.0.6a
    CMSG_STANDSTATECHANGE                           = 0xFC88, // 4.0.6a
    CMSG_EMOTE                                      = 0xFAC4, // 4.0.6a
    SMSG_EMOTE                                      = 0xEEA0, // 4.0.6a
    CMSG_TEXT_EMOTE                                 = 0xE9E0, // 4.0.6a
    SMSG_TEXT_EMOTE                                 = 0xBB8C, // 4.0.6a
    CMSG_AUTOEQUIP_GROUND_ITEM                      = 0x106, //
    CMSG_AUTOSTORE_GROUND_ITEM                      = 0x2FC8, // 4.0.6a
    CMSG_AUTOSTORE_LOOT_ITEM                        = 0xB2E8, // 4.0.6a
    CMSG_STORE_LOOT_IN_SLOT                         = 0x7FCC, // 4.0.6a
    CMSG_AUTOEQUIP_ITEM                             = 0xE1C0, // 4.0.6a
    CMSG_AUTOSTORE_BAG_ITEM                         = 0xEDCC, // 4.0.6a
    CMSG_SWAP_ITEM                                  = 0xE8AC, // 4.0.6a
    CMSG_SWAP_INV_ITEM                              = 0x3EC4, // 4.0.6a
    CMSG_SPLIT_ITEM                                 = 0xFDAC, // 4.0.6a
    CMSG_AUTOEQUIP_ITEM_SLOT                        = 0xE8A8, // 4.0.6a
    OBSOLETE_DROP_ITEM                              = 0x110, //
    CMSG_DESTROYITEM                                = 0xB8A8, // 4.0.6a
    SMSG_INVENTORY_CHANGE_FAILURE                   = 0xAFCC, // 4.0.6a
    SMSG_OPEN_CONTAINER                             = 0x1C5F, // ???
    CMSG_INSPECT                                    = 0x78A8, // 4.0.6a
    SMSG_INSPECT                                    = 0x7AC8, // 4.0.6a
    CMSG_INITIATE_TRADE                             = 0x0413, // 4.0.6a
    CMSG_BEGIN_TRADE                                = 0x0F93, // 4.0.6a
    CMSG_BUSY_TRADE                                 = 0x118, //
    CMSG_IGNORE_TRADE                               = 0x119, //
    CMSG_ACCEPT_TRADE                               = 0x0891, // 4.0.6a
    CMSG_UNACCEPT_TRADE                             = 0x0811, // 4.0.6a
    CMSG_CANCEL_TRADE                               = 0x0013, // 4.0.6a
    CMSG_SET_TRADE_ITEM                             = 0x0A11, // 4.0.6a
    CMSG_CLEAR_TRADE_ITEM                           = 0x0213, // 4.0.6a
    CMSG_SET_TRADE_GOLD                             = 0x0C13, // 4.0.6a
    SMSG_TRADE_STATUS                               = 0x494E, // 4.0.6a
    SMSG_TRADE_STATUS_EXTENDED                      = 0x400C, // 4.0.6a
    SMSG_INITIALIZE_FACTIONS                        = 0x25C0, // 4.0.6a
    SMSG_SET_FACTION_VISIBLE                        = 0x3988, // 4.0.6a
    SMSG_SET_FACTION_STANDING                       = 0x718C, // 4.0.6a
    CMSG_SET_FACTION_ATWAR                          = 0x125, //
    CMSG_SET_FACTION_CHEAT                          = 0x126, //
    SMSG_SET_PROFICIENCY                            = 0xBBA8, // 4.0.6a
    CMSG_SET_ACTION_BUTTON                          = 0x72E8, // 4.0.6a
    SMSG_ACTION_BUTTONS                             = 0x2CCC, // 4.0.6a
    SMSG_INITIAL_SPELLS                             = 0x6584, // 4.0.6a
    SMSG_LEARNED_SPELL                              = 0x76E8, // 4.0.6a
    SMSG_SUPERCEDED_SPELL                           = 0xE8E4, // 4.0.6a
    CMSG_NEW_SPELL_SLOT                             = 0x12D, //
    CMSG_CAST_SPELL                                 = 0x65C4, // 4.0.6a
    CMSG_CANCEL_CAST                                = 0xA1C0, // 4.0.6a
    SMSG_CAST_FAILED                                = 0x2A8C, // 4.0.6a
    SMSG_SPELL_START                                = 0x6BA8, // 4.0.6a
    SMSG_SPELL_GO                                   = 0x30C0, // 4.0.6a
    SMSG_SPELL_FAILURE                              = 0xF9CC, // 4.0.6a
    SMSG_SPELL_COOLDOWN                             = 0xF3E8, // 4.0.6a
    SMSG_COOLDOWN_EVENT                             = 0xEAEC, // 4.0.6a
    CMSG_CANCEL_AURA                                = 0x7684, // 4.0.6a
    SMSG_EQUIPMENT_SET_SAVED                        = 0xB0C0, // 4.0.6a
    SMSG_PET_CAST_FAILED                            = 0xA9CC, // 4.0.6a
    MSG_CHANNEL_START                               = 0x2BAC, // 4.0.6a
    MSG_CHANNEL_UPDATE                              = 0x62AC, // 4.0.6a
    CMSG_CANCEL_CHANNELLING                         = 0xA780, // 4.0.6a
    SMSG_AI_REACTION                                = 0x31CC, // 4.0.6a
    CMSG_SET_SELECTION                              = 0x6488, // 4.0.6a
    CMSG_EQUIPMENT_SET_DELETE                       = 0xAEA0, // 4.0.6a
    CMSG_INSTANCE_LOCK_WARNING_RESPONSE             = 0x13F, //
    CMSG_UNUSED2                                    = 0x140, //
    CMSG_ATTACKSWING                                = 0x74A8, // 4.0.6a
    CMSG_ATTACKSTOP                                 = 0x62C4, // 4.0.6a
    SMSG_ATTACKSTART                                = 0xB68C, // 4.0.6a
    SMSG_ATTACKSTOP                                 = 0x6DCC, // 4.0.6a
    SMSG_ATTACKSWING_NOTINRANGE                     = 0x36C4, // 4.0.6a
    SMSG_ATTACKSWING_BADFACING                      = 0x67A8, // 4.0.6a
    SMSG_INSTANCE_LOCK_WARNING_QUERY                = 0x147, //
    SMSG_ATTACKSWING_DEADTARGET                     = 0xA7C4, // 4.0.6a
    SMSG_ATTACKSWING_CANT_ATTACK                    = 0x6188, // 4.0.6a
    SMSG_ATTACKERSTATEUPDATE                        = 0xBBC0, // 4.0.6a
    SMSG_BATTLEFIELD_PORT_DENIED                    = 0x14B, //
    SMSG_DAMAGE_DONE_OBSOLETE                       = 0x14C, //
    SMSG_UNIT_SPELLCAST_START                       = 0xBDE0, // 4.0.6a
    SMSG_CANCEL_COMBAT                              = 0xBAE4, // 4.0.6a
    SMSG_SPELLBREAKLOG                              = 0xBDAC, // 4.0.6a
    SMSG_SPELLHEALLOG                               = 0x6E84, // 4.0.6a
    SMSG_SPELLENERGIZELOG                           = 0xF0EC, // 4.0.6a
    SMSG_BREAK_TARGET                               = 0x2488, // 4.0.6a
    CMSG_SAVE_PLAYER                                = 0x153, //
    CMSG_SETDEATHBINDPOINT                          = 0x154, //
    SMSG_BINDPOINTUPDATE                            = 0xA9A0, // 4.0.6a
    CMSG_GETDEATHBINDZONE                           = 0x156, //
    SMSG_BINDZONEREPLY                              = 0xACAC, // 4.0.6a
    SMSG_PLAYERBOUND                                = 0x6BCC, // 4.0.6a
    SMSG_CLIENT_CONTROL_UPDATE                      = 0x3C84, // 4.0.6a
    CMSG_REPOP_REQUEST                              = 0xA9E4, // 4.0.6a
    SMSG_RESURRECT_REQUEST                          = 0xF3A0, // 4.0.6a
    CMSG_RESURRECT_RESPONSE                         = 0xBBE8, // 4.0.6a
    CMSG_LOOT                                       = 0xFCEC, // 4.0.6a
    CMSG_LOOT_MONEY                                 = 0x79E0, // 4.0.6a
    CMSG_LOOT_RELEASE                               = 0x3CE8, // 4.0.6a
    SMSG_LOOT_RESPONSE                              = 0xF38C, // 4.0.6a
    SMSG_LOOT_RELEASE_RESPONSE                      = 0x23C8, // 4.0.6a
    SMSG_LOOT_REMOVED                               = 0x6F88, // 4.0.6a
    SMSG_LOOT_MONEY_NOTIFY                          = 0x67C0, // 4.0.6a
    SMSG_LOOT_ITEM_NOTIFY                           = 0xAECC, // 4.0.6a
    SMSG_LOOT_CLEAR_MONEY                           = 0x3480, // 4.0.6a
    SMSG_ITEM_PUSH_RESULT                           = 0xFBE8, // 4.0.6a
    SMSG_DUEL_REQUESTED                             = 0x3FC8, // 4.0.6a
    SMSG_DUEL_OUTOFBOUNDS                           = 0x68C0, // 4.0.6a
    SMSG_DUEL_INBOUNDS                              = 0xECA4, // 4.0.6a
    SMSG_DUEL_COMPLETE                              = 0xFCE8, // 4.0.6a
    SMSG_DUEL_WINNER                                = 0x79E4, // 4.0.6a
    CMSG_DUEL_ACCEPTED                              = 0xA688, // 4.0.6a
    CMSG_DUEL_CANCELLED                             = 0x6F8C, // 4.0.6a
    SMSG_MOUNTRESULT                                = 0x2AEC, // 4.0.6a (NOT SHURE)
    SMSG_DISMOUNTRESULT                             = 0xF9C0, // 4.0.6a (NOT SHURE)
    SMSG_PUREMOUNT_CANCELLED_OBSOLETE               = 0x054E, // 4.0.6a (ERR_REMOVE_FROM_PVP_QUEUE_* events)
    CMSG_MOUNTSPECIAL_ANIM                          = 0x2EE4, // 4.0.6a
    SMSG_MOUNTSPECIAL_ANIM                          = 0x2388, // 4.0.6a
    SMSG_PET_TAME_FAILURE                           = 0xFDA8, // 4.0.6a
    CMSG_PET_SET_ACTION                             = 0x3C8C, // 4.0.6a
    CMSG_PET_ACTION                                 = 0xAFC0, // 4.0.6a
    CMSG_PET_ABANDON                                = 0xA480, // 4.0.6a
    CMSG_PET_RENAME                                 = 0x38E8, // 4.0.6a
    SMSG_PET_NAME_INVALID                           = 0x178, //
    SMSG_PET_SPELLS                                 = 0xB780, // 4.0.6a
    SMSG_PET_MODE                                   = 0x79C0, // 4.0.6a
    CMSG_GOSSIP_HELLO                               = 0x74C8, // 4.0.6a
    CMSG_GOSSIP_SELECT_OPTION                       = 0xFF88, // 4.0.6a
    SMSG_GOSSIP_MESSAGE                             = 0xBBC8, // 4.0.6a
    SMSG_GOSSIP_COMPLETE                            = 0xF0AC, // 4.0.6a
    CMSG_NPC_TEXT_QUERY                             = 0xA2EC, // 4.0.6a
    SMSG_NPC_TEXT_UPDATE                            = 0xB2AC, // 4.0.6a
    SMSG_NPC_WONT_TALK                              = 0x181, //
    CMSG_QUESTGIVER_STATUS_QUERY                    = 0xFDEC, // 4.0.6a
    SMSG_QUESTGIVER_STATUS                          = 0x7988, // 4.0.6a
    CMSG_QUESTGIVER_HELLO                           = 0x36AC, // 4.0.6a
    SMSG_QUESTGIVER_QUEST_LIST                      = 0x2B88, // 4.0.6a
    CMSG_QUESTGIVER_QUERY_QUEST                     = 0x2CC0, // 4.0.6a
    CMSG_QUESTGIVER_QUEST_AUTOLAUNCH                = 0x187, //
    SMSG_QUESTGIVER_QUEST_DETAILS                   = 0x68A0, // 4.0.6a
    CMSG_QUESTGIVER_ACCEPT_QUEST                    = 0x20C4, // 4.0.6a
    CMSG_QUESTGIVER_COMPLETE_QUEST                  = 0xB5AC, // 4.0.6a
    SMSG_QUESTGIVER_REQUEST_ITEMS                   = 0x6EE0, // 4.0.6a
    CMSG_QUESTGIVER_REQUEST_REWARD                  = 0x23A8, // 4.0.6a
    SMSG_QUESTGIVER_OFFER_REWARD                    = 0x3FCC, // 4.0.6a
    CMSG_QUESTGIVER_CHOOSE_REWARD                   = 0x6AC0, // 4.0.6a
    SMSG_QUESTGIVER_QUEST_INVALID                   = 0x18F, //
    CMSG_QUESTGIVER_CANCEL                          = 0x61EC, /// 4.0.6a (SMSG_QUESTLOG_FULL SAME ?)
    SMSG_QUESTGIVER_QUEST_COMPLETE                  = 0x050E, // 4.0.6a
    SMSG_QUESTGIVER_QUEST_FAILED                    = 0xA084, // 4.0.6a
    CMSG_QUESTLOG_SWAP_QUEST                        = 0x193, //
    CMSG_QUESTLOG_REMOVE_QUEST                      = 0xEDA8, // 4.0.6a
    SMSG_QUESTLOG_FULL                              = 0x61EC, /// 4.0.6a (CMSG_QUESTGIVER_CANCEL SAME ?)
    SMSG_QUESTUPDATE_FAILED                         = 0xE588, // 4.0.6a
    SMSG_QUESTUPDATE_FAILEDTIMER                    = 0xF7CC, // 4.0.6a
    SMSG_QUESTUPDATE_COMPLETE                       = 0xEDA0, // 4.0.6a
    SMSG_QUESTUPDATE_ADD_KILL                       = 0xADA0, // 4.0.6a
    SMSG_QUESTUPDATE_ADD_ITEM                       = 0x19A, //
    CMSG_QUEST_CONFIRM_ACCEPT                       = 0x6FCC, // 4.0.6a
    SMSG_QUEST_CONFIRM_ACCEPT                       = 0x7C8C, // 4.0.6a
    CMSG_PUSHQUESTTOPARTY                           = 0x29E8, // 4.0.6a
    CMSG_LIST_INVENTORY                             = 0xEDC8, // 4.0.6a
    SMSG_LIST_INVENTORY                             = 0xF8AC, // 4.0.6a
    CMSG_SELL_ITEM                                  = 0x63A4, // 4.0.6a
    SMSG_SELL_ITEM                                  = 0x37AC, // 4.0.6a
    CMSG_BUY_ITEM                                   = 0xEA84, // 4.0.6a
    CMSG_BUY_ITEM_IN_SLOT                           = 0x1A3, //
    SMSG_BUY_ITEM                                   = 0x69CC, // 4.0.6a
    SMSG_BUY_FAILED                                 = 0x6CE8, // 4.0.6a
    CMSG_TAXICLEARALLNODES                          = 0x1A6, // (NEVER USED)
    CMSG_TAXIENABLEALLNODES                         = 0x1A7, // (NEVER USED)
    CMSG_TAXISHOWNODES                              = 0xB8E8, // 4.0.6a
    SMSG_SHOWTAXINODES                              = 0x2B84, // 4.0.6a
    CMSG_TAXINODE_STATUS_QUERY                      = 0xA1EC, // 4.0.6a
    SMSG_TAXINODE_STATUS                            = 0x77E8, // 4.0.6a
    CMSG_TAXIQUERYAVAILABLENODES                    = 0xBE8E, // 4.0.6a
    CMSG_ACTIVATETAXI                               = 0x39A4, // 4.0.6a
    SMSG_ACTIVATETAXIREPLY                          = 0x7A84, // 4.0.6a
    SMSG_NEW_TAXI_PATH                              = 0xE5E4, // 4.0.6a
    CMSG_TRAINER_LIST                               = 0xE5AC, // 4.0.6a
    SMSG_TRAINER_LIST                               = 0xBBE0, // 4.0.6a
    CMSG_TRAINER_BUY_SPELL                          = 0xFDC8, // 4.0.6a
    SMSG_TRAINER_BUY_SUCCEEDED                      = 0x1B3, //
    SMSG_TRAINER_BUY_FAILED                         = 0x1B4, //
    CMSG_BINDER_ACTIVATE                            = 0xA48C, // 4.0.6a
    SMSG_PLAYERBINDERROR                            = 0xEEC8, // 4.0.6a
    CMSG_BANKER_ACTIVATE                            = 0xE7E0, // 4.0.6a
    SMSG_SHOW_BANK                                  = 0x27A4, // 4.0.6a
    CMSG_BUY_BANK_SLOT                              = 0x2BA0, // 4.0.6a
    SMSG_BUY_BANK_SLOT_RESULT                       = 0x1BA, //
    CMSG_PETITION_SHOWLIST                          = 0xFCC4, // 4.0.6a
    SMSG_PETITION_SHOWLIST                          = 0xFCC0, // 4.0.6a
    CMSG_PETITION_BUY                               = 0xB3E4, // 4.0.6a
    CMSG_PETITION_SHOW_SIGNATURES                   = 0x2CA8, // 4.0.6a
    SMSG_PETITION_SHOW_SIGNATURES                   = 0xE2E0, // 4.0.6a
    CMSG_PETITION_SIGN                              = 0x3AA0, // 4.0.6a
    SMSG_PETITION_SIGN_RESULTS                      = 0xA1A4, // 4.0.6a
    MSG_PETITION_DECLINE                            = 0x32E0, // 4.0.6a
    CMSG_OFFER_PETITION                             = 0x7AC4, // 4.0.6a
    CMSG_TURN_IN_PETITION                           = 0xA584, // 4.0.6a
    SMSG_TURN_IN_PETITION_RESULTS                   = 0x35AC, // 4.0.6a
    CMSG_PETITION_QUERY                             = 0xB1AC, // 4.0.6a
    SMSG_PETITION_QUERY_RESPONSE                    = 0xFB80, // 4.0.6a
    SMSG_FISH_NOT_HOOKED                            = 0x39EC, // 4.0.6a
    SMSG_FISH_ESCAPED                               = 0xF080, // 4.0.6a
    CMSG_BUG                                        = 0x34AC, // 4.0.6a
    SMSG_NOTIFICATION                               = 0xBC88, // 4.0.6a
    CMSG_PLAYED_TIME                                = 0xF480, // 4.0.6a
    SMSG_PLAYED_TIME                                = 0xE4C8, // 4.0.6a
    CMSG_QUERY_TIME                                 = 0xB1C0, // 4.0.6a
    SMSG_QUERY_TIME_RESPONSE                        = 0xF1AC, // 4.0.6a
    SMSG_LOG_XPGAIN                                 = 0xB880, // 4.0.6a
    SMSG_AURACASTLOG                                = 0x1D1, //
    CMSG_RECLAIM_CORPSE                             = 0x7CC8, // 4.0.6a
    CMSG_WRAP_ITEM                                  = 0x6E54, // 
    SMSG_LEVELUP_INFO                               = 0xB9C4, // 4.0.6a
    MSG_MINIMAP_PING                                = 0xC475, //
    SMSG_RESISTLOG                                  = 0x1D6, //
    SMSG_ENCHANTMENTLOG                             = 0xF5AC, // 4.0.6a
    CMSG_SET_SKILL_CHEAT                            = 0x1D8, //
    SMSG_START_MIRROR_TIMER                         = 0xB4A8, // 4.0.6a
    SMSG_PAUSE_MIRROR_TIMER                         = 0x21EC, // 4.0.6a
    SMSG_STOP_MIRROR_TIMER                          = 0xA68C, // 4.0.6a
    CMSG_PING                                       = 0x064E, // 4.0.6a
    SMSG_PONG                                       = 0xA01B, // 4.0.6a
    SMSG_CLEAR_COOLDOWN                             = 0x36CC, // 4.0.6a
    SMSG_GAMEOBJECT_PAGETEXT                        = 0xE5C8, // 4.0.6a
    CMSG_SETSHEATHED                                = 0xAAE4, // 4.0.6a
    SMSG_COOLDOWN_CHEAT                             = 0xAAA4, // 4.0.6a
    SMSG_SPELL_DELAYED                              = 0xA3E8, // 4.0.6a
    CMSG_QUEST_POI_QUERY                            = 0x7DE0, // 4.0.6a
    SMSG_QUEST_POI_QUERY_RESPONSE                   = 0x6AEC, // 4.0.6a
    CMSG_GHOST                                      = 0x1E5, //
    CMSG_GM_INVIS                                   = 0x1E6, //
    SMSG_INVALID_PROMOTION_CODE                     = 0x69AC, // 4.0.6a
    MSG_GM_BIND_OTHER                               = 0x1E8, //
    MSG_GM_SUMMON                                   = 0x1E9, //
    SMSG_ITEM_TIME_UPDATE                           = 0x66A4, // 4.0.6a
    SMSG_ITEM_ENCHANT_TIME_UPDATE                   = 0x66A0, // 4.0.6a
    SMSG_AUTH_CHALLENGE                             = 0x6019, // 4.0.6a
    CMSG_AUTH_SESSION                               = 0x0E0E, // 4.0.6a
    SMSG_AUTH_RESPONSE                              = 0xB28C, // 4.0.6a
    MSG_GM_SHOWLABEL                                = 0x1EF, //
    CMSG_PET_CAST_SPELL                             = 0x2888, // 4.0.6a
    MSG_SAVE_GUILD_EMBLEM                           = 0x31AC, // 4.0.6a
    MSG_TABARDVENDOR_ACTIVATE                       = 0x2C80, // 4.0.6a
    SMSG_PLAY_SPELL_VISUAL                          = 0xFF8C, // 4.0.6a
    CMSG_ZONEUPDATE                                 = 0x33E4, // 4.0.6a
    SMSG_PARTYKILLLOG                               = 0xAB84, // 4.0.6a
    SMSG_COMPRESSED_UPDATE_OBJECT                   = 0xEAC0, // 4.0.6a
    SMSG_PLAY_SPELL_IMPACT                          = 0xA3E4, // 4.0.6a
    SMSG_EXPLORATION_EXPERIENCE                     = 0xA9C4, // 4.0.6a
    CMSG_GM_SET_SECURITY_GROUP                      = 0x1F9, //
    CMSG_GM_NUKE                                    = 0x1FA, //
    MSG_RANDOM_ROLL                                 = 0xB7A4, // 4.0.6a
    SMSG_ENVIRONMENTALDAMAGELOG                     = 0xE1C8, // 4.0.6a
    CMSG_PLAYER_DIFFICULTY_CHANGE                   = 0x7E5D, //
    SMSG_RWHOIS                                     = 0x71C8, // 4.0.6a
    SMSG_LFG_PLAYER_REWARD                          = 0x2C88, // 4.0.6a
    SMSG_LFG_TELEPORT_DENIED                        = 0xEAA0, // 4.0.6a
    CMSG_UNLEARN_SPELL                              = 0x201, // 
    CMSG_UNLEARN_SKILL                              = 0x63C8, // 4.0.6a
    SMSG_REMOVED_SPELL                              = 0x7CA0, // 4.0.6a 
    CMSG_DECHARGE                                   = 0x204, //
    CMSG_GMTICKET_CREATE                            = 0x6380, // 4.0.6a 
    SMSG_GMTICKET_CREATE                            = 0xA8A0, // 4.0.6a 
    CMSG_GMTICKET_UPDATETEXT                        = 0x7F8C, // 4.0.6a 
    SMSG_GMTICKET_UPDATETEXT                        = 0xA5E8, // 4.0.6a 
    SMSG_ACCOUNT_DATA_TIMES                         = 0x7280, // 4.0.6a  
    CMSG_REQUEST_ACCOUNT_DATA                       = 0xEEAC, // 4.0.6a 
    CMSG_UPDATE_ACCOUNT_DATA                        = 0x72A4, // 4.0.6a 
    SMSG_UPDATE_ACCOUNT_DATA                        = 0xF7A0, // 4.0.6a 
    SMSG_CLEAR_FAR_SIGHT_IMMEDIATE                  = 0xBEE4, // 4.0.6a 
    SMSG_PLAYER_DIFFICULTY_CHANGE                   = 0x2A80, // 4.0.6a
    CMSG_GM_TEACH                                   = 0x20F, //
    CMSG_GM_CREATE_ITEM_TARGET                      = 0x210, //
    CMSG_GMTICKET_GETTICKET                         = 0xB4C4, // 4.0.6a
    SMSG_GMTICKET_GETTICKET                         = 0x2284, // 4.0.6a
    CMSG_UNLEARN_TALENTS                            = 0x213, //
    SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT             = 0xEDA4, // 4.0.6a
    SMSG_GAMEOBJECT_DESPAWN_ANIM                    = 0xBFA8, // 4.0.6a
    MSG_CORPSE_QUERY                                = 0xE0C8, // 4.0.6a
    CMSG_GMTICKET_DELETETICKET                      = 0xFBE4, // 4.0.6a
    SMSG_GMTICKET_DELETETICKET                      = 0xF48C, // 4.0.6a
    SMSG_CHAT_WRONG_FACTION                         = 0xBB88, // 4.0.6a
    CMSG_GMTICKET_SYSTEMSTATUS                      = 0xACE0, // 4.0.6a
    SMSG_GMTICKET_SYSTEMSTATUS                      = 0xB9C0, // 4.0.6a
    CMSG_SPIRIT_HEALER_ACTIVATE                     = 0xF3AC, // 4.0.6a
    CMSG_SET_STAT_CHEAT                             = 0x21D, //
    SMSG_QUEST_FORCE_REMOVE                         = 0x21E, // (uint32 questid)
    CMSG_SKILL_BUY_STEP                             = 0x21F, //
    CMSG_SKILL_BUY_RANK                             = 0x220, //
    CMSG_XP_CHEAT                                   = 0x221, //
    SMSG_SPIRIT_HEALER_CONFIRM                      = 0xB9C0, // 4.0.6a
    CMSG_CHARACTER_POINT_CHEAT                      = 0x223, //
    SMSG_GOSSIP_POI                                 = 0xB9AC, // 4.0.6a
    CMSG_CHAT_IGNORED                               = 0xA78C, // 4.0.6a
    CMSG_GM_VISION                                  = 0x226, //
    CMSG_SERVER_COMMAND                             = 0x227, //
    CMSG_GM_SILENCE                                 = 0x228, //
    CMSG_GM_REVEALTO                                = 0x229, //
    CMSG_GM_RESURRECT                               = 0x22A, //
    CMSG_GM_SUMMONMOB                               = 0x22B, //
    CMSG_GM_MOVECORPSE                              = 0x22C, //
    CMSG_GM_FREEZE                                  = 0x22D, //
    CMSG_GM_UBERINVIS                               = 0x22E, //
    CMSG_GM_REQUEST_PLAYER_INFO                     = 0x22F, //
    SMSG_GM_PLAYER_INFO                             = 0x230, //
    CMSG_GUILD_RANK                                 = 0x2709, // 4.0.6a
    CMSG_GUILD_ADD_RANK                             = 0x2309, // 4.0.6a
    CMSG_GUILD_DEL_RANK                             = 0x2129, // 4.0.6a
    CMSG_GUILD_SET_PUBLIC_NOTE                      = 0x234, //
    CMSG_GUILD_SET_OFFICER_NOTE                     = 0x235, //
    SMSG_LOGIN_VERIFY_WORLD                         = 0x28C0, // 4.0.6a
    CMSG_CLEAR_EXPLORATION                          = 0x237, //
    CMSG_SEND_MAIL                                  = 0x2DEC, // 4.0.6a
    SMSG_SEND_MAIL_RESULT                           = 0xE5C0, // 4.0.6a
    CMSG_GET_MAIL_LIST                              = 0xB284, // 4.0.6a
    SMSG_MAIL_LIST_RESULT                           = 0xF1C8, // 4.0.6a
    CMSG_BATTLEFIELD_LIST                           = 0x0508, // 4.0.6a - StrawberryEMU: 0x0093
    SMSG_BATTLEFIELD_LIST                           = 0x490C, // 4.0.6a
    CMSG_BATTLEFIELD_JOIN                           = 0x0C91, // 4.0.6a
    SMSG_BATTLEFIELD_WIN_OBSOLETE                   = 0x23F, //
    SMSG_BATTLEFIELD_LOSE_OBSOLETE                  = 0x240, //
    CMSG_TAXICLEARNODE                              = 0x241, //
    CMSG_TAXIENABLENODE                             = 0x242, //
    CMSG_ITEM_TEXT_QUERY                            = 0xF280, // 4.0.6a
    SMSG_ITEM_TEXT_QUERY_RESPONSE                   = 0x77C8, // 4.0.6a
    CMSG_MAIL_TAKE_MONEY                            = 0xE8EC, // 4.0.6a
    CMSG_MAIL_TAKE_ITEM                             = 0x62A8, // 4.0.6a
    CMSG_MAIL_MARK_AS_READ                          = 0xE8C0, // 4.0.6a
    CMSG_MAIL_RETURN_TO_SENDER                      = 0x65A4, // 4.0.6a
    CMSG_MAIL_DELETE                                = 0x7DE4, // 4.0.6a
    CMSG_MAIL_CREATE_TEXT_ITEM                      = 0xFAE4, // 4.0.6a
    SMSG_SPELLLOGMISS                               = 0xB4A4, // 4.0.6a
    SMSG_SPELLLOGEXECUTE                            = 0xB6E8, // 4.0.6a
    SMSG_DEBUGAURAPROC                              = 0x24D, //
    SMSG_PERIODICAURALOG                            = 0x3388, // 4.0.6a
    SMSG_SPELLDAMAGESHIELD                          = 0x73A0, // 4.0.6a
    SMSG_SPELLNONMELEEDAMAGELOG                     = 0x74AC, // 4.0.6a
    CMSG_LEARN_TALENT                               = 0xA7CC, // 4.0.6a
    SMSG_RESURRECT_FAILED                           = 0x252, //
    CMSG_TOGGLE_PVP                                 = 0x6480, // 4.0.6a
    SMSG_ZONE_UNDER_ATTACK                          = 0xBD80, // 4.0.6a
    MSG_AUCTION_HELLO                               = 0xB3A0, // 4.0.6a
    CMSG_AUCTION_SELL_ITEM                          = 0xEE8C, // 4.0.6a
    CMSG_AUCTION_REMOVE_ITEM                        = 0x3EEC, // 4.0.6a
    CMSG_AUCTION_LIST_ITEMS                         = 0xE48C, // 4.0.6a
    CMSG_AUCTION_LIST_OWNER_ITEMS                   = 0x2D8C, // 4.0.6a
    CMSG_AUCTION_PLACE_BID                          = 0xA6A0, // 4.0.6a
    SMSG_AUCTION_COMMAND_RESULT                     = 0xAAE0, // 4.0.6a
    SMSG_AUCTION_LIST_RESULT                        = 0xA1A8, // 4.0.6a
    SMSG_AUCTION_OWNER_LIST_RESULT                  = 0x3CA8, // 4.0.6a
    SMSG_AUCTION_BIDDER_NOTIFICATION                = 0xACEC, // 4.0.6a
    SMSG_AUCTION_OWNER_NOTIFICATION                 = 0x6C80, // 4.0.6a
    SMSG_PROCRESIST                                 = 0x7E80, // 4.0.6a
    SMSG_STANDSTATE_CHANGE_FAILURE_OBSOLETE         = 0x6DCC, // 4.0.6a
    SMSG_DISPEL_FAILED                              = 0xAAE8, // 4.0.6a
    SMSG_SPELLORDAMAGE_IMMUNE                       = 0x73C8, // 4.0.6a
    CMSG_AUCTION_LIST_BIDDER_ITEMS                  = 0x21C0, // 4.0.6a
    SMSG_AUCTION_BIDDER_LIST_RESULT                 = 0xE5A8, // 4.0.6a
    SMSG_SET_FLAT_SPELL_MODIFIER                    = 0x2BC8, // 4.0.6a
    SMSG_SET_PCT_SPELL_MODIFIER                     = 0xA6E8, // 4.0.6a
    CMSG_SET_AMMO                                   = 0x268, //
    SMSG_CORPSE_RECLAIM_DELAY                       = 0x31C4, // 4.0.6a
    CMSG_SET_ACTIVE_MOVER                           = 0x6CA0, // 4.0.6a
    CMSG_PET_CANCEL_AURA                            = 0xF6C0, // 4.0.6a
    CMSG_PLAYER_AI_CHEAT                            = 0x26C, //
    CMSG_CANCEL_AUTO_REPEAT_SPELL                   = 0x75CC, // 4.0.6a
    MSG_GM_ACCOUNT_ONLINE                           = 0x26E, //
    MSG_LIST_STABLED_PETS                           = 0x6EAC, // 4.0.6a
    CMSG_STABLE_PET                                 = 0x270, //
    CMSG_UNSTABLE_PET                               = 0x271, //
    CMSG_BUY_STABLE_SLOT                            = 0x272, //
    SMSG_STABLE_RESULT                              = 0xEACC, // 4.0.6a
    CMSG_STABLE_REVIVE_PET                          = 0x274, //
    CMSG_STABLE_SWAP_PET                            = 0x275, //
    MSG_QUEST_PUSH_RESULT                           = 0x22A4, // 4.0.6a
    SMSG_PLAY_MUSIC                                 = 0xAE54, // 4.0.6a
    SMSG_PLAY_OBJECT_SOUND                          = 0x7DA0, // 4.0.6a
    CMSG_REQUEST_PET_INFO                           = 0xEAE4, // 4.0.6a
    CMSG_FAR_SIGHT                                  = 0xB2EC, // 4.0.6a
    SMSG_SPELLDISPELLOG                             = 0x27B, //
    SMSG_DAMAGE_CALC_LOG                            = 0xFD84, // 4.0.6a
    CMSG_ENABLE_DAMAGE_LOG                          = 0x27D, //
    CMSG_GROUP_CHANGE_SUB_GROUP                     = 0x3A80, // 4.0.6a
    CMSG_REQUEST_PARTY_MEMBER_STATS                 = 0x70C8, // 4.0.6a
    CMSG_GROUP_SWAP_SUB_GROUP                       = 0x280, //
    CMSG_RESET_FACTION_CHEAT                        = 0x281, //
    CMSG_AUTOSTORE_BANK_ITEM                        = 0xF2AC, // 4.0.6a
    CMSG_AUTOBANK_ITEM                              = 0x66E4, // 4.0.6a
    MSG_QUERY_NEXT_MAIL_TIME                        = 0x25C8, // 4.0.6a
    SMSG_RECEIVED_MAIL                              = 0x75E4, // 4.0.6a
    SMSG_RAID_GROUP_ONLY                            = 0x0554, // 4.0.6a (NOT TESTED)
    CMSG_SET_DURABILITY_CHEAT                       = 0x287, //
    CMSG_SET_PVP_RANK_CHEAT                         = 0x288, //
    CMSG_ADD_PVP_MEDAL_CHEAT                        = 0x289, //
    CMSG_DEL_PVP_MEDAL_CHEAT                        = 0x28A, //
    CMSG_SET_PVP_TITLE                              = 0x28B, //
    SMSG_PVP_CREDIT                                 = 0x37C8, // 4.0.6a
    SMSG_AUCTION_REMOVED_NOTIFICATION               = 0xB1EC, // 4.0.6a
    CMSG_GROUP_RAID_CONVERT                         = 0x628C, // 4.0.6a
    CMSG_GROUP_ASSISTANT_LEADER                     = 0x3F84, // 4.0.6a
    CMSG_BUYBACK_ITEM                               = 0xA4C4, // 4.0.6a
    SMSG_SERVER_MESSAGE                             = 0x78C0, // 4.0.6a
    CMSG_SET_SAVED_INSTANCE_EXTEND                  = 0x2588, // 4.0.6a (lua: SetSavedInstanceExtend)
    SMSG_LFG_OFFER_CONTINUE                         = 0x63EC, // 4.0.6a
    CMSG_MEETINGSTONE_CHEAT                         = 0x294, // (not found since 3.3)
    SMSG_MEETINGSTONE_SETQUEUE                      = 0xED88, // 4.0.6a (string, showed in console // almost 100% sure it's wrong)
    CMSG_MEETINGSTONE_INFO                          = 0xF984, // 4.0.6a (EVENT_LFG_UPDATE)
    SMSG_MEETINGSTONE_COMPLETE                      = 0xF680, // 4.0.6a (EVENT_MAIL_SHOW)
    SMSG_MEETINGSTONE_IN_PROGRESS                   = 0xE7C4, // 4.0.6a (uint32, some UPDATE_COOLDOWN events)
    SMSG_MEETINGSTONE_MEMBER_ADDED                  = 0xB2A8, // 4.0.6a (uint32, errors: ERR_NOT_IN_GROUP (2, 51) and ERR_NOT_IN_RAID (3, 39, 40))
    CMSG_GMTICKETSYSTEM_TOGGLE                      = 0x29A, //
    CMSG_CANCEL_GROWTH_AURA                         = 0xFECC, // 4.0.6a
    SMSG_CANCEL_AUTO_REPEAT                         = 0x3DE0, // 4.0.6a
    SMSG_STANDSTATE_UPDATE                          = 0xE6A8, // 4.0.6a
    SMSG_LOOT_ALL_PASSED                            = 0x6AC4, // 4.0.6a
    SMSG_LOOT_ROLL_WON                              = 0x6280, // 4.0.6a
    CMSG_LOOT_ROLL                                  = 0xBDA8, // 4.0.6a
    SMSG_LOOT_START_ROLL                            = 0xEB84, // 4.0.6a
    SMSG_LOOT_ROLL                                  = 0x66A8, // 4.0.6a
    CMSG_LOOT_MASTER_GIVE                           = 0x2A3, //
    SMSG_LOOT_MASTER_LIST                           = 0xECC4, // 4.0.6a
    SMSG_SET_FORCED_REACTIONS                       = 0x2A5, //
    SMSG_SPELL_FAILED_OTHER                         = 0xE7A4, // 4.0.6a
    SMSG_GAMEOBJECT_RESET_STATE                     = 0x22E0, // 4.0.6a
    CMSG_REPAIR_ITEM                                = 0x39E4, // 4.0.6a
    SMSG_CHAT_PLAYER_NOT_FOUND                      = 0x35A0, // 4.0.6a
    MSG_TALENT_WIPE_CONFIRM                         = 0xBFC4, // 4.0.6a
    SMSG_SUMMON_REQUEST                             = 0x3AE4, // 4.0.6a
    CMSG_SUMMON_RESPONSE                            = 0x6BA0, // 4.0.6a
    MSG_MOVE_TOGGLE_GRAVITY_CHEAT                   = 0x2AD, //
    SMSG_MONSTER_MOVE_TRANSPORT                     = 0x248C, // 4.0.6a
    SMSG_PET_BROKEN                                 = 0x75E0, // 4.0.6a
    MSG_MOVE_FEATHER_FALL                           = 0xB6A8, // 4.0.6a
    MSG_MOVE_WATER_WALK                             = 0xE1A4, // 4.0.6a
    CMSG_SERVER_BROADCAST                           = 0x2B2, //
    CMSG_SELF_RES                                   = 0xAEC4, // 4.0.6a
    SMSG_FEIGN_DEATH_RESISTED                       = 0x3BE8, // 4.0.6a
    CMSG_RUN_SCRIPT                                 = 0x2B5, //
    SMSG_SCRIPT_MESSAGE                             = 0x2B6, //
    SMSG_DUEL_COUNTDOWN                             = 0xE8E0, // 4.0.6a
    SMSG_AREA_TRIGGER_MESSAGE                       = 0xEAE0, // 4.0.6a
    CMSG_SHOWING_HELM                               = 0xB7C0, // 4.0.6a
    CMSG_SHOWING_CLOAK                              = 0x7AA4, // 4.0.6a
    SMSG_LFG_ROLE_CHOSEN                            = 0xA9AC, // 4.0.6a
    SMSG_PLAYER_SKINNED                             = 0xBAA0, // 4.0.6a
    SMSG_DURABILITY_DAMAGE_DEATH                    = 0xFDA0, // 4.0.6a
    CMSG_SET_EXPLORATION                            = 0x2BE, //
    CMSG_SET_ACTIONBAR_TOGGLES                      = 0x32C4, // 4.0.6a
    UMSG_DELETE_GUILD_CHARTER                       = 0x2C0, // (UNUSED)
    MSG_PETITION_RENAME                             = 0x70C0, // 4.0.6a
    SMSG_INIT_WORLD_STATES                          = 0xF6E8, // 4.0.6a
    SMSG_UPDATE_WORLD_STATE                         = 0xF784, // 4.0.6a
    CMSG_ITEM_NAME_QUERY                            = 0x2C4, //
    SMSG_ITEM_NAME_QUERY_RESPONSE                   = 0x7BC8, // 4.0.6a
    SMSG_PET_ACTION_FEEDBACK                        = 0x2584, // 4.0.6a
    CMSG_CHAR_RENAME                                = 0x27C4, // 4.0.6a
    SMSG_CHAR_RENAME                                = 0xE0EC, // 4.0.6a
    CMSG_MOVE_SPLINE_DONE                           = 0x69E8, // 4.0.6a
    CMSG_MOVE_FALL_RESET                            = 0x2CA, //
    SMSG_INSTANCE_SAVE_CREATED                      = 0xBBC4, // 4.0.6a
    SMSG_RAID_INSTANCE_INFO                         = 0x2CC, //
    CMSG_REQUEST_RAID_INFO                          = 0x3DE4, // 4.0.6a
    CMSG_MOVE_TIME_SKIPPED                          = 0xE180, // 4.0.6a
    CMSG_MOVE_FEATHER_FALL_ACK                      = 0x6EA8, // 4.0.6a
    CMSG_MOVE_WATER_WALK_ACK                        = 0x21C4, // 4.0.6a
    CMSG_MOVE_NOT_ACTIVE_MOVER                      = 0xB9A8, // 4.0.6a
    SMSG_PLAY_SOUND                                 = 0x2EA8, // 4.0.6a
    CMSG_BATTLEFIELD_STATUS                         = 0x2D3, //
    SMSG_BATTLEFIELD_STATUS                         = 0x2D4, //
    CMSG_BATTLEFIELD_PORT                           = 0x0E11, // 4.0.6a
    MSG_INSPECT_HONOR_STATS                         = 0x2D6, //
    CMSG_BATTLEMASTER_HELLO                         = 0x2D7, //
    CMSG_MOVE_START_SWIM_CHEAT                      = 0x26C0, // 4.0.6a
    CMSG_MOVE_STOP_SWIM_CHEAT                       = 0x6988, // 4.0.6a
    SMSG_FORCE_WALK_SPEED_CHANGE                    = 0x68E8, // 4.0.6a
    CMSG_FORCE_WALK_SPEED_CHANGE_ACK                = 0x78CC, // 4.0.6a
    SMSG_FORCE_SWIM_BACK_SPEED_CHANGE               = 0x02DC, // 4.0.6a
    CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK           = 0xE8C4, // 4.0.6a
    SMSG_FORCE_TURN_RATE_CHANGE                     = 0x375E, //
    CMSG_FORCE_TURN_RATE_CHANGE_ACK                 = 0xE384, // 4.0.6a
    MSG_PVP_LOG_DATA                                = 0x0C0E, // 4.0.6a
    CMSG_LEAVE_BATTLEFIELD                          = 0x7DC4, // 4.0.6a
    CMSG_AREA_SPIRIT_HEALER_QUERY                   = 0xA6C0, // 4.0.6a
    CMSG_AREA_SPIRIT_HEALER_QUEUE                   = 0xF388, // 4.0.6a
    SMSG_AREA_SPIRIT_HEALER_TIME                    = 0x6D80, // 4.0.6a
    CMSG_GM_UNTEACH                                 = 0x2E5, //
    SMSG_WARDEN_DATA                                = 0xF8A0, // 4.0.6a
    CMSG_WARDEN_DATA                                = 0x2F84, // 4.0.6a
    SMSG_GROUP_JOINED_BATTLEGROUND                  = 0x0D1E, // 4.0.6a
    MSG_BATTLEGROUND_PLAYER_POSITIONS               = 0x2E9, //
    CMSG_PET_STOP_ATTACK                            = 0x2EA, //
    SMSG_BINDER_CONFIRM                             = 0x33C4, // 4.0.6a
    SMSG_BATTLEGROUND_PLAYER_JOINED                 = 0x494C, // 4.0.6a
    SMSG_BATTLEGROUND_PLAYER_LEFT                   = 0x0D1C, // 4.0.6a
    CMSG_BATTLEMASTER_JOIN                          = 0x0137, // 4.0.6a
    SMSG_ADDON_INFO                                 = 0xEA80, // 4.0.6a
    CMSG_PET_UNLEARN                                = 0x2F0, // (Deprecated 3.x)
    SMSG_PET_UNLEARN_CONFIRM                        = 0x2F1, // (Deprecated 3.x)
    SMSG_PARTY_MEMBER_STATS_FULL                    = 0xBA8C, // 4.0.6a
    CMSG_PET_SPELL_AUTOCAST                         = 0xB6A4, // 4.0.6a
    SMSG_WEATHER                                    = 0x79A0, // 4.0.6a
    SMSG_PLAY_TIME_WARNING                          = 0x32EC, // 4.0.6a
    SMSG_MINIGAME_SETUP                             = 0x2F6, //
    SMSG_MINIGAME_STATE                             = 0x2F7, //
    CMSG_MINIGAME_MOVE                              = 0xB2E4, // 4.0.6a
    SMSG_MINIGAME_MOVE_FAILED                       = 0x2F9,//
    SMSG_RAID_INSTANCE_MESSAGE                      = 0x6680, // 4.0.6a
    SMSG_COMPRESSED_MOVES                           = 0x6FE4, // 4.0.6a
    CMSG_GUILD_INFO_TEXT                            = 0x270D, // 4.0.6a
    SMSG_CHAT_RESTRICTED                            = 0x3EC8, // 4.0.6a
    SMSG_SPLINE_SET_RUN_SPEED                       = 0xF9E8, // 4.0.6a
    SMSG_SPLINE_SET_RUN_BACK_SPEED                  = 0xE9C0, // 4.0.6a
    SMSG_SPLINE_SET_SWIM_SPEED                      = 0xB2C0, // 4.0.6a
    SMSG_SPLINE_SET_WALK_SPEED                      = 0x3EA8, // 4.0.6a
    SMSG_SPLINE_SET_SWIM_BACK_SPEED                 = 0x21C8, // 4.0.6a
    SMSG_SPLINE_SET_TURN_RATE                       = 0x7EAC, // 4.0.6a
    SMSG_SPLINE_MOVE_UNROOT                         = 0x304, //
    SMSG_SPLINE_MOVE_FEATHER_FALL                   = 0x305, //
    SMSG_SPLINE_MOVE_NORMAL_FALL                    = 0x306, //
    SMSG_SPLINE_MOVE_SET_HOVER                      = 0x307, //
    SMSG_SPLINE_MOVE_UNSET_HOVER                    = 0x308, //
    SMSG_SPLINE_MOVE_WATER_WALK                     = 0x61C0, // 4.0.6a
    SMSG_SPLINE_MOVE_LAND_WALK                      = 0xA7C8, // 4.0.6a
    SMSG_SPLINE_MOVE_START_SWIM                     = 0x30B, //
    SMSG_SPLINE_MOVE_STOP_SWIM                      = 0x30C, //
    SMSG_SPLINE_MOVE_SET_RUN_MODE                   = 0x30D, //
    SMSG_SPLINE_MOVE_SET_WALK_MODE                  = 0x30E, //
    CMSG_GM_NUKE_ACCOUNT                            = 0x30F, //
    MSG_GM_DESTROY_CORPSE                           = 0x310, //
    CMSG_GM_DESTROY_ONLINE_CORPSE                   = 0x311, //
    CMSG_ACTIVATETAXIEXPRESS                        = 0xFC8C, // 4.0.6a
    SMSG_SET_FACTION_ATWAR                          = 0x2780, // 4.0.6a
    SMSG_GAMETIMEBIAS_SET                           = 0x314, //
    CMSG_DEBUG_ACTIONS_START                        = 0x315, //
    CMSG_DEBUG_ACTIONS_STOP                         = 0x316, //
    CMSG_SET_FACTION_INACTIVE                       = 0x317, //
    CMSG_SET_WATCHED_FACTION                        = 0x318, //
    MSG_MOVE_TIME_SKIPPED                           = 0x25E4, // 4.0.6a
    SMSG_SPLINE_MOVE_ROOT                           = 0x1E55, // 4.0.6a
    CMSG_SET_EXPLORATION_ALL                        = 0x31B, //
    SMSG_INVALIDATE_PLAYER                          = 0xA884, // 4.0.6a
    CMSG_RESET_INSTANCES                            = 0xAAA0, // 4.0.6a
    SMSG_INSTANCE_RESET                             = 0x30E8, // 4.0.6a
    SMSG_INSTANCE_RESET_FAILED                      = 0x3BA0, // 4.0.6a
    SMSG_UPDATE_LAST_INSTANCE                       = 0x33E8, // 4.0.6a
    MSG_RAID_TARGET_UPDATE                          = 0xA5AC, // 4.0.6a
    MSG_RAID_READY_CHECK                            = 0xFDC0, // 4.0.6a
    CMSG_LUA_USAGE                                  = 0x323, //
    SMSG_PET_ACTION_SOUND                           = 0x30E4, // 4.0.6a
    SMSG_PET_DISMISS_SOUND                          = 0xB7E0, // 4.0.6a
    SMSG_GHOSTEE_GONE                               = 0x326, //
    CMSG_GM_UPDATE_TICKET_STATUS                    = 0x327, //
    SMSG_GM_TICKET_STATUS_UPDATE                    = 0x72C4, // 4.0.6a
    MSG_SET_DUNGEON_DIFFICULTY                      = 0x74E0, // 4.0.6a
    CMSG_GMSURVEY_SUBMIT                            = 0xE280, // 4.0.6a
    SMSG_UPDATE_INSTANCE_OWNERSHIP                  = 0x3B8C, // 4.0.6a
    CMSG_IGNORE_KNOCKBACK_CHEAT                     = 0x32C, //
    SMSG_CHAT_PLAYER_AMBIGUOUS                      = 0x06AE8, // 4.0.6a
    MSG_DELAY_GHOST_TELEPORT                        = 0x32E, //
    SMSG_SPELLINSTAKILLLOG                          = 0x61C8, // 4.0.6a
    SMSG_SPELL_UPDATE_CHAIN_TARGETS                 = 0x36A4, // 4.0.6a
    CMSG_CHAT_FILTERED                              = 0x331, //
    SMSG_EXPECTED_SPAM_RECORDS                      = 0x6084, // 4.0.6a
    SMSG_SPELLSTEALLOG                              = 0x333, //
    CMSG_LOTTERY_QUERY_OBSOLETE                     = 0x334, //
    SMSG_LOTTERY_QUERY_RESULT_OBSOLETE              = 0x335, //
    CMSG_BUY_LOTTERY_TICKET_OBSOLETE                = 0x336, //
    SMSG_LOTTERY_RESULT_OBSOLETE                    = 0x337, //
    SMSG_CHARACTER_PROFILE                          = 0x338, //
    SMSG_CHARACTER_PROFILE_REALM_CONNECTED          = 0x339, //
    SMSG_DEFENSE_MESSAGE                            = 0x65EC, // 4.0.6a
    SMSG_INSTANCE_DIFFICULTY                        = 0x33B, //
    MSG_GM_RESETINSTANCELIMIT                       = 0x33C, //
    SMSG_MOTD                                       = 0x77C0, // 4.0.6a
    SMSG_MOVE_SET_FLIGHT                            = 0x33E, //
    SMSG_MOVE_UNSET_FLIGHT                          = 0xBDA0, // 4.0.6a   (NOT SURE)
    CMSG_MOVE_FLIGHT_ACK                            = 0xA3C8, // 4.0.6a
    MSG_MOVE_START_SWIM_CHEAT                       = 0x26C0, // 4.0.6a
    MSG_MOVE_STOP_SWIM_CHEAT                        = 0x6988, // 4.0.6a
    SMSG_MOVE_SET_CAN_FLY                           = 0xBDA0, // 4.0.6a
    SMSG_MOVE_UNSET_CAN_FLY                         = 0x3084, // 4.0.6a
    CMSG_MOVE_SET_CAN_FLY_ACK                       = 0xFCAC, // 4.0.6a
    CMSG_MOVE_SET_FLY                               = 0xE0E0, // 4.0.6a
    CMSG_SOCKET_GEMS                                = 0x76C4, // 4.0.6a
    CMSG_ARENA_TEAM_CREATE                          = 0x0509, // 4.0.6a
    SMSG_ARENA_TEAM_COMMAND_RESULT                  = 0x040C, // 4.0.6a
    UMSG_UPDATE_ARENA_TEAM_OBSOLETE                 = 0x34A, // (OUTDATED)
    CMSG_ARENA_TEAM_QUERY                           = 0xB9C8, // 4.0.6a
    SMSG_ARENA_TEAM_QUERY_RESPONSE                  = 0x3DE8, // 4.0.6a
    CMSG_ARENA_TEAM_ROSTER                          = 0x6BAC, // 4.0.6a
    SMSG_ARENA_TEAM_ROSTER                          = 0xEC80, // 4.0.6a
    CMSG_ARENA_TEAM_INVITE                          = 0xE9CC, // 4.0.6a
    SMSG_ARENA_TEAM_INVITE                          = 0x63A0, // 4.0.6a
    CMSG_ARENA_TEAM_ACCEPT                          = 0x61AC, // 4.0.6a
    CMSG_ARENA_TEAM_DECLINE                         = 0xF2C0, // 4.0.6a
    CMSG_ARENA_TEAM_LEAVE                           = 0x64C4, // 4.0.6a
    CMSG_ARENA_TEAM_REMOVE                          = 0x7E84, // 4.0.6a
    CMSG_ARENA_TEAM_DISBAND                         = 0x698C, // 4.0.6a
    CMSG_ARENA_TEAM_LEADER                          = 0x218C, // 4.0.6a
    SMSG_ARENA_TEAM_EVENT                           = 0x74C4, // 4.0.6a
    CMSG_BATTLEMASTER_JOIN_ARENA                    = 0x0311, // 4.0.6a
    MSG_MOVE_START_ASCEND                           = 0xBDC0, // 4.0.6a
    MSG_MOVE_STOP_ASCEND                            = 0xFCA8, // 4.0.6a
    SMSG_ARENA_TEAM_STATS                           = 0x35B, //
    CMSG_LFG_JOIN                                   = 0x63C0, // 4.0.6a
    CMSG_LFG_LEAVE                                  = 0x3688, // 4.0.6a
    CMSG_SEARCH_LFG_JOIN                            = 0x61CC, // 4.0.6a
    CMSG_SEARCH_LFG_LEAVE                           = 0x35F, //
    SMSG_UPDATE_LFG_LIST                            = 0x768C, // 4.0.6a
    SMSG_LFG_PROPOSAL_UPDATE                        = 0x32AC, // 4.0.6a
    CMSG_LFG_PROPOSAL_RESULT                        = 0xA7A4, // 4.0.6a
    SMSG_LFG_ROLE_CHECK_UPDATE                      = 0xF2A8, // 4.0.6a
    SMSG_LFG_JOIN_RESULT                            = 0x338C, // 4.0.6a
    SMSG_LFG_QUEUE_STATUS                           = 0xB388, // 4.0.6a
    CMSG_SET_LFG_COMMENT                            = 0xE1C4, // 4.0.6a
    SMSG_LFG_UPDATE_PLAYER                          = 0xE284, // 4.0.6a
    SMSG_LFG_UPDATE_PARTY                           = 0x2CE8, // 4.0.6a
    SMSG_LFG_UPDATE_SEARCH                          = 0x3880, // 4.0.6a
    CMSG_LFG_SET_ROLES                              = 0xE8CC, // 4.0.6a
    CMSG_LFG_SET_NEEDS                              = 0x36B, //
    CMSG_LFG_SET_BOOT_VOTE                          = 0x36C, //
    SMSG_LFG_BOOT_PLAYER                            = 0x36D, //
    CMSG_LFD_PLAYER_LOCK_INFO_REQUEST               = 0xE5E8, // 4.0.6a
    SMSG_LFG_PLAYER_INFO                            = 0xE088, // 4.0.6a
    CMSG_LFG_TELEPORT                               = 0xFA88, // 4.0.6a
    CMSG_LFD_PARTY_LOCK_INFO_REQUEST                = 0x371, //
    SMSG_LFG_PARTY_INFO                             = 0x60A0, // 4.0.6a
    SMSG_TITLE_EARNED                               = 0x6C8C, // 4.0.6a
    CMSG_SET_TITLE                                  = 0xEC8C, // 4.0.6a
    CMSG_CANCEL_MOUNT_AURA                          = 0x64CC, // 4.0.6a (NOT SURE)
    SMSG_ARENA_ERROR                                = 0x2FEC, // 4.0.6a
    MSG_INSPECT_ARENA_TEAMS                         = 0xFDA4, // 4.0.6a
    SMSG_DEATH_RELEASE_LOC                          = 0x33C8, // 4.0.6a
    CMSG_CANCEL_TEMP_ENCHANTMENT                    = 0xE484, // 4.0.6a
    SMSG_FORCED_DEATH_UPDATE                        = 0xFFE8, // 4.0.6a
    CMSG_CHEAT_SET_HONOR_CURRENCY                   = 0x37B, //
    CMSG_CHEAT_SET_ARENA_CURRENCY                   = 0x37C, //
    MSG_MOVE_SET_FLIGHT_SPEED_CHEAT                 = 0x37D, //
    MSG_MOVE_SET_FLIGHT_SPEED                       = 0xB088, // 4.0.6a
    MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT            = 0x37F, //
    MSG_MOVE_SET_FLIGHT_BACK_SPEED                  = 0xB484, // 4.0.6a
    SMSG_FORCE_FLIGHT_SPEED_CHANGE                  = 0xE5CC, // 4.0.6a
    CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK              = 0xA98C, // 4.0.6a
    SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE             = 0x383, //
    CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK         = 0xFBC8, // 4.0.6a
    SMSG_SPLINE_SET_FLIGHT_SPEED                    = 0xE0C0, // 4.0.6a
    SMSG_SPLINE_SET_FLIGHT_BACK_SPEED               = 0xF2EC, // 4.0.6a
    CMSG_MAELSTROM_INVALIDATE_CACHE                 = 0x387, //
    SMSG_FLIGHT_SPLINE_SYNC                         = 0xBFAC, // 4.0.6a
    CMSG_SET_TAXI_BENCHMARK_MODE                    = 0x73C4, // 4.0.6a
    SMSG_JOINED_BATTLEGROUND_QUEUE                  = 0x090E, // 4.0.6a
    SMSG_REALM_SPLIT                                = 0x25EC, // 4.0.6a
    CMSG_REALM_SPLIT                                = 0x60AC, // 4.0.6a
    CMSG_MOVE_CHNG_TRANSPORT                        = 0x38D, //
    MSG_PARTY_ASSIGNMENT                            = 0x28AC, // 4.0.6a
    SMSG_OFFER_PETITION_ERROR                       = 0x38F, //
    SMSG_TIME_SYNC_REQ                              = 0xAA80, // 4.0.6a
    CMSG_TIME_SYNC_RESP                             = 0xA8AC, // 4.0.6a
    CMSG_SEND_LOCAL_EVENT                           = 0x392, //
    CMSG_SEND_GENERAL_TRIGGER                       = 0x393, //
    CMSG_SEND_COMBAT_TRIGGER                        = 0x394, //
    CMSG_MAELSTROM_GM_SENT_MAIL                     = 0x395, //
    SMSG_RESET_FAILED_NOTIFY                        = 0x396, //
    SMSG_REAL_GROUP_UPDATE                          = 0x31C0, // 4.0.6a
    SMSG_LFG_DISABLED                               = 0xF880, // 4.0.6a
    CMSG_ACTIVE_PVP_CHEAT                           = 0x399, //
    CMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY                = 0x39A, //
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE       = 0x39B, //
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE_WRITE_FILE = 0x39C, //
    SMSG_UPDATE_COMBO_POINTS                        = 0x37A8, // 4.0.6a
    SMSG_VOICE_SESSION_ROSTER_UPDATE                = 0xACC0, // 4.0.6a
    SMSG_VOICE_SESSION_LEAVE                        = 0x78A4, // 4.0.6a
    SMSG_VOICE_SESSION_ADJUST_PRIORITY              = 0x3A0, //
    CMSG_VOICE_SET_TALKER_MUTED_REQUEST             = 0x3A1, //
    SMSG_VOICE_SET_TALKER_MUTED                     = 0xE3E4, // 4.0.6a
    SMSG_INIT_EXTRA_AURA_INFO_OBSOLETE              = 0x3A3, //
    SMSG_SET_EXTRA_AURA_INFO_OBSOLETE               = 0x3A4, //
    SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE_OBSOLETE   = 0x3A5, //
    SMSG_CLEAR_EXTRA_AURA_INFO_OBSOLETE             = 0x3A6, //
    MSG_MOVE_START_DESCEND                          = 0x7880, // 4.0.6a
    CMSG_IGNORE_REQUIREMENTS_CHEAT                  = 0x3A8, //
    SMSG_IGNORE_REQUIREMENTS_CHEAT                  = 0x7C84, // 4.0.6a
    SMSG_SPELL_CHANCE_PROC_LOG                      = 0x3AA, //
    CMSG_MOVE_SET_RUN_SPEED                         = 0x3AB, //
    SMSG_DISMOUNT                                   = 0x3CC4, // 4.0.6a
    MSG_MOVE_UPDATE_CAN_FLY                         = 0x25E0, // 4.0.6a
    MSG_RAID_READY_CHECK_CONFIRM                    = 0xA2AC, // 4.0.6a
    CMSG_VOICE_SESSION_ENABLE                       = 0xFEA4, // 4.0.6a
    SMSG_VOICE_SESSION_ENABLE                       = 0x3B0, //
    SMSG_VOICE_PARENTAL_CONTROLS                    = 0x71E8, // 4.0.6a
    CMSG_GM_WHISPER                                 = 0x3B2, //
    SMSG_GM_MESSAGECHAT                             = 0x3AEC, // 4.0.6a
    MSG_GM_GEARRATING                               = 0x3B4, //
    CMSG_COMMENTATOR_ENABLE                         = 0xB1C4, // 4.0.6a
    SMSG_COMMENTATOR_STATE_CHANGED                  = 0xE0E4, // 4.0.6a
    CMSG_COMMENTATOR_GET_MAP_INFO                   = 0x28C4, // 4.0.6a
    SMSG_COMMENTATOR_MAP_INFO                       = 0xA4E8, // 4.0.6a
    CMSG_COMMENTATOR_GET_PLAYER_INFO                = 0xBBA0, // 4.0.6a
    SMSG_COMMENTATOR_GET_PLAYER_INFO                = 0x3BA, //
    SMSG_COMMENTATOR_PLAYER_INFO                    = 0x758C, // 4.0.6a
    CMSG_COMMENTATOR_ENTER_INSTANCE                 = 0x7BCC, // 4.0.6a
    CMSG_COMMENTATOR_EXIT_INSTANCE                  = 0xB8E4, // 4.0.6a
    CMSG_COMMENTATOR_INSTANCE_COMMAND               = 0x7D80, // 4.0.6a
    SMSG_CLEAR_TARGET                               = 0xA7AC, // 4.0.6a
    CMSG_BOT_DETECTED                               = 0x3C0, //
    SMSG_CROSSED_INEBRIATION_THRESHOLD              = 0xA580, // 4.0.6a
    CMSG_CHEAT_PLAYER_LOGIN                         = 0x3C2, //
    CMSG_CHEAT_PLAYER_LOOKUP                        = 0x3C3, //
    SMSG_CHEAT_PLAYER_LOOKUP                        = 0x3C4, //
    SMSG_KICK_REASON                                = 0xEAC8, // 4.0.6a
    MSG_RAID_READY_CHECK_FINISHED                   = 0xA0A0, // 4.0.6a
    CMSG_COMPLAIN                                   = 0x68C8, // 4.0.6a
    SMSG_COMPLAIN_RESULT                            = 0x70CC, // 4.0.6a
    SMSG_FEATURE_SYSTEM_STATUS                      = 0x3DAC, // 4.0.6a
    CMSG_GM_SHOW_COMPLAINTS                         = 0x3CA, //
    CMSG_GM_UNSQUELCH                               = 0x3CB, //
    CMSG_CHANNEL_SILENCE_VOICE                      = 0x0801, // 4.0.6a
    CMSG_CHANNEL_SILENCE_ALL                        = 0x0021, // 4.0.6a
    CMSG_CHANNEL_UNSILENCE_VOICE                    = 0x002B, // 4.0.6a
    CMSG_CHANNEL_UNSILENCE_ALL                      = 0x0840, // 4.0.6a
    CMSG_TARGET_CAST                                = 0x3D0, //
    CMSG_TARGET_SCRIPT_CAST                         = 0x3D1, //
    CMSG_CHANNEL_DISPLAY_LIST                       = 0x3D2, //
    CMSG_SET_ACTIVE_VOICE_CHANNEL                   = 0x32A4, // 4.0.6a
    CMSG_GET_CHANNEL_MEMBER_COUNT                   = 0x0009, // 4.0.6a
    SMSG_CHANNEL_MEMBER_COUNT                       = 0x2CEC, // 4.0.6a
    CMSG_CHANNEL_VOICE_ON                           = 0x3D6, //
    CMSG_CHANNEL_VOICE_OFF                          = 0x3D7, //
    CMSG_DEBUG_LIST_TARGETS                         = 0x3D8, //
    SMSG_DEBUG_LIST_TARGETS                         = 0x3D9, //
    SMSG_AVAILABLE_VOICE_CHANNEL                    = 0xF8C8, // 4.0.6a
    CMSG_ADD_VOICE_IGNORE                           = 0x0DB, //
    CMSG_DEL_VOICE_IGNORE                           = 0x3DC, //
    CMSG_PARTY_SILENCE                              = 0x3DD, //
    CMSG_PARTY_UNSILENCE                            = 0x3DE, //
    MSG_NOTIFY_PARTY_SQUELCH                        = 0xE8E8, // 4.0.6a
    SMSG_COMSAT_RECONNECT_TRY                       = 0x3E0, //
    SMSG_COMSAT_DISCONNECT                          = 0x3E1, //
    SMSG_COMSAT_CONNECT_FAIL                        = 0x3E2, //
    SMSG_VOICE_CHAT_STATUS                          = 0x6B88, // 4.0.6a
    CMSG_REPORT_PVP_AFK                             = 0xE3AC, // 4.0.6a
    SMSG_REPORT_PVP_AFK_RESULT                      = 0x78E8, // 4.0.6a
    CMSG_GUILD_BANKER_ACTIVATE                      = 0xFFC4, // 4.0.6a
    CMSG_GUILD_BANK_QUERY_TAB                       = 0xA788, // 4.0.6a
    SMSG_GUILD_BANK_LIST                            = 0xA6A8, // 4.0.6a
    CMSG_GUILD_BANK_SWAP_ITEMS                      = 0xA8C4, // 4.0.6a
    CMSG_GUILD_BANK_BUY_TAB                         = 0x78AC, // 4.0.6a
    CMSG_GUILD_BANK_UPDATE_TAB                      = 0xE3CC, // 4.0.6a
    CMSG_GUILD_BANK_DEPOSIT_MONEY                   = 0x6FE8, // 4.0.6a
    CMSG_GUILD_BANK_WITHDRAW_MONEY                  = 0x73A8, // 4.0.6a
    MSG_GUILD_BANK_LOG_QUERY                        = 0xF584, // 4.0.6a
    CMSG_SET_CHANNEL_WATCH                          = 0x7FE0, // 4.0.6a
    SMSG_USERLIST_ADD                               = 0xF8CC, // 4.0.6a
    SMSG_USERLIST_REMOVE                            = 0xEF80, // 4.0.6a
    SMSG_USERLIST_UPDATE                            = 0x2C8C, // 4.0.6a
    CMSG_CLEAR_CHANNEL_WATCH                        = 0xA1E0, // 4.0.6a
    SMSG_INSPECT_TALENT                             = 0xF8C0, // 4.0.6a
    SMSG_GOGOGO_OBSOLETE                            = 0x3F5, //
    SMSG_ECHO_PARTY_SQUELCH                         = 0x2AC4, // 4.0.6a
    CMSG_SET_TITLE_SUFFIX                           = 0x3F7, //
    CMSG_SPELLCLICK                                 = 0xF9A4, // 4.0.6a
    SMSG_LOOT_LIST                                  = 0xF684, // 4.0.6a
    CMSG_GM_CHARACTER_RESTORE                       = 0x3FA, //
    CMSG_GM_CHARACTER_SAVE                          = 0x3FB, //
    SMSG_VOICESESSION_FULL                          = 0x3FC, //
    MSG_GUILD_PERMISSIONS                           = 0xF4C4, // 4.0.6a
    MSG_GUILD_BANK_MONEY_WITHDRAWN                  = 0x6CE4, // 4.0.6a
    MSG_GUILD_EVENT_LOG_QUERY                       = 0x69EC, // 4.0.6a
    CMSG_MAELSTROM_RENAME_GUILD                     = 0x400, //
    CMSG_GET_MIRRORIMAGE_DATA                       = 0xA08C, // 4.0.6a
    SMSG_MIRRORIMAGE_DATA                           = 0xE2A4, // 4.0.6a
    SMSG_FORCE_DISPLAY_UPDATE                       = 0x6788, // 4.0.6a
    SMSG_SPELL_CHANCE_RESIST_PUSHBACK               = 0x404, //
    CMSG_IGNORE_DIMINISHING_RETURNS_CHEAT           = 0x405, //
    SMSG_IGNORE_DIMINISHING_RETURNS_CHEAT           = 0x406, //
    CMSG_KEEP_ALIVE                                 = 0x2CE0, // 4.0.6a
    SMSG_RAID_READY_CHECK_ERROR                     = 0x408, //
    CMSG_OPT_OUT_OF_LOOT                            = 0x75A4, // 4.0.6a
    MSG_QUERY_GUILD_BANK_TEXT                       = 0xA2C4, // 4.0.6a
    CMSG_SET_GUILD_BANK_TEXT                        = 0x7680, // 4.0.6a
    CMSG_SET_GRANTABLE_LEVELS                       = 0x40C, //
    CMSG_GRANT_LEVEL                                = 0xB980, // 4.0.6a
    CMSG_REFER_A_FRIEND                             = 0x40E, //
    MSG_GM_CHANGE_ARENA_RATING                      = 0x40F, //
    CMSG_DECLINE_CHANNEL_INVITE                     = 0xDF7F, // 4.0.6a
    SMSG_GROUPACTION_THROTTLED                      = 0x411, //
    SMSG_OVERRIDE_LIGHT                             = 0x412, //
    SMSG_TOTEM_CREATED                              = 0x2EAC, // 4.0.6a
    CMSG_TOTEM_DESTROYED                            = 0x34A0, // 4.0.6a
    CMSG_EXPIRE_RAID_INSTANCE                       = 0x415, //
    CMSG_NO_SPELL_VARIANCE                          = 0x416, //
    CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY           = 0x2DAC, // 4.0.6a
    SMSG_QUESTGIVER_STATUS_MULTIPLE                 = 0xF5C0, // 4.0.6a
    CMSG_SET_PLAYER_DECLINED_NAMES                  = 0xADC0, // 4.0.6a
    SMSG_SET_PLAYER_DECLINED_NAMES_RESULT           = 0xBAAC, // 4.0.6a
    CMSG_QUERY_SERVER_BUCK_DATA                     = 0x41B, //
    CMSG_CLEAR_SERVER_BUCK_DATA                     = 0x41C, //
    SMSG_SERVER_BUCK_DATA                           = 0x41D, //
    SMSG_SEND_UNLEARN_SPELLS                        = 0xBDE8, // 4.0.6a
    SMSG_PROPOSE_LEVEL_GRANT                        = 0x41F, //
    CMSG_ACCEPT_LEVEL_GRANT                         = 0xB5CC, // 4.0.6a
    SMSG_REFER_A_FRIEND_FAILURE                     = 0x7F7C, // 4.0.6a
    SMSG_SPLINE_MOVE_SET_FLYING                     = 0x422, //
    SMSG_SPLINE_MOVE_UNSET_FLYING                   = 0x7688, // 4.0.6a
    SMSG_SUMMON_CANCEL                              = 0x70A8, // 4.0.6a
    CMSG_CHANGE_PERSONAL_ARENA_RATING               = 0x425, //
    CMSG_ALTER_APPEARANCE                           = 0x34A4, // 4.0.6a
    SMSG_ENABLE_BARBER_SHOP                         = 0x37E8, // 4.0.6a
    SMSG_BARBER_SHOP_RESULT                         = 0x3188, // 4.0.6a
    CMSG_CALENDAR_GET_CALENDAR                      = 0x429, //
    CMSG_CALENDAR_GET_EVENT                         = 0x3580, // 4.0.6a
    CMSG_CALENDAR_GUILD_FILTER                      = 0xADAC, // 4.0.6a
    CMSG_CALENDAR_ARENA_TEAM                        = 0xE9AC, // 4.0.6a
    CMSG_CALENDAR_ADD_EVENT                         = 0xF488, // 4.0.6a
    CMSG_CALENDAR_UPDATE_EVENT                      = 0xF084, // 4.0.6a
    CMSG_CALENDAR_REMOVE_EVENT                      = 0x6C88, // 4.0.6a
    CMSG_CALENDAR_COPY_EVENT                        = 0xBF84, // 4.0.6a
    CMSG_CALENDAR_EVENT_INVITE                      = 0xF6C4, // 4.0.6a
    CMSG_CALENDAR_EVENT_RSVP                        = 0x757F, // 4.0.6a
    CMSG_CALENDAR_EVENT_REMOVE_INVITE               = 0xEBCC, // 4.0.6a
    CMSG_CALENDAR_EVENT_STATUS                      = 0xBC84, // 4.0.6a
    CMSG_CALENDAR_EVENT_MODERATOR_STATUS            = 0xBDE4, // 4.0.6a
    SMSG_CALENDAR_SEND_CALENDAR                     = 0xB0A4, // 4.0.6a
    SMSG_CALENDAR_SEND_EVENT                        = 0xFAA4, // 4.0.6a
    SMSG_CALENDAR_FILTER_GUILD                      = 0x2FC4, // 4.0.6a
    SMSG_CALENDAR_ARENA_TEAM                        = 0x21E0, // 4.0.6a
    SMSG_CALENDAR_EVENT_INVITE                      = 0xA5A0, // 4.0.6a
    SMSG_CALENDAR_EVENT_INVITE_REMOVED              = 0xA9E0, // 4.0.6a
    SMSG_CALENDAR_EVENT_STATUS                      = 0x7EC0, // 4.0.6a
    SMSG_CALENDAR_COMMAND_RESULT                    = 0xAD80, // 4.0.6a
    SMSG_CALENDAR_RAID_LOCKOUT_ADDED                = 0x2AE0, // 4.0.6a
    SMSG_CALENDAR_RAID_LOCKOUT_REMOVED              = 0xFCE0, // 4.0.6a
    SMSG_CALENDAR_EVENT_INVITE_ALERT                = 0xAFA8, // 4.0.6a
    SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT        = 0xFEE0, // 4.0.6a
    SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT         = 0xF7C8, // 4.0.6a
    SMSG_CALENDAR_EVENT_REMOVED_ALERT               = 0x6288, // 4.0.6a
    SMSG_CALENDAR_EVENT_UPDATED_ALERT               = 0x29C0, // 4.0.6a
    SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT      = 0xABC8, // 4.0.6a
    CMSG_CALENDAR_COMPLAIN                          = 0x1E75, // 4.0.6a
    CMSG_CALENDAR_GET_NUM_PENDING                   = 0xEFAC, // 4.0.6a
    SMSG_CALENDAR_SEND_NUM_PENDING                  = 0xA8E0, // 4.0.6a
    CMSG_SAVE_DANCE                                 = 0x449, //
    SMSG_NOTIFY_DANCE                               = 0x3488, // 4.0.6a
    CMSG_PLAY_DANCE                                 = 0x2288, // 4.0.6a
    SMSG_PLAY_DANCE                                 = 0xB4EC, // 4.0.6a
    CMSG_LOAD_DANCES                                = 0x44D, //
    CMSG_STOP_DANCE                                 = 0x3080, // 4.0.6a
    SMSG_STOP_DANCE                                 = 0xE0A8, // 4.0.6a
    CMSG_SYNC_DANCE                                 = 0x450, //
    CMSG_DANCE_QUERY                                = 0x22A0, // 4.0.6a
    SMSG_DANCE_QUERY_RESPONSE                       = 0x31A8, // 4.0.6a
    SMSG_INVALIDATE_DANCE                           = 0xBEE8, // 4.0.6a
    CMSG_DELETE_DANCE                               = 0x454, //
    SMSG_LEARNED_DANCE_MOVES                        = 0x6F80, // 4.0.6a
    CMSG_LEARN_DANCE_MOVE                           = 0x456, //
    CMSG_UNLEARN_DANCE_MOVE                         = 0x457, //
    CMSG_SET_RUNE_COUNT                             = 0x458, //
    CMSG_SET_RUNE_COOLDOWN                          = 0x459, //
    MSG_MOVE_SET_PITCH_RATE_CHEAT                   = 0x45A, //
    MSG_MOVE_SET_PITCH_RATE                         = 0xABA4, // 4.0.6a
    SMSG_FORCE_PITCH_RATE_CHANGE                    = 0x45C, //
    CMSG_FORCE_PITCH_RATE_CHANGE_ACK                = 0xE6C0, // 4.0.6a
    SMSG_SPLINE_SET_PITCH_RATE                      = 0x70c4, // 4.0.6a
    SMSG_MOVE_ABANDON_TRANSPORT                     = 0x45F, //
    SMSG_CALENDAR_UPDATE_INVITE_LIST                = 0x71A0, // 4.0.6a
    SMSG_CALENDAR_UPDATE_INVITE_LIST2               = 0xEDC4, // 4.0.6a
    CMSG_UPDATE_MISSILE_TRAJECTORY                  = 0x462, //
    SMSG_UPDATE_ACCOUNT_DATA_COMPLETE               = 0xB1CC, // 4.0.6a
    SMSG_TRIGGER_MOVIE                              = 0x20C8, // 4.0.6a
    CMSG_COMPLETE_MOVIE                             = 0xE188, // 4.0.6a
    CMSG_SET_GLYPH_SLOT                             = 0x466, //
    CMSG_SET_GLYPH                                  = 0x467, //
    SMSG_ACHIEVEMENT_EARNED                         = 0xF5E4, // 4.0.6a
    SMSG_DYNAMIC_DROP_ROLL_RESULT                   = 0x469, //
    SMSG_CRITERIA_UPDATE                            = 0xAFC8, // 4.0.6a
    CMSG_QUERY_INSPECT_ACHIEVEMENTS                 = 0x69A0, // 4.0.6a
    SMSG_RESPOND_INSPECT_ACHIEVEMENTS               = 0x46C, //
    CMSG_DISMISS_CONTROLLED_VEHICLE                 = 0xE3C0, // 4.0.6a
    CMSG_COMPLETE_ACHIEVEMENT_CHEAT                 = 0x46E, //
    SMSG_QUESTUPDATE_ADD_PVP_KILL                   = 0x78E0, // 4.0.6a
    CMSG_SET_CRITERIA_CHEAT                         = 0x470, //
    SMSG_CALENDAR_UPDATE_INVITE_LIST3               = 0xA2A0, // 4.0.6a
    CMSG_UNITANIMTIER_CHEAT                         = 0x472, //
    CMSG_CHAR_CUSTOMIZE                             = 0x6484, // 4.0.6a
    SMSG_CHAR_CUSTOMIZE                             = 0x2da4, // 4.0.6a
    SMSG_PET_RENAMEABLE                             = 0xB6C8, // 4.0.6a
    CMSG_REQUEST_VEHICLE_EXIT                       = 0xB3CC, // 4.0.6a
    CMSG_REQUEST_VEHICLE_PREV_SEAT                  = 0x2DE4, // 4.0.6a
    CMSG_REQUEST_VEHICLE_NEXT_SEAT                  = 0x64E4, // 4.0.6a
    CMSG_REQUEST_VEHICLE_SWITCH_SEAT                = 0xA8CC, // 4.0.6a
    CMSG_PET_LEARN_TALENT                           = 0xA7A0, // 4.0.6a
    CMSG_PET_UNLEARN_TALENTS                        = 0x47B, //
    SMSG_SET_PHASE_SHIFT                            = 0x044C, // 4.0.6a
    SMSG_ALL_ACHIEVEMENT_DATA                       = 0x400E, // 4.0.6a
    CMSG_FORCE_SAY_CHEAT                            = 0x47E, //
    SMSG_HEALTH_UPDATE                              = 0x2AA8, // 4.0.6a
    SMSG_POWER_UPDATE                               = 0x65E8, // 4.0.6a
    CMSG_GAMEOBJ_REPORT_USE                         = 0x23A0, // 4.0.6a
    SMSG_HIGHEST_THREAT_UPDATE                      = 0x482, //
    SMSG_THREAT_UPDATE                              = 0xB480, // 4.0.6a
    SMSG_THREAT_REMOVE                              = 0x29E0, // 4.0.6a
    SMSG_THREAT_CLEAR                               = 0xFFC8, // 4.0.6a
    SMSG_CONVERT_RUNE                               = 0xB4AC, // 4.0.6a
    SMSG_RESYNC_RUNES                               = 0x487, //
    SMSG_ADD_RUNE_POWER                             = 0x488, //
    CMSG_START_QUEST                                = 0x0613, // 4.0.6a
    CMSG_REMOVE_GLYPH                               = 0x48A, //
    CMSG_DUMP_OBJECTS                               = 0x48B, //
    SMSG_DUMP_OBJECTS_DATA                          = 0x48C, //
    CMSG_DISMISS_CRITTER                            = 0xB7CC, // 4.0.6a
    SMSG_NOTIFY_DEST_LOC_SPELL_CAST                 = 0x3588, // 4.0.6a
    CMSG_AUCTION_LIST_PENDING_SALES                 = 0xEDEC, // 4.0.6a
    SMSG_AUCTION_LIST_PENDING_SALES                 = 0xBAC4, // 4.0.6a
    SMSG_MODIFY_COOLDOWN                            = 0x30CC, // 4.0.6a
    SMSG_PET_UPDATE_COMBO_POINTS                    = 0x7588, // 4.0.6a
    CMSG_ENABLETAXI                                 = 0x328C, // 4.0.6a
    SMSG_PRE_RESURRECT                              = 0x66C4, // 4.0.6a
    SMSG_AURA_UPDATE_ALL                            = 0x37E0, // 4.0.6a
    SMSG_AURA_UPDATE                                = 0x65C0, // 4.0.6a
    CMSG_FLOOD_GRACE_CHEAT                          = 0x497, //
    SMSG_SERVER_FIRST_ACHIEVEMENT                   = 0x68CC, // 4.0.6a
    SMSG_PET_LEARNED_SPELL                          = 0xB3C4, // 4.0.6a
    SMSG_PET_REMOVED_SPELL                          = 0xF28C, // 4.0.6a
    CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE         = 0xE988, // 4.0.6a
    CMSG_HEARTH_AND_RESURRECT                       = 0x49C, //
    SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA       = 0x3380, // 4.0.6a
    SMSG_CRITERIA_DELETED                           = 0xAF84, // 4.0.6a
    SMSG_ACHIEVEMENT_DELETED                        = 0xE6A0, // 4.0.6a
    CMSG_SERVER_INFO_QUERY                          = 0x4A0, //
    SMSG_SERVER_INFO_RESPONSE                       = 0x4A1, //
    CMSG_CHECK_LOGIN_CRITERIA                       = 0x4A2, //
    SMSG_SERVER_BUCK_DATA_START                     = 0x4A3, //
    CMSG_QUERY_VEHICLE_STATUS                       = 0x4A4, //
    UMSG_UNKNOWN_1189                               = 0x4A5, // (UNUSED)
    SMSG_BATTLEGROUND_INFO_THROTTLED                = 0x75C4, // 4.0.6a
    SMSG_PLAYER_VEHICLE_DATA                        = 0xA5A4, // 4.0.6a
    CMSG_PLAYER_VEHICLE_ENTER                       = 0xAEC8, // 4.0.6a
    CMSG_EJECT_PASSENGER                            = 0xF688, // 4.0.6a
    SMSG_PET_GUIDS                                  = 0xE4E8, // 4.0.6a
    SMSG_CLIENTCACHE_VERSION                        = 0x2EC4, // 4.0.6a
    UMSG_UNKNOWN_1196                               = 0x4AC, // (UNUSED)
    UMSG_UNKNOWN_1197                               = 0x4AD, // (UNUSED)
    UMSG_UNKNOWN_1198                               = 0x4AE, // (UNUSED)
    UMSG_UNKNOWN_1199                               = 0x4AF, // (UNUSED)
    UMSG_UNKNOWN_1200                               = 0x4B0, // (UNUSED)
    UMSG_UNKNOWN_1201                               = 0x4B1, // (UNUSED)
    SMSG_ITEM_REFUND_INFO_RESPONSE                  = 0x4B2, //             (refund item info)
    CMSG_ITEM_REFUND_INFO                           = 0x31E0, // 4.0.6a
    CMSG_ITEM_REFUND                                = 0x62E8, // 4.0.6a
    SMSG_ITEM_REFUND_RESULT                         = 0x4B5, //             (refund item result)
    CMSG_CORPSE_MAP_POSITION_QUERY                  = 0x23CC, // 4.0.6a
    SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE         = 0x4B7, //             (SMSG, 3*float+float)
    UMSG_UNKNOWN_1208                               = 0x4B8, // (UNUSED)
    UMSG_UNKNOWN_1209                               = 0x4B9, // (UNUSED)
    CMSG_CALENDAR_CONTEXT_EVENT_SIGNUP              = 0xAEAC, // 4.0.6a
    SMSG_CALENDAR_ACTION_PENDING                    = 0x7E8C, // 4.0.6a
    SMSG_EQUIPMENT_SET_LIST                         = 0xF1A8, // 4.0.6a
    CMSG_EQUIPMENT_SET_SAVE                         = 0xBFC0, // 4.0.6a
    CMSG_UPDATE_PROJECTILE_POSITION                 = 0x4BE, //            (CMSG, uint64 caster, uint32 spellId, uint8 castId, vector3 position)
    SMSG_SET_PROJECTILE_POSITION                    = 0x2C84, // 4.0.6a
    SMSG_TALENTS_INFO                               = 0x75C4, // 4.0.6a
    CMSG_LEARN_PREVIEW_TALENTS                      = 0xFFAC, // 4.0.6a
    CMSG_LEARN_PREVIEW_TALENTS_PET                  = 0xBCE8, // 4.0.6a
    UMSG_UNKNOWN_1219                               = 0x4C3, // (UNUSED)
    UMSG_UNKNOWN_1220                               = 0x4C4, // (UNUSED)
    UMSG_UNKNOWN_1221                               = 0x4C5, // (UNUSED)
    UMSG_UNKNOWN_1222                               = 0x4C6, // (UNUSED)
    SMSG_ARENA_OPPONENT_UPDATE                      = 0x28CC, // 4.0.6a
    SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED            = 0xB2A0, // 4.0.6a
    UMSG_UNKNOWN_1225                               = 0x4C9, // (UNUSED)
    UMSG_UNKNOWN_1226                               = 0x4CA, // (UNUSED)
    UMSG_UNKNOWN_1227                               = 0x4CB, // (UNUSED)
    UMSG_UNKNOWN_1228                               = 0x4CC, // (UNUSED)
    SMSG_MULTIPLE_PACKETS                           = 0xFEC0, // 4.0.6a
    SMSG_FORCE_UNK1_SPEED_CHANGE                    = 0x4CE, //             (SMSG, movement related)
    CMSG_FORCE_UNK1_SPEED_CHANGE_ACK                = 0xF0C0, // 4.0.6a
    SMSG_FORCE_UNK2_SPEED_CHANGE                    = 0x4D0, //             (SMSG, movement related)
    CMSG_FORCE_UNK2_SPEED_CHANGE_ACK                = 0x7DE8, // 4.0.6a
    MSG_MOVE_UNKNOWN_1234                           = 0x4D2, //             (SMSG, movement related)
    SMSG_SPLINE_MOVE_UNKNOWN_1235                   = 0x4D3, //             (SMSG, movement related)
    SMSG_SPLINE_MOVE_UNKNOWN_1236                   = 0x4D4, //             (SMSG, movement related)
    CMSG_EQUIPMENT_SET_USE                          = 0xE8A0, // 4.0.6a
    SMSG_EQUIPMENT_SET_USE_RESULT                   = 0x76AC, // 4.0.6a
    UMSG_UNKNOWN_1239                               = 0x4D7, // (UNUSED)
    SMSG_UNKNOWN_1240                               = 0xB8E0, // 4.0.6a
    CMSG_CHAR_FACTION_CHANGE                        = 0xBBCC, // 4.0.6a     (PTR SERVER)
    SMSG_CHAR_FACTION_CHANGE                        = 0x23AC, // 4.0.6a     (PTR SERVER)
    UMSG_UNKNOWN_1243                               = 0x4DB, // (UNUSED)
    UMSG_UNKNOWN_1244                               = 0x4DC, // (UNUSED)
    UMSG_UNKNOWN_1245                               = 0x4DD, // (UNUSED)
    SMSG_BATTLEFIELD_MGR_ENTRY_INVITE               = 0x4DE, //             (uint32, EVENT_BATTLEFIELD_MGR_ENTRY_INVITE)
    CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE      = 0x0005, // 4.0.6a
    SMSG_BATTLEFIELD_MGR_ENTERED                    = 0x0004, // 4.0.6a
    SMSG_BATTLEFIELD_MGR_QUEUE_INVITE               = 0x4E1, //             (uint32, EVENT_BATTLEFIELD_MGR_QUEUE_INVITE)
    CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE      = 0x8108, // 4.0.6a
    CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST              = 0x011D, // 4.0.6a
    SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE     = 0x011C, // 4.0.6a
    SMSG_BATTLEFIELD_MGR_EJECT_PENDING              = 0x011B, // 4.0.6a
    SMSG_BATTLEFIELD_MGR_EJECTED                    = 0x011A, // 4.0.6a
    CMSG_BATTLEFIELD_MGR_EXIT_REQUEST               = 0x8580, // 4.0.6a
    SMSG_BATTLEFIELD_MGR_STATE_CHANGE               = 0x352D, // 4.0.6a
    UMSG_UNKNOWN_1257                               = 0x4E9, // (UNUSED)
    UMSG_UNKNOWN_1258                               = 0x4EA, // (UNUSED)
    MSG_SET_RAID_DIFFICULTY                         = 0xB5E8, // 4.0.6a
    UMSG_UNKNOWN_1260                               = 0x4EC, // (UNUSED)
    SMSG_TOGGLE_XP_GAIN                             = 0x7980, // 4.0.6a
    SMSG_GMRESPONSE_DB_ERROR                        = 0xE0A0, // 4.0.6a
    SMSG_GMRESPONSE_RECEIVED                        = 0x33AC, // 4.0.6a
    CMSG_GMRESPONSE_RESOLVE                         = 0x62C8, // 4.0.6a
    SMSG_GMRESPONSE_STATUS_UPDATE                   = 0x0101, // 4.0.6a
    UMSG_UNKNOWN_1266                               = 0x4F2, // (UNUSED)
    UMSG_UNKNOWN_1267                               = 0x4F3, // (UNUSED)
    UMSG_UNKNOWN_1268                               = 0x4F4, // (UNUSED)
    UMSG_UNKNOWN_1269                               = 0x4F5, // (UNUSED)
    CMSG_WORLD_STATE_UI_TIMER_UPDATE                = 0x3FA8, // 4.0.6a
    SMSG_WORLD_STATE_UI_TIMER_UPDATE                = 0x5557, // 4.0.6a
    CMSG_CHAR_RACE_CHANGE                           = 0x6EA4, // 4.0.6a
    UMSG_UNKNOWN_1273                               = 0x4F9, // (UNUSED)
    SMSG_TALENTS_INVOLUNTARILY_RESET                = 0x2A84, // 4.0.6a
    UMSG_UNKNOWN_1275                               = 0x4FB, // (UNUSED)
    SMSG_UNKNOWN_1276                               = 0x0093, // 4.0.6a             (does nothing in 10554)
    SMSG_LOOT_SLOT_CHANGED                          = 0x31EC, // 4.0.6a
    UMSG_UNKNOWN_1278                               = 0x4FE, // (UNUSED)
    CMSG_READY_FOR_ACCOUNT_DATA_TIMES               = 0x7DA8, // 4.0.6a
    CMSG_QUERY_QUESTS_COMPLETED                     = 0xFE84, // 4.0.6a
    SMSG_QUERY_QUESTS_COMPLETED_RESPONSE            = 0xF1E8, // 4.0.6a
    CMSG_GM_REPORT_LAG                              = 0x3FA0, // 4.0.6a
    UMSG_UNKNOWN_1283                               = 0x503, // (UNUSED)
    UMSG_UNKNOWN_1284                               = 0x504, // (UNUSED)
    UMSG_UNKNOWN_1285                               = 0x505, // (UNUSED)
    SMSG_CORPSE_NOT_IN_INSTANCE                     = 0x31E4, // 4.0.6a
    UMSG_UNKNOWN_1287                               = 0x507, // (UNUSED)
    CMSG_SET_ALLOW_LOW_LEVEL_RAID1                  = 0x35EC, // 4.0.6a
    CMSG_SET_ALLOW_LOW_LEVEL_RAID2                  = 0x29C4, // 4.0.6a
    SMSG_CAMERA_SHAKE                               = 0x50A, //                     (uint32 SpellEffectCameraShakes.dbc index, uint32)
    SMSG_UPDATE_ITEM_ENCHANTMENTS                   = 0x20E8, // 4.0.6a
    UMSG_UNKNOWN_1292                               = 0x50C, // (UNUSED)
    SMSG_REDIRECT_CLIENT                            = 0x201B, // 4.0.6a
    CMSG_REDIRECTION_FAILED                         = 0x50E, //                     (something with networking)
    SMSG_UNKNOWN_1295                               = 0x50F, //                     (not found - disconnect)
    CMSG_UNKNOWN_1296                               = 0x510, //                     (something with networking)
    SMSG_FORCE_SEND_QUEUED_PACKETS                  = 0x6EC8, // 4.0.6a
    CMSG_REDIRECTION_AUTH_PROOF                     = 0x0E4C, // 4.0.6a
    UMSG_UNKNOWN_1299                               = 0x513, // (UNUSED)
    SMSG_UNKNOWN_1300                               = 0x514, //
    SMSG_UNKNOWN_1301                               = 0x515, //
    SMSG_UNKNOWN_1302                               = 0x516, //
    CMSG_UNKNOWN_1303                               = 0x6BE0, // 4.0.6a
    SMSG_UNKNOWN_1304                               = 0x72E0, // 4.0.6a
    UMSG_UNKNOWN_1305                               = 0x519, //
    UMSG_UNKNOWN_1306                               = 0x51A, //
    CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND         = 0x6DC8, // 4.0.6a
    SMSG_UNKNOWN_1309                               = 0x51D, //
    CMSG_TRANSFORM                                  = 0x4577, // 4.0.6a
    SMSG_UNKNOWN_1310                               = 0x2E88, // 4.0.6a
    CMSG_REDIRECT_AUTH_PROOF                        = 0x0100, // 4.0.6a
    CMSG_AUTO_DECLINE_GUILD_INVITES                 = 0x8589, // 4.0.6a
    CMSG_SET_PRIMARY_TALENT_TREE                    = 0xFEA8, // 4.0.6a
    CMSG_GROUP_SET_ROLES                            = 0x8509, // 4.0.6a
    CMSG_WORLD_LOGIN                                = 0x8508, // 4.0.6a
    CMSG_RETURN_TO_GRAVEYARD                        = 0x0593, // 4.0.6a
    NUM_MSG_TYPES                                   = 0x51F //                      (last unknown opcode + 1.)
};

/// Player state
enum SessionStatus
{
    STATUS_AUTHED = 0,                                      // Player authenticated (_player == NULL, m_playerRecentlyLogout = false or will be reset before handler call, m_GUID have garbage)
    STATUS_LOGGEDIN,                                        // Player in game (_player != NULL, m_GUID == _player->GetGUID(), inWorld())
    STATUS_TRANSFER,                                        // Player transferring to another map (_player != NULL, m_GUID == _player->GetGUID(), !inWorld())
    STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT,                    // _player!= NULL or _player == NULL && m_playerRecentlyLogout, m_GUID store last _player guid)
    STATUS_NEVER,                                           // Opcode not accepted from client (deprecated or server side only)
    STATUS_UNHANDLED,                                       // Opcode not handled yet
};

enum PacketProcessing
{
    PROCESS_INPLACE = 0,                                    //process packet whenever we receive it - mostly for non-handled or non-implemented packets
    PROCESS_THREADUNSAFE,                                   //packet is not thread-safe - process it in Trillium::UpdateSessions()
    PROCESS_THREADSAFE                                      //packet is thread-safe - process it in Map::Update()
};

class WorldPacket;

struct OpcodeHandler
{
    char const* name;
    SessionStatus status;
    PacketProcessing packetProcessing;
    void (WorldSession::*handler)(WorldPacket& recvPacket);
};

extern OpcodeHandler opcodeTable[NUM_MSG_TYPES];

/// Lookup opcode name for human understandable logging
inline const char* LookupOpcodeName(uint16 id)
{
    if (id >= NUM_MSG_TYPES)
        return "Received unknown opcode, it's more than max!";
    return opcodeTable[id].name;
}
#endif
/// @}
