/*
 * Copyright (C) 2011 TrilliumENCORE <http://www.trilliumemu.com/>
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/// \addtogroup u2w
/// @{
/// \file

#ifndef _OPCODES_H
#define _OPCODES_H

#include "Common.h"

// Note: this include need for be sure have full definition of class WorldSession
//       if this class definition not complete then VS for x64 release use different size for
//       struct OpcodeHandler in this header and Opcode.cpp and get totally wrong data from
//       table opcodeTable in source when Opcode.h included but WorldSession.h not included
#include "WorldSession.h"

/// List of Opcodes
enum Opcodes
{
    NUM_OPCODE_HANDLERS                              = 0x102B7,  // last unknown opcode + 1.
    UNKNOWN_OPCODE = NUM_OPCODE_HANDLERS, // must be >= NUM_OPCODE_HANDLERS

    CMSG_WORLD_TELEPORT                              = 0x08581, //
    CMSG_TELEPORT_TO_UNIT                            = 0x0E1AC, //
    SMSG_CHECK_FOR_BOTS                              = 0x0FEC8, //
    CMSG_BOT_DETECTED2                               = 0x10002, //
    SMSG_FORCEACTIONSHOW                             = 0x0AC84, //
    SMSG_PETGODMODE                                  = 0x072FA, // 14333
    SMSG_GODMODE                                     = 0x076E7, // 14333
    SMSG_DESTRUCTIBLE_BUILDING_DAMAGE                = 0x0A0E0, //
    CMSG_CHAR_CREATE                                 = 0x02A22, // 14333
    CMSG_CHAR_ENUM                                   = 0x01091, // 14333
    CMSG_CHAR_DELETE                                 = 0x06E32, // 14333
    SMSG_CHAR_CREATE                                 = 0x03EFA, // 14333
    SMSG_CHAR_ENUM                                   = 0x0C727, // 14333
    SMSG_CHAR_DELETE                                 = 0x03E36, // 14333
    CMSG_PLAYER_LOGIN                                = 0x010D1, // 14333
    SMSG_NEW_WORLD                                   = 0x0451E, //
    SMSG_TRANSFER_PENDING                            = 0x026EA, // 14333
    SMSG_TRANSFER_ABORTED                            = 0x066AF, // 14333
    SMSG_CHARACTER_LOGIN_FAILED                      = 0x0B2E3, // 14333
    SMSG_LOGIN_SETTIMESPEED                          = 0x0766F, // 14333
    SMSG_GAMETIME_UPDATE                             = 0x0F1EC, //
    CMSG_GAMETIME_SET                                = 0x020C4, //
    SMSG_GAMETIME_SET                                = 0x07888, //
    CMSG_GAMESPEED_SET                               = 0x10004, // 
    SMSG_GAMESPEED_SET                               = 0x03EC0, //
    CMSG_SERVERTIME                                  = 0x10005, //
    SMSG_SERVERTIME                                  = 0x07236, // 14333
    CMSG_PLAYER_LOGOUT                               = 0x0EAEE, // 14333
    CMSG_LOGOUT_REQUEST                              = 0x0B2A6, // 14333
    SMSG_LOGOUT_RESPONSE                             = 0x062BA, // 14333
    SMSG_LOGOUT_COMPLETE                             = 0x0A27F, // 14333
    CMSG_LOGOUT_CANCEL                               = 0x0F2BF, // 14333
    SMSG_LOGOUT_CANCEL_ACK                           = 0x0AA37, // 14333
    CMSG_NAME_QUERY                                  = 0x07266, // 14333
    SMSG_NAME_QUERY_RESPONSE                         = 0x0FA67, // 14333
    CMSG_PET_NAME_QUERY                              = 0x0BE3E, // 14333
    SMSG_PET_NAME_QUERY_RESPONSE                     = 0x07AFA, // 14333
    CMSG_GUILD_QUERY                                 = 0x0A26A, // 14333
    SMSG_GUILD_QUERY_RESPONSE                        = 0x076E3, // 14333
    CMSG_COMMENTATOR_START_WARGAME                   = 0x08588, //
    SMSG_ITEM_QUERY_SINGLE_RESPONSE                  = 0x00C4E, //
    SMSG_ITEM_QUERY_MULTIPLE_RESPONSE                = 0x10009, //
    CMSG_PAGE_TEXT_QUERY                             = 0x0F2FF, // 14333
    SMSG_PAGE_TEXT_QUERY_RESPONSE                    = 0x0762F, // 14333
    CMSG_QUEST_QUERY                                 = 0x02AFE, // 14333
    SMSG_QUEST_QUERY_RESPONSE                        = 0x0AEE3, // 14333
    CMSG_GAMEOBJECT_QUERY                            = 0x03AFE, // 14333
    SMSG_GAMEOBJECT_QUERY_RESPONSE                   = 0x0AEBF, // 14333
    CMSG_CREATURE_QUERY                              = 0x0A662, // 14333
    SMSG_CREATURE_QUERY_RESPONSE                     = 0x0AA67, // 14333
    CMSG_WHO                                         = 0x0F2B3, // 14333
    SMSG_WHO                                         = 0x0223B, // 14333
    CMSG_WHOIS                                       = 0x026E3, // 14333
    SMSG_WHOIS                                       = 0x0AA76, // 14333
    CMSG_CONTACT_LIST                                = 0x07A3B, // 14333
    SMSG_CONTACT_LIST                                = 0x0BEE3, // 14333
    SMSG_FRIEND_STATUS                               = 0x03EBE, // 14333
    CMSG_ADD_FRIEND                                  = 0x02AA3, // 14333
    CMSG_DEL_FRIEND                                  = 0x03E3B, // 14333
    CMSG_SET_CONTACT_NOTES                           = 0x0B2AA, // 14333
    CMSG_ADD_IGNORE                                  = 0x06E66, // 14333
    CMSG_DEL_IGNORE                                  = 0x07AB6, // 14333
    CMSG_GROUP_INVITE                                = 0x04051, // 14333
    SMSG_GROUP_INVITE                                = 0x0A8A8, //
    CMSG_GROUP_CANCEL                                = 0x1000A, //
    SMSG_GROUP_CANCEL                                = 0x0A627, // 14333
    CMSG_GROUP_ACCEPT                                = 0x0368C, //
    CMSG_GROUP_DECLINE                               = 0x0B4CC, //
    SMSG_GROUP_DECLINE                               = 0x0ABAC, //
    CMSG_GROUP_UNINVITE                              = 0x04F74, //
    CMSG_GROUP_UNINVITE_GUID                         = 0x0FEBB, // 14333
    SMSG_GROUP_UNINVITE                              = 0x03ACC, //
    CMSG_GROUP_SET_LEADER                            = 0x0B27A, // 14333
    SMSG_GROUP_SET_LEADER                            = 0x03A63, // 14333
    CMSG_LOOT_METHOD                                 = 0x0EE62, // 14333
    CMSG_GROUP_DISBAND                               = 0x02AEB, // 14333
    SMSG_GROUP_DESTROYED                             = 0x06AF6, // 14333
    SMSG_GROUP_LIST                                  = 0x0BEB3, // 14333
    SMSG_PARTY_MEMBER_STATS                          = 0x029AC, //
    SMSG_PARTY_COMMAND_RESULT                        = 0x026E0, //
    CMSG_GUILD_CREATE                                = 0x02219, //
    CMSG_GUILD_INVITE                                = 0x0F232, // 14333
    SMSG_GUILD_INVITE                                = 0x0010C, //
    CMSG_GUILD_ACCEPT                                = 0x03729, //
    CMSG_GUILD_DECLINE                               = 0x0352D, //
    SMSG_GUILD_DECLINE                               = 0x07A2F, // 14333
    CMSG_GUILD_INFO                                  = 0x0226E, // 14333
    SMSG_GUILD_INFO                                  = 0x03EAF, // 14333
    CMSG_GUILD_ROSTER                                = 0x0B2A4, //
    SMSG_GUILD_ROSTER                                = 0x01B47, // 14333
    CMSG_GUILD_PROMOTE                               = 0x02109, //
    CMSG_GUILD_DEMOTE                                = 0x0330D, //
    CMSG_GUILD_LEAVE                                 = 0x03329, //
    CMSG_GUILD_REMOVE                                = 0x0312D, //
    CMSG_GUILD_DISBAND                               = 0x0372D, //
    CMSG_GUILD_LEADER                                = 0x02650, //
    CMSG_GUILD_MOTD                                  = 0x0272D, //
    CMSG_QUERY_GUILD_REWARDS                         = 0x02210, //
    CMSG_QUERY_GUILD_MAX_XP                          = 0x0350D, //
    CMSG_QUERY_GUILD_XP                              = 0x03509, //
    SMSG_GUILD_EVENT                                 = 0x06672, // 14333
    SMSG_GUILD_UPDATE_ROSTER                         = 0x0085E, //
    SMSG_GUILD_RANKS_UPDATE                          = 0x0004C, //
    SMSG_GUILD_REWARDS_LIST                          = 0x00C4C, //
    SMSG_GUILD_TRADESKILL_UPDATE                     = 0x0454E, //
    SMSG_GUILD_MAX_DAILY_XP                          = 0x0441C, //
    SMSG_GUILD_NEWS_UPDATE                           = 0x0485E, //
    SMSG_GUILD_XP_UPDATE                             = 0x0440E, //
    SMSG_GUILD_COMMAND_RESULT                        = 0x023C0, //
    CMSG_MESSAGECHAT_SAY                             = 0x059B5, // 14333
    CMSG_MESSAGECHAT_YELL                            = 0x013B1, // 14333
    CMSG_MESSAGECHAT_CHANNEL                         = 0x05BB5, // 14333
    CMSG_MESSAGECHAT_WHISPER                         = 0x05B35, // 14333
    CMSG_MESSAGECHAT_GUILD                           = 0x01111, // 14333
    CMSG_MESSAGECHAT_OFFICER                         = 0x00861, //
    CMSG_MESSAGECHAT_AFK                             = 0x01191, // 14333
    CMSG_MESSAGECHAT_DND                             = 0x01B31, // 14333
    CMSG_MESSAGECHAT_EMOTE                           = 0x07EB6, // 14333
    CMSG_MESSAGECHAT_PARTY                           = 0x0084B, //
    CMSG_MESSAGECHAT_PARTY_LEADER                    = 0x0080B, //
    CMSG_MESSAGECHAT_RAID                            = 0x00803, //
    CMSG_MESSAGECHAT_RAID_LEADER                     = 0x00863, //
    CMSG_MESSAGECHAT_BATTLEGROUND                    = 0x00063, //
    CMSG_MESSAGECHAT_BATTLEGROUND_LEADER             = 0x00860, //
    CMSG_MESSAGECHAT_RAID_WARNING                    = 0x00061, //
    SMSG_MESSAGECHAT                                 = 0x06A2A, // 14333
    CMSG_JOIN_CHANNEL                                = 0x00002, //
    CMSG_LEAVE_CHANNEL                               = 0x0000B, //
    SMSG_CHANNEL_NOTIFY                              = 0x026B6, // 14333
    CMSG_CHANNEL_LIST                                = 0x07FE0, //
    SMSG_CHANNEL_LIST                                = 0x07E77, // 14333
    CMSG_CHANNEL_PASSWORD                            = 0x0080A, //
    CMSG_CHANNEL_SET_OWNER                           = 0x00800, //
    CMSG_CHANNEL_OWNER                               = 0x00848, //
    CMSG_CHANNEL_MODERATOR                           = 0x00828, //
    CMSG_CHANNEL_UNMODERATOR                         = 0x00809, //
    CMSG_CHANNEL_MUTE                                = 0x00023, //
    CMSG_CHANNEL_UNMUTE                              = 0x00841, //
    CMSG_CHANNEL_INVITE                              = 0x00020, //
    CMSG_CHANNEL_KICK                                = 0x00068, //
    CMSG_CHANNEL_ROSTER_INFO                         = 0x00069, //
    CMSG_CHANNEL_BAN                                 = 0x0000A, //
    CMSG_CHANNEL_UNBAN                               = 0x00048, //
    CMSG_CHANNEL_ANNOUNCEMENTS                       = 0x0004B, //
    CMSG_CHANNEL_MODERATE                            = 0x10018, //
    SMSG_UPDATE_OBJECT                               = 0x072A7, // 14333
    SMSG_DESTROY_OBJECT                              = 0x0FEBE, // 14333
    CMSG_USE_ITEM                                    = 0x022B3, // 14333
    CMSG_OPEN_ITEM                                   = 0x03677, // 14333
    CMSG_READ_ITEM                                   = 0x06A67, // 14333
    SMSG_READ_ITEM_OK                                = 0x0B6E7, // 14333
    SMSG_READ_ITEM_FAILED                            = 0x06EE7, // 14333
    SMSG_ITEM_COOLDOWN                               = 0x0F6FE, // 14333
    CMSG_GAMEOBJ_USE                                 = 0x072BB, // 14333
    CMSG_DESTROY_ITEMS                               = 0x06E7A, // 14333
    SMSG_GAMEOBJECT_CUSTOM_ANIM                      = 0x036A0, // 
    CMSG_AREATRIGGER                                 = 0x062A6, // 14333
    MSG_MOVE_START_FORWARD                           = 0x018E1, // 14333
    MSG_MOVE_START_BACKWARD                          = 0x072E4, //
    MSG_MOVE_STOP                                    = 0x0286A, // 14333
    MSG_MOVE_START_STRAFE_LEFT                       = 0x060E8, //
    MSG_MOVE_START_STRAFE_RIGHT                      = 0x0B843, // 14333
    MSG_MOVE_STOP_STRAFE                             = 0x0A8E0, // 14333
    MSG_MOVE_JUMP                                    = 0x0386A, // 14333
    MSG_MOVE_START_TURN_LEFT                         = 0x0084A, // 14333
    MSG_MOVE_START_TURN_RIGHT                        = 0x088E0, // 14333
    MSG_MOVE_STOP_TURN                               = 0x03862, // 14333
    MSG_MOVE_START_PITCH_UP                          = 0x060E4, //
    MSG_MOVE_START_PITCH_DOWN                        = 0x0ADC4, //
    MSG_MOVE_STOP_PITCH                              = 0x028E8, //
    MSG_MOVE_SET_RUN_MODE                            = 0x0E7A8, //
    MSG_MOVE_SET_WALK_MODE                           = 0x03FAC, //
    MSG_MOVE_TOGGLE_LOGGING                          = 0x1001D, //
    MSG_MOVE_TELEPORT                                = 0x024E4, //
    MSG_MOVE_TELEPORT_CHEAT                          = 0x0E7EC, //
    MSG_MOVE_TELEPORT_ACK                            = 0x06DAC, //
    MSG_MOVE_TOGGLE_FALL_LOGGING                     = 0x1001F, //
    MSG_MOVE_FALL_LAND                               = 0x088E1, // 14333
    MSG_MOVE_START_SWIM                              = 0x026C0, //
    MSG_MOVE_STOP_SWIM                               = 0x0FDE8, //
    MSG_MOVE_SET_RUN_SPEED_CHEAT                     = 0x10020, //
    MSG_MOVE_SET_RUN_SPEED                           = 0x064A0, //
    MSG_MOVE_SET_RUN_BACK_SPEED_CHEAT                = 0x10021, //
    MSG_MOVE_SET_RUN_BACK_SPEED                      = 0x0B5EC, //
    MSG_MOVE_SET_WALK_SPEED_CHEAT                    = 0x10022, //
    MSG_MOVE_SET_WALK_SPEED                          = 0x0F284, //
    MSG_MOVE_SET_SWIM_SPEED_CHEAT                    = 0x10023, //
    MSG_MOVE_SET_SWIM_SPEED                          = 0x02380, //
    MSG_MOVE_SET_SWIM_BACK_SPEED_CHEAT               = 0x10024, //
    MSG_MOVE_SET_SWIM_BACK_SPEED                     = 0x0B0AC, //
    MSG_MOVE_SET_ALL_SPEED_CHEAT                     = 0x10025, //
    MSG_MOVE_SET_TURN_RATE_CHEAT                     = 0x10026, //
    MSG_MOVE_SET_TURN_RATE                           = 0x0A3A8, //
    MSG_MOVE_TOGGLE_COLLISION_CHEAT                  = 0x00028, // 
    MSG_MOVE_SET_FACING                              = 0x09848, // 14333
    MSG_MOVE_SET_PITCH                               = 0x0EBA0, //
    MSG_MOVE_WORLDPORT_ACK                           = 0x02FC0, //
    SMSG_PLAYER_MOVE                                 = 0x05341, // 14333
    SMSG_MONSTER_MOVE                                = 0x0F1A4, //
    SMSG_MOVE_WATER_WALK                             = 0x02E84, //
    SMSG_MOVE_LAND_WALK                              = 0x02084, //
    MSG_MOVE_SET_RAW_POSITION_ACK                    = 0x0F4A0, //
    CMSG_MOVE_SET_RAW_POSITION                       = 0x0F0C8, //
    SMSG_FORCE_RUN_SPEED_CHANGE                      = 0x0F1CC, //
    CMSG_FORCE_RUN_SPEED_CHANGE_ACK                  = 0x026C8, //
    SMSG_FORCE_RUN_BACK_SPEED_CHANGE                 = 0x1002E, //
    CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK             = 0x078E4, //
    SMSG_FORCE_SWIM_SPEED_CHANGE                     = 0x0F5A0, //
    CMSG_FORCE_SWIM_SPEED_CHANGE_ACK                 = 0x0B1A0, //
    SMSG_FORCE_MOVE_ROOT                             = 0x02F88, //
    CMSG_FORCE_MOVE_ROOT_ACK                         = 0x07184, //
    SMSG_FORCE_MOVE_UNROOT                           = 0x030A0, //
    CMSG_FORCE_MOVE_UNROOT_ACK                       = 0x07FA8, //
    MSG_MOVE_ROOT                                    = 0x0ABA8, //
    MSG_MOVE_UNROOT                                  = 0x02088, //
    MSG_MOVE_HEARTBEAT                               = 0x028E3, // 14333
    SMSG_MOVE_KNOCK_BACK                             = 0x0B180, //
    CMSG_MOVE_KNOCK_BACK_ACK                         = 0x0F580, //
    MSG_MOVE_KNOCK_BACK                              = 0x0B0E8, //
    SMSG_MOVE_FEATHER_FALL                           = 0x06088, //
    SMSG_MOVE_NORMAL_FALL                            = 0x06CE0, //
    SMSG_MOVE_SET_HOVER                              = 0x06AE0, //
    SMSG_MOVE_UNSET_HOVER                            = 0x03FE0, //
    SMSG_MOVE_SET_WALK_IN_AIR                        = 0x0A980, //
    SMSG_MOVE_UNSET_WALK_IN_AIR                      = 0x07784, //
    CMSG_MOVE_HOVER_ACK                              = 0x0F4CC, //
    MSG_MOVE_HOVER                                   = 0x02FCC, //
    CMSG_TRIGGER_CINEMATIC_CHEAT                     = 0x1003D, //
    CMSG_OPENING_CINEMATIC                           = 0x0323E, // 14333
    SMSG_TRIGGER_CINEMATIC                           = 0x0A2FE, // 14333
    CMSG_NEXT_CINEMATIC_CAMERA                       = 0x0A2BA, // 14333
    CMSG_COMPLETE_CINEMATIC                          = 0x0B2F7, // 14333
    SMSG_TUTORIAL_FLAGS                              = 0x07E72, // 14333
    CMSG_TUTORIAL_FLAG                               = 0x0266A, // 14333
    CMSG_TUTORIAL_CLEAR                              = 0x0B2FB, // 14333
    CMSG_TUTORIAL_RESET                              = 0x0B6BF, // 14333
    CMSG_STANDSTATECHANGE                            = 0x032EA, // 14333
    CMSG_EMOTE                                       = 0x0FAC4, //
    SMSG_EMOTE                                       = 0x076FE, // 14333
    CMSG_TEXT_EMOTE                                  = 0x0E9E0, //
    SMSG_TEXT_EMOTE                                  = 0x026EF, // 14333
    CMSG_AUTOEQUIP_GROUND_ITEM                       = 0x10044, //
    CMSG_AUTOSTORE_GROUND_ITEM                       = 0x02FC8, //
    CMSG_AUTOSTORE_LOOT_ITEM                         = 0x0B2E8, //
    CMSG_STORE_LOOT_IN_SLOT                          = 0x07FCC, //
    CMSG_AUTOEQUIP_ITEM                              = 0x0E1C0, //
    CMSG_AUTOSTORE_BAG_ITEM                          = 0x0EDCC, //
    CMSG_SWAP_ITEM                                   = 0x03ABB, // 14333
    CMSG_SWAP_INV_ITEM                               = 0x03EC4, //
    CMSG_SPLIT_ITEM                                  = 0x0FDAC, //
    CMSG_AUTOEQUIP_ITEM_SLOT                         = 0x0E8A8, //
    OBSOLETE_DROP_ITEM                               = 0x10049, //
    CMSG_DESTROYITEM                                 = 0x06E7A, // 14333
    SMSG_INVENTORY_CHANGE_FAILURE                    = 0x0AFCC, //
    SMSG_OPEN_CONTAINER                              = 0x01C5F, //
    CMSG_INSPECT                                     = 0x06AAF, // 14333
    SMSG_INSPECT                                     = 0x07AC8, //
    CMSG_INITIATE_TRADE                              = 0x00413, //
    CMSG_BEGIN_TRADE                                 = 0x00F93, //
    CMSG_BUSY_TRADE                                  = 0x1004C, //
    CMSG_IGNORE_TRADE                                = 0x1004D, //
    CMSG_ACCEPT_TRADE                                = 0x008C0, // 14333
    CMSG_UNACCEPT_TRADE                              = 0x00811, //
    CMSG_CANCEL_TRADE                                = 0x00013, //
    CMSG_SET_TRADE_ITEM                              = 0x00A11, //
    CMSG_CLEAR_TRADE_ITEM                            = 0x00213, //
    CMSG_SET_TRADE_GOLD                              = 0x00C13, //
    SMSG_TRADE_STATUS                                = 0x0494E, //
    SMSG_TRADE_STATUS_EXTENDED                       = 0x0400C, //
    SMSG_INITIALIZE_FACTIONS                         = 0x03A2A, // 14333
    SMSG_SET_FACTION_VISIBLE                         = 0x03988, //
    SMSG_SET_FACTION_STANDING                        = 0x026EB, // 14333
    CMSG_SET_FACTION_ATWAR                           = 0x02E22, // 14333
    CMSG_SET_FACTION_CHEAT                           = 0x10056, //
    SMSG_SET_PROFICIENCY                             = 0x07EE6, // 14333
    CMSG_SET_ACTION_BUTTON                           = 0x07AB3, // 14333
    SMSG_ACTION_BUTTONS                              = 0x06EBA, // 14333
    SMSG_INITIAL_SPELLS                              = 0x0F6AE, // 14333
    SMSG_LEARNED_SPELL                               = 0x03626, // 14333
    SMSG_SUPERCEDED_SPELL                            = 0x03E3E, // 14333
    CMSG_NEW_SPELL_SLOT                              = 0x10057, //
    CMSG_CAST_SPELL                                  = 0x072FB, // 14333
    CMSG_CANCEL_CAST                                 = 0x032F3, // 14333
    SMSG_CAST_FAILED                                 = 0x0B626, // 14333
    SMSG_SPELL_START                                 = 0x0A632, // 14333
    SMSG_SPELL_GO                                    = 0x02A27, // 14333
    SMSG_SPELL_FAILURE                               = 0x022FB, // 14333
    SMSG_SPELL_COOLDOWN                              = 0x07277, // 14333
    SMSG_COOLDOWN_EVENT                              = 0x0EAEC, //
    CMSG_CANCEL_AURA                                 = 0x0BEEA, // 14333
    SMSG_EQUIPMENT_SET_SAVED                         = 0x076A6, // 14333
    SMSG_PET_CAST_FAILED                             = 0x0EAAA, // 14333
    MSG_CHANNEL_START                                = 0x02BAC, //
    MSG_CHANNEL_UPDATE                               = 0x062AC, //
    CMSG_CANCEL_CHANNELLING                          = 0x0AA63, // 14333
    SMSG_AI_REACTION                                 = 0x0B2EF, // 14333
    CMSG_SET_SELECTION                               = 0x06626, // 14333
    CMSG_EQUIPMENT_SET_DELETE                        = 0x0FEBF, // 14333
    CMSG_INSTANCE_LOCK_WARNING_RESPONSE              = 0x0E476, //
    CMSG_UNUSED2                                     = 0x10058, //
    CMSG_ATTACKSWING                                 = 0x0663B, // 14333
    CMSG_ATTACKSTOP                                  = 0x06EAB, // 14333
    SMSG_ATTACKSTART                                 = 0x06A22, // 14333
    SMSG_ATTACKSTOP                                  = 0x0E6FF, // 14333
    SMSG_ATTACKSWING_NOTINRANGE                      = 0x0EEE7, // 14333
    SMSG_ATTACKSWING_BADFACING                       = 0x0622B, // 14333
    SMSG_INSTANCE_LOCK_WARNING_QUERY                 = 0x0B574, //
    SMSG_ATTACKSWING_DEADTARGET                      = 0x03E67, // 14333
    SMSG_ATTACKSWING_CANT_ATTACK                     = 0x0F627, // 14333
    SMSG_ATTACKERSTATEUPDATE                         = 0x0BE26, // 14333
    SMSG_BATTLEFIELD_PORT_DENIED                     = 0x10059, //
    SMSG_DAMAGE_DONE_OBSOLETE                        = 0x1005A, //
    SMSG_UNIT_SPELLCAST_START                        = 0x0BAAA, // 14333
    SMSG_CANCEL_COMBAT                               = 0x0A2BB, // 14333
    SMSG_SPELLBREAKLOG                               = 0x0EEFE, // 14333
    SMSG_SPELLHEALLOG                                = 0x0F673, // 14333
    SMSG_SPELLENERGIZELOG                            = 0x07A2A, // 14333
    SMSG_BREAK_TARGET                                = 0x02488, //
    CMSG_SAVE_PLAYER                                 = 0x1005C, //
    CMSG_SETDEATHBINDPOINT                           = 0x0A94E, //
    SMSG_BINDPOINTUPDATE                             = 0x07E26, // 14333
    CMSG_GETDEATHBINDZONE                            = 0x1005E, //
    SMSG_BINDZONEREPLY                               = 0x0622E, // 14333
    SMSG_PLAYERBOUND                                 = 0x06EAE, // 14333
    SMSG_CLIENT_CONTROL_UPDATE                       = 0x0E267, // 14333
    CMSG_REPOP_REQUEST                               = 0x0F23A, // 14333
    SMSG_RESURRECT_REQUEST                           = 0x0322E, // 14333
    CMSG_RESURRECT_RESPONSE                          = 0x0BA32, // 14333
    CMSG_LOOT                                        = 0x0726B, // 14333
    CMSG_LOOT_MONEY                                  = 0x03AEA, // 14333
    CMSG_LOOT_RELEASE                                = 0x0E273, // 14333
    SMSG_LOOT_RESPONSE                               = 0x0F663, // 14333
    SMSG_LOOT_RELEASE_RESPONSE                       = 0x0F66E, // 14333
    SMSG_LOOT_REMOVED                                = 0x0327F, // 14333
    SMSG_LOOT_MONEY_NOTIFY                           = 0x0B637, // 14333
    SMSG_LOOT_ITEM_NOTIFY                            = 0x0FEF7, // 14333
    SMSG_LOOT_CLEAR_MONEY                            = 0x0AABA, // 14333
    SMSG_ITEM_PUSH_RESULT                            = 0x0FBE8, //
    SMSG_DUEL_REQUESTED                              = 0x0AA6E, // 14333
    SMSG_DUEL_OUTOFBOUNDS                            = 0x068C0, //
    SMSG_DUEL_INBOUNDS                               = 0x0ECA4, //
    SMSG_DUEL_COMPLETE                               = 0x0B6FE, // 14333
    SMSG_DUEL_WINNER                                 = 0x03AF2, // 14333
    CMSG_DUEL_ACCEPTED                               = 0x0F63B, // 14333
    CMSG_DUEL_CANCELLED                              = 0x0362E, // 14333
    SMSG_MOUNTRESULT                                 = 0x0EEF2, // 14333
    SMSG_DISMOUNTRESULT                              = 0x026AF, // 14333
    SMSG_PUREMOUNT_CANCELLED_OBSOLETE                = 0x0054E, //
    CMSG_MOUNTSPECIAL_ANIM                           = 0x0AA6F, // 14333
    SMSG_MOUNTSPECIAL_ANIM                           = 0x022F3, // 14333
    SMSG_PET_TAME_FAILURE                            = 0x03EB6, // 14333
    CMSG_PET_SET_ACTION                              = 0x02A6E, // 14333
    CMSG_PET_ACTION                                  = 0x07232, // 14333
    CMSG_PET_ABANDON                                 = 0x0A480, //
    CMSG_PET_RENAME                                  = 0x0BAEE, // 14333
    SMSG_PET_NAME_INVALID                            = 0x01457, //
    SMSG_PET_SPELLS                                  = 0x066A3, // 14333
    SMSG_PET_MODE                                    = 0x0EE26, // 14333
    CMSG_GOSSIP_HELLO                                = 0x0EE7B, // 14333
    CMSG_GOSSIP_SELECT_OPTION                        = 0x02AE3, // 14333
    SMSG_GOSSIP_MESSAGE                              = 0x062E6, // 14333
    SMSG_GOSSIP_COMPLETE                             = 0x0F6A3, // 14333
    CMSG_NPC_TEXT_QUERY                              = 0x03AEF, // 14333
    SMSG_NPC_TEXT_UPDATE                             = 0x02AFF, // 14333
    SMSG_NPC_WONT_TALK                               = 0x10061, //
    CMSG_QUESTGIVER_STATUS_QUERY                     = 0x07223, // 14333
    SMSG_QUESTGIVER_STATUS                           = 0x066FB, // 14333
    CMSG_QUESTGIVER_HELLO                            = 0x036AC, //
    SMSG_QUESTGIVER_QUEST_LIST                       = 0x07AE6, // 14333
    CMSG_QUESTGIVER_QUERY_QUEST                      = 0x0BEEB, // 14333
    CMSG_QUESTGIVER_QUEST_AUTOLAUNCH                 = 0x10064, //
    SMSG_QUESTGIVER_QUEST_DETAILS                    = 0x0F266, // 14333
    CMSG_QUESTGIVER_ACCEPT_QUEST                     = 0x0F2AB, // 14333
    CMSG_QUESTGIVER_COMPLETE_QUEST                   = 0x072E3, // 14333
    SMSG_QUESTGIVER_REQUEST_ITEMS                    = 0x03E76, // 14333
    CMSG_QUESTGIVER_REQUEST_REWARD                   = 0x0E27F, // 14333
    SMSG_QUESTGIVER_OFFER_REWARD                     = 0x0E6A3, // 14333
    CMSG_QUESTGIVER_CHOOSE_REWARD                    = 0x03EAB, // 14333
    SMSG_QUESTGIVER_QUEST_INVALID                    = 0x10065, //
    CMSG_QUESTGIVER_CANCEL                           = 0x0E263, // 14333
    SMSG_QUESTGIVER_QUEST_COMPLETE                   = 0x01303, // 14333
    SMSG_QUESTGIVER_QUEST_FAILED                     = 0x0E6FE, // 14333
    CMSG_QUESTLOG_SWAP_QUEST                         = 0x10068, //
    CMSG_QUESTLOG_REMOVE_QUEST                       = 0x03A3F, // 14333
    SMSG_QUESTLOG_FULL                               = 0x0E263, // 14333
    SMSG_QUESTUPDATE_FAILED                          = 0x0EAB7, // 14333
    SMSG_QUESTUPDATE_FAILEDTIMER                     = 0x0BAF7, // 14333
    SMSG_QUESTUPDATE_COMPLETE                        = 0x03A73, // 14333
    SMSG_QUESTUPDATE_ADD_KILL                        = 0x0B67A, // 14333
    SMSG_QUESTUPDATE_ADD_ITEM                        = 0x1006B, //
    CMSG_QUEST_CONFIRM_ACCEPT                        = 0x0F2B7, // 14333
    SMSG_QUEST_CONFIRM_ACCEPT                        = 0x022AF, // 14333
    CMSG_PUSHQUESTTOPARTY                            = 0x022B2, // 14333
    CMSG_LIST_INVENTORY                              = 0x0EAFB, // 14333
    SMSG_LIST_INVENTORY                              = 0x0F8AC, //
    CMSG_SELL_ITEM                                   = 0x026B3, // 14333
    SMSG_SELL_ITEM                                   = 0x037AC, //
    CMSG_BUY_ITEM                                    = 0x0626A, // 14333
    SMSG_BUY_ITEM                                    = 0x069CC, //
    SMSG_BUY_FAILED                                  = 0x06CE8, //
    CMSG_TAXICLEARALLNODES                           = 0x1006C, // Never used
    CMSG_TAXIENABLEALLNODES                          = 0x1006D, // Never used
    CMSG_TAXISHOWNODES                               = 0x0B8E8, //
    SMSG_SHOWTAXINODES                               = 0x02B84, //
    CMSG_TAXINODE_STATUS_QUERY                       = 0x06622, // 14333
    SMSG_TAXINODE_STATUS                             = 0x0226A, // 14333
    CMSG_TAXIQUERYAVAILABLENODES                     = 0x0BE8E, //
    CMSG_ACTIVATETAXI                                = 0x0A2AF, // 14333
    SMSG_ACTIVATETAXIREPLY                           = 0x0AEB2, // 14333
    SMSG_NEW_TAXI_PATH                               = 0x06AA6, // 14333
    CMSG_TRAINER_LIST                                = 0x0BEBA, // 14333
    SMSG_TRAINER_LIST                                = 0x0BBE0, //
    CMSG_TRAINER_BUY_SPELL                           = 0x0BA27, // 14333
    SMSG_TRAINER_BUY_RESULT                          = 0x06DEC, //
    CMSG_BINDER_ACTIVATE                             = 0x0EA6F, // 14433
    SMSG_PLAYERBINDERROR                             = 0x0A26B, // 14333
    CMSG_BANKER_ACTIVATE                             = 0x0E7E0, //
    SMSG_SHOW_BANK                                   = 0x027A4, //
    CMSG_BUY_BANK_SLOT                               = 0x0A2B6, // 14333
    SMSG_BUY_BANK_SLOT_RESULT                        = 0x10076, //
    CMSG_PETITION_SHOWLIST                           = 0x0FCC4, //
    SMSG_PETITION_SHOWLIST                           = 0x0FCC0, //
    CMSG_PETITION_BUY                                = 0x02A26, // 14333
    CMSG_PETITION_SHOW_SIGNATURES                    = 0x0FA36, // 14333
    SMSG_PETITION_SHOW_SIGNATURES                    = 0x0E2E0, //
    CMSG_PETITION_SIGN                               = 0x026BE, // 14333
    SMSG_PETITION_SIGN_RESULTS                       = 0x0A1A4, //
    MSG_PETITION_DECLINE                             = 0x0AE2F, // 14333
    CMSG_OFFER_PETITION                              = 0x02EFE, // 14333
    CMSG_TURN_IN_PETITION                            = 0x0727A, // 14333
    SMSG_TURN_IN_PETITION_RESULTS                    = 0x035AC, //
    CMSG_PETITION_QUERY                              = 0x07E36, // 14333
    SMSG_PETITION_QUERY_RESPONSE                     = 0x03AB7, // 14333
    SMSG_FISH_NOT_HOOKED                             = 0x0EAAF, // 14333
    SMSG_FISH_ESCAPED                                = 0x06AFF, // 14333
    CMSG_BUG                                         = 0x06262, // 14333
    SMSG_NOTIFICATION                                = 0x076A7, // 14333
    CMSG_PLAYED_TIME                                 = 0x0EEE2, // 14333
    SMSG_PLAYED_TIME                                 = 0x02EA2, // 14333
    CMSG_QUERY_TIME                                  = 0x0B1C0, //
    SMSG_QUERY_TIME_RESPONSE                         = 0x03AF3, // 14333
    SMSG_LOG_XPGAIN                                  = 0x0EE7A, // 14333
    SMSG_AURACASTLOG                                 = 0x10080, //
    CMSG_RECLAIM_CORPSE                              = 0x07E76, // 14333
    CMSG_WRAP_ITEM                                   = 0x06E54, //
    SMSG_LEVELUP_INFO                                = 0x0E2AE, // 14333
    MSG_MINIMAP_PING                                 = 0x0C475, //
    SMSG_RESISTLOG                                   = 0x10084, //
    SMSG_ENCHANTMENTLOG                              = 0x0A6AE, // 14333
    CMSG_SET_SKILL_CHEAT                             = 0x10085, //
    SMSG_START_MIRROR_TIMER                          = 0x0AAA7, // 14333
    SMSG_PAUSE_MIRROR_TIMER                          = 0x0A2EF, // 14333
    SMSG_STOP_MIRROR_TIMER                           = 0x0B63E, // 14333
    CMSG_PING                                        = 0x02920, // 14333
    SMSG_PONG                                        = 0x00C90, // 14333
    SMSG_CLEAR_COOLDOWN                              = 0x036CC, //
    SMSG_GAMEOBJECT_PAGETEXT                         = 0x0E5C8, //
    CMSG_SETSHEATHED                                 = 0x0AAE4, //
    SMSG_COOLDOWN_CHEAT                              = 0x0A2F3, // 14333
    SMSG_SPELL_DELAYED                               = 0x0A3E8, //
    CMSG_QUEST_POI_QUERY                             = 0x07DE0, //
    SMSG_QUEST_POI_QUERY_RESPONSE                    = 0x0663F, // 14333
    CMSG_GHOST                                       = 0x10088, //
    CMSG_GM_INVIS                                    = 0x10089, //
    SMSG_INVALID_PROMOTION_CODE                      = 0x06A23, // 14333
    MSG_GM_BIND_OTHER                                = 0x1008B, //
    MSG_GM_SUMMON                                    = 0x1008C, //
    SMSG_ITEM_TIME_UPDATE                            = 0x066A4, //
    SMSG_ITEM_ENCHANT_TIME_UPDATE                    = 0x066A0, //
    SMSG_AUTH_CHALLENGE                              = 0x08C10, // 14333
    CMSG_AUTH_SESSION                                = 0x029A0, // 14333
    SMSG_AUTH_RESPONSE                               = 0x0BEFB, // 14333
    MSG_GM_SHOWLABEL                                 = 0x1008D, //
    CMSG_PET_CAST_SPELL                              = 0x02888, //
    MSG_SAVE_GUILD_EMBLEM                            = 0x06A36, // 14333
    MSG_TABARDVENDOR_ACTIVATE                        = 0x0EAEF, // 14333
    SMSG_PLAY_SPELL_VISUAL                           = 0x0FF8C, //
    CMSG_ZONEUPDATE                                  = 0x0AEB7, // 14333
    SMSG_PARTYKILLLOG                                = 0x03276, // 14333
    SMSG_COMPRESSED_UPDATE_OBJECT                    = 0x0E23F, // 14333
    SMSG_PLAY_SPELL_IMPACT                           = 0x0A3E4, //
    SMSG_EXPLORATION_EXPERIENCE                      = 0x0A66A, // 14333
    CMSG_GM_SET_SECURITY_GROUP                       = 0x1008E, //
    CMSG_GM_NUKE                                     = 0x1008F, //
    MSG_RANDOM_ROLL                                  = 0x0FEFB, // 14333
    SMSG_ENVIRONMENTALDAMAGELOG                      = 0x06EE6, // 14333
    CMSG_PLAYER_DIFFICULTY_CHANGE                    = 0x07E5D, //
    SMSG_RWHOIS                                      = 0x0E63A, // 14333
    SMSG_LFG_PLAYER_REWARD                           = 0x022B6, // 14333
    SMSG_LFG_TELEPORT_DENIED                         = 0x0E6B3, // 14333
    CMSG_UNLEARN_SPELL                               = 0x10090, //
    CMSG_UNLEARN_SKILL                               = 0x0B2EE, // 14333
    SMSG_REMOVED_SPELL                               = 0x07AF6, // 14333
    CMSG_DECHARGE                                    = 0x10092, //
    CMSG_GMTICKET_CREATE                             = 0x02223, // 14333
    SMSG_GMTICKET_CREATE                             = 0x0A8A0, //
    CMSG_GMTICKET_UPDATETEXT                         = 0x06A2B, // 14333
    SMSG_GMTICKET_UPDATETEXT                         = 0x0A5E8, //
    SMSG_ACCOUNT_DATA_TIMES                          = 0x02E3E, // 14333 
    CMSG_REQUEST_ACCOUNT_DATA                        = 0x07E3B, // 14333
    CMSG_UPDATE_ACCOUNT_DATA                         = 0x066FF, // 14333
    SMSG_UPDATE_ACCOUNT_DATA                         = 0x0AA66, // 14333
    SMSG_CLEAR_FAR_SIGHT_IMMEDIATE                   = 0x06E7B, // 14333
    SMSG_PLAYER_DIFFICULTY_CHANGE                    = 0x07EAF, // 14333
    CMSG_GM_TEACH                                    = 0x10095, //
    CMSG_GM_CREATE_ITEM_TARGET                       = 0x10096, //
    CMSG_GMTICKET_GETTICKET                          = 0x032A2, // 14333
    SMSG_GMTICKET_GETTICKET                          = 0x02284, //
    CMSG_UNLEARN_TALENTS                             = 0x10098, //
    SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT              = 0x03EF2, // 14333
    SMSG_GAMEOBJECT_DESPAWN_ANIM                     = 0x032F7, // 14333
    MSG_CORPSE_QUERY                                 = 0x03232, // 14333
    CMSG_GMTICKET_DELETETICKET                       = 0x0FE22, // 14333
    SMSG_GMTICKET_DELETETICKET                       = 0x0F48C, //
    SMSG_CHAT_WRONG_FACTION                          = 0x02233, // 14333
    CMSG_GMTICKET_SYSTEMSTATUS                       = 0x07E67, // 14333
    SMSG_GMTICKET_SYSTEMSTATUS                       = 0x0B9C0, //
    CMSG_SPIRIT_HEALER_ACTIVATE                      = 0x0B6B6, // 14333
    SMSG_QUEST_FORCE_REMOVED                         = 0x02A7A, // 14333
    CMSG_SKILL_BUY_STEP                              = 0x1009E, //
    CMSG_SKILL_BUY_RANK                              = 0x1009F, //
    SMSG_SPIRIT_HEALER_CONFIRM                       = 0x0B9C0, //
    CMSG_CHARACTER_POINT_CHEAT                       = 0x100A0, //
    SMSG_GOSSIP_POI                                  = 0x0223A, // 14333
    CMSG_CHAT_IGNORED                                = 0x0A78C, //
    CMSG_GUILD_RANK                                  = 0x02709, //
    SMSG_GUILD_RANK                                  = 0x0411E, //
    CMSG_GUILD_ADD_RANK                              = 0x02309, //
    CMSG_GUILD_DEL_RANK                              = 0x02129, //
    CMSG_GUILD_SWITCH_RANK                           = 0x100A6, //
    CMSG_GUILD_SET_NOTE                              = 0x0232D, //
    SMSG_LOGIN_VERIFY_WORLD                          = 0x0BA77, // 14333
    CMSG_CLEAR_EXPLORATION                           = 0x100A9, //
    CMSG_SEND_MAIL                                   = 0x02DEC, //
    SMSG_SEND_MAIL_RESULT                            = 0x0A6FE, // 14333
    CMSG_GET_MAIL_LIST                               = 0x0EA33, // 14333
    SMSG_MAIL_LIST_RESULT                            = 0x0F63A, // 14333
    CMSG_BATTLEFIELD_LIST                            = 0x00508, //
    SMSG_BATTLEFIELD_LIST                            = 0x05301, // 14333
    CMSG_BATTLEFIELD_JOIN                            = 0x0A860, // 14333
    SMSG_JOINED_BATTLEGROUND_QUEUE                   = 0x08707, // 14333
    CMSG_REQUEST_RATED_BG_INFO                       = 0x04000, // 14333
    CMSG_REQUEST_PVP_OPTIONS_ENABLED                 = 0x00188, //
    CMSG_BATTLEMASTER_JOIN_RATED                     = 0x10104, //
    CMSG_TAXICLEARNODE                               = 0x100AD, //
    CMSG_TAXIENABLENODE                              = 0x100AE, //
    CMSG_ITEM_TEXT_QUERY                             = 0x07EF7, // 14333
    SMSG_ITEM_TEXT_QUERY_RESPONSE                    = 0x07A3E, // 14333
    CMSG_MAIL_TAKE_MONEY                             = 0x0AAF2, // 14333
    CMSG_MAIL_TAKE_ITEM                              = 0x0FA3A, // 14333
    CMSG_MAIL_MARK_AS_READ                           = 0x0A2AB, // 14333
    CMSG_MAIL_RETURN_TO_SENDER                       = 0x07662, // 14333
    CMSG_MAIL_DELETE                                 = 0x02EB3, // 14333
    CMSG_MAIL_CREATE_TEXT_ITEM                       = 0x06A6F, // 14333
    SMSG_SPELLLOGMISS                                = 0x07623, // 14333
    SMSG_SPELLLOGEXECUTE                             = 0x0E223, // 14333
    SMSG_DEBUGAURAPROC                               = 0x100B6, //
    SMSG_PERIODICAURALOG                             = 0x0A2A3, // 14333
    SMSG_SPELLDAMAGESHIELD                           = 0x076EE, // 14333
    SMSG_SPELLNONMELEEDAMAGELOG                      = 0x0B2AE, // 14333
    CMSG_LEARN_TALENT                                = 0x0A7CC, // 
    SMSG_RESURRECT_FAILED                            = 0x0D557, //
    CMSG_TOGGLE_PVP                                  = 0x0BA6F, // 14333
    SMSG_ZONE_UNDER_ATTACK                           = 0x0FE72, // 14333
    MSG_AUCTION_HELLO                                = 0x06EAF, // 14333
    CMSG_AUCTION_SELL_ITEM                           = 0x06A6B, // 14333
    CMSG_AUCTION_REMOVE_ITEM                         = 0x0B62A, // 14333
    CMSG_AUCTION_LIST_ITEMS                          = 0x06E77, // 14333
    CMSG_AUCTION_LIST_OWNER_ITEMS                    = 0x02AAB, // 14333
    CMSG_AUCTION_PLACE_BID                           = 0x0227B, // 14333
    SMSG_AUCTION_COMMAND_RESULT                      = 0x0226F, // 14333
    SMSG_AUCTION_LIST_RESULT                         = 0x0EEB7, // 14333
    SMSG_AUCTION_OWNER_LIST_RESULT                   = 0x0E2AB, // 14333
    SMSG_AUCTION_BIDDER_NOTIFICATION                 = 0x0AE67, // 14333
    SMSG_AUCTION_OWNER_NOTIFICATION                  = 0x03E6B, // 14333
    SMSG_PROCRESIST                                  = 0x0BAE3, // 14333
    SMSG_STANDSTATE_CHANGE_FAILURE_OBSOLETE          = 0x0E6FF, // 14333
    SMSG_DISPEL_FAILED                               = 0x0A6F2, // 14333
    SMSG_SPELLORDAMAGE_IMMUNE                        = 0x0E622, // 14333
    CMSG_AUCTION_LIST_BIDDER_ITEMS                   = 0x0BAF6, // 14333
    SMSG_AUCTION_BIDDER_LIST_RESULT                  = 0x06AB7, // 14333
    SMSG_SET_FLAT_SPELL_MODIFIER                     = 0x0B6EB, // 14333
    SMSG_SET_PCT_SPELL_MODIFIER                      = 0x0FAAF, // 14333
    UMSG_SET_AMMO                                    = 0x100BF, // 14333          =*UNUSED*=
    SMSG_CORPSE_RECLAIM_DELAY                        = 0x031C4, //
    CMSG_SET_ACTIVE_MOVER                            = 0x06CA0, //
    CMSG_PET_CANCEL_AURA                             = 0x0F6C0, //
    CMSG_PLAYER_AI_CHEAT                             = 0x100C2, //
    CMSG_CANCEL_AUTO_REPEAT_SPELL                    = 0x075CC, //
    MSG_GM_ACCOUNT_ONLINE                            = 0x100C3, //
    MSG_LIST_STABLED_PETS                            = 0x0B272, // 14333
    SMSG_STABLE_RESULT                               = 0x0EA36, // 14333
    CMSG_STABLE_REVIVE_PET                           = 0x100C7, //
    CMSG_STABLE_CHANGE_SLOT                          = 0x00291, //
    MSG_QUEST_PUSH_RESULT                            = 0x0BE3A, // 14333
    SMSG_PLAY_MUSIC                                  = 0x0AE54, //
    SMSG_PLAY_OBJECT_SOUND                           = 0x07DA0, //
    CMSG_REQUEST_PET_INFO                            = 0x0EAE4, //
    CMSG_FAR_SIGHT                                   = 0x0B2EC, //
    SMSG_SPELLDISPELLOG                              = 0x03C56, //
    SMSG_DAMAGE_CALC_LOG                             = 0x06AEF, // 14333
    CMSG_ENABLE_DAMAGE_LOG                           = 0x100CB, //
    CMSG_GROUP_CHANGE_SUB_GROUP                      = 0x026A2, // 14333
    CMSG_REQUEST_PARTY_MEMBER_STATS                  = 0x0266B, // 14333
    CMSG_GROUP_SWAP_SUB_GROUP                        = 0x0E222, // 14333
    CMSG_RESET_FACTION_CHEAT                         = 0x100CD, //
    CMSG_AUTOSTORE_BANK_ITEM                         = 0x0F2AC, //
    CMSG_AUTOBANK_ITEM                               = 0x066E4, //
    MSG_QUERY_NEXT_MAIL_TIME                         = 0x0FA62, // 14333
    SMSG_RECEIVED_MAIL                               = 0x07EEB, // 14333
    SMSG_RAID_GROUP_ONLY                             = 0x00554, //
    CMSG_SET_DURABILITY_CHEAT                        = 0x100CE, //
    CMSG_SET_PVP_RANK_CHEAT                          = 0x100CF, //
    CMSG_ADD_PVP_MEDAL_CHEAT                         = 0x100D0, //
    CMSG_DEL_PVP_MEDAL_CHEAT                         = 0x100D1, //
    CMSG_SET_PVP_TITLE                               = 0x100D2, //
    SMSG_PVP_CREDIT                                  = 0x0662B, // 14333
    SMSG_AUCTION_REMOVED_NOTIFICATION                = 0x02ABF, // 14333
    CMSG_GROUP_RAID_CONVERT                          = 0x036BE, // 14333
    CMSG_GROUP_ASSISTANT_LEADER                      = 0x06223, // 14333
    CMSG_BUYBACK_ITEM                                = 0x0AAAF, // 14333
    SMSG_SERVER_MESSAGE                              = 0x0E62F, // 14333
    CMSG_SET_SAVED_INSTANCE_EXTEND                   = 0x0AEAB, // 14333
    SMSG_LFG_OFFER_CONTINUE                          = 0x0AAFE, // 14333
    CMSG_MEETINGSTONE_CHEAT                          = 0x100D5, //
    SMSG_MEETINGSTONE_SETQUEUE                       = 0x03A3A, // 14333
    CMSG_MEETINGSTONE_INFO                           = 0x07622, // 14333
    SMSG_MEETINGSTONE_COMPLETE                       = 0x0FA6A, // 14333
    SMSG_MEETINGSTONE_IN_PROGRESS                    = 0x02E7A, // 14333
    SMSG_MEETINGSTONE_MEMBER_ADDED                   = 0x03AEE, // 14333
    CMSG_GMTICKETSYSTEM_TOGGLE                       = 0x100D7, //
    CMSG_CANCEL_GROWTH_AURA                          = 0x0FECC, //
    SMSG_CANCEL_AUTO_REPEAT                          = 0x0FEA7, // 14333
    SMSG_STANDSTATE_UPDATE                           = 0x0E2F6, // 14333
    SMSG_LOOT_ALL_PASSED                             = 0x07222, // 14333
    SMSG_LOOT_ROLL_WON                               = 0x02AAA, // 14333
    CMSG_LOOT_ROLL                                   = 0x02EAF, // 14333
    SMSG_LOOT_START_ROLL                             = 0x0722A, // 14333
    SMSG_LOOT_ROLL                                   = 0x06E33, // 14333
    CMSG_LOOT_MASTER_GIVE                            = 0x02A72, // 14333
    SMSG_LOOT_MASTER_LIST                            = 0x0A2BE, // 14333
    SMSG_SET_FORCED_REACTIONS                        = 0x03EE2, // 14333
    SMSG_SPELL_FAILED_OTHER                          = 0x0E7A4, //
    SMSG_GAMEOBJECT_RESET_STATE                      = 0x022E0, //
    CMSG_REPAIR_ITEM                                 = 0x032BF, // 14333
    SMSG_CHAT_PLAYER_NOT_FOUND                       = 0x035A0, //
    MSG_TALENT_WIPE_CONFIRM                          = 0x02EA7, // 14333
    SMSG_SUMMON_REQUEST                              = 0x022FF, // 14333
    CMSG_SUMMON_RESPONSE                             = 0x07A3A, // 14333
    MSG_MOVE_TOGGLE_GRAVITY_CHEAT                    = 0x100DD, //
    SMSG_MONSTER_MOVE_TRANSPORT                      = 0x0248C, //
    SMSG_PET_BROKEN                                  = 0x075E0, //
    MSG_MOVE_FEATHER_FALL                            = 0x0B6A8, //
    MSG_MOVE_WATER_WALK                              = 0x0E1A4, //
    CMSG_SERVER_BROADCAST                            = 0x100DE, //
    CMSG_SELF_RES                                    = 0x0B2B3, // 14333
    SMSG_FEIGN_DEATH_RESISTED                        = 0x03BE8, //
    CMSG_RUN_SCRIPT                                  = 0x100DF, //
    SMSG_SCRIPT_MESSAGE                              = 0x100E0, //
    SMSG_DUEL_COUNTDOWN                              = 0x07E73, // 14333
    SMSG_AREA_TRIGGER_MESSAGE                        = 0x0EAE0, //
    CMSG_SHOWING_HELM                                = 0x0B667, // 14333
    CMSG_SHOWING_CLOAK                               = 0x03636, // 14333
    SMSG_LFG_ROLE_CHOSEN                             = 0x0A9AC, //
    SMSG_PLAYER_SKINNED                              = 0x0FAF6, // 14333
    SMSG_DURABILITY_DAMAGE_DEATH                     = 0x0FDA0, //
    CMSG_SET_EXPLORATION                             = 0x100E1, //
    CMSG_SET_ACTIONBAR_TOGGLES                       = 0x0BE62, // 14333
    MSG_PETITION_RENAME                              = 0x0FAFA, // 14333
    SMSG_INIT_WORLD_STATES                           = 0x0F6E8, //
    SMSG_UPDATE_WORLD_STATE                          = 0x0F784, //
    CMSG_ITEM_NAME_QUERY                             = 0x07EF7, // 14333
    SMSG_ITEM_NAME_QUERY_RESPONSE                    = 0x07BC8, //
    SMSG_PET_ACTION_FEEDBACK                         = 0x06A7B, // 14333
    CMSG_CHAR_RENAME                                 = 0x06263, // 14333
    SMSG_CHAR_RENAME                                 = 0x0E0EC, //
    CMSG_MOVE_SPLINE_DONE                            = 0x069E8, //
    CMSG_MOVE_FALL_RESET                             = 0x100E6, //
    SMSG_INSTANCE_SAVE_CREATED                       = 0x0AE2B, // 14333
    SMSG_RAID_INSTANCE_INFO                          = 0x100E7, //
    CMSG_REQUEST_RAID_INFO                           = 0x0B672, // 14333
    CMSG_MOVE_TIME_SKIPPED                           = 0x0E180, //
    CMSG_MOVE_FEATHER_FALL_ACK                       = 0x06EA8, //
    CMSG_MOVE_WATER_WALK_ACK                         = 0x021C4, //
    CMSG_MOVE_NOT_ACTIVE_MOVER                       = 0x0B9A8, //
    SMSG_PLAY_SOUND                                  = 0x02622, // 14333
    CMSG_BATTLEFIELD_STATUS                          = 0x03620, // 14333
    SMSG_BATTLEFIELD_STATUS1                         = 0x00B07, // 14333
    SMSG_BATTLEFIELD_STATUS2                         = 0x04B05, // 14333
    SMSG_BATTLEFIELD_STATUS3                         = 0x04F63, // 14333
    SMSG_BATTLEFIELD_STATUS4                         = 0x00303, // 14333
    CMSG_BATTLEFIELD_PORT                            = 0x00E11, //
    CMSG_INSPECT_HONOR_STATS                         = 0x00E93, //
    SMSG_INSPECT_HONOR_STATS                         = 0x0005E, //
    CMSG_BATTLEMASTER_HELLO                          = 0x06D57, //
    CMSG_MOVE_START_SWIM_CHEAT                       = 0x026C0, //
    CMSG_MOVE_STOP_SWIM_CHEAT                        = 0x06988, //
    SMSG_FORCE_WALK_SPEED_CHANGE                     = 0x068E8, //
    CMSG_FORCE_WALK_SPEED_CHANGE_ACK                 = 0x078CC, //
    SMSG_FORCE_SWIM_BACK_SPEED_CHANGE                = 0x002DC, // 
    CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK            = 0x0E8C4, //
    SMSG_FORCE_TURN_RATE_CHANGE                      = 0x0375E, //
    CMSG_FORCE_TURN_RATE_CHANGE_ACK                  = 0x0E384, //
    MSG_PVP_LOG_DATA                                 = 0x05365, // 14333
    CMSG_BATTLEFIELD_REQUEST_SCORE_DATA              = 0x0886B, // 14333
    CMSG_LEAVE_BATTLEFIELD                           = 0x06EF2, // 14333
    CMSG_AREA_SPIRIT_HEALER_QUERY                    = 0x032EB, // 14333
    CMSG_AREA_SPIRIT_HEALER_QUEUE                    = 0x03AE6, // 14333
    SMSG_AREA_SPIRIT_HEALER_TIME                     = 0x06D80, //
    CMSG_GM_UNTEACH                                  = 0x100FD, //
    SMSG_WARDEN_DATA                                 = 0x07A36, // 14333
    CMSG_WARDEN_DATA                                 = 0x0E2FB, // 14333
    SMSG_GROUP_JOINED_BATTLEGROUND                   = 0x0DB01, // 14333
    CMSG_BATTLEGROUND_PLAYER_POSITIONS               = 0x098EB, // 14333
    SMSG_BATTLEGROUND_PLAYER_POSITIONS               = 0x0045C, //
    CMSG_PET_STOP_ATTACK                             = 0x0FA66, // 14333
    SMSG_BINDER_CONFIRM                              = 0x033C4, //
    SMSG_BATTLEGROUND_PLAYER_JOINED                  = 0x0494C, //
    SMSG_BATTLEGROUND_PLAYER_LEFT                    = 0x00D1C, //
    CMSG_BATTLEMASTER_JOIN                           = 0x00137, //
    SMSG_ADDON_INFO                                  = 0x06AAE, // 14333
    CMSG_PET_UNLEARN                                 = 0x10105, //
    SMSG_PET_UNLEARN_CONFIRM                         = 0x10106, //
    SMSG_PARTY_MEMBER_STATS_FULL                     = 0x0BA8C, //
    CMSG_PET_SPELL_AUTOCAST                          = 0x066FE, // 14333
    SMSG_WEATHER                                     = 0x0FE2A, // 14333
    SMSG_PLAY_TIME_WARNING                           = 0x0EAE6, // 14333
    SMSG_MINIGAME_SETUP                              = 0x0F277, // 14333
    SMSG_MINIGAME_STATE                              = 0x04C7F, //
    CMSG_MINIGAME_MOVE                               = 0x0FAEA, // 14333
    SMSG_MINIGAME_MOVE_FAILED                        = 0x10109, //
    SMSG_RAID_INSTANCE_MESSAGE                       = 0x06677, // 14333
    SMSG_COMPRESSED_MOVES                            = 0x0662F, // 14333
    CMSG_GUILD_INFO_TEXT                             = 0x0270D, //
    SMSG_CHAT_RESTRICTED                             = 0x07667, // 14333
    SMSG_SPLINE_SET_RUN_SPEED                        = 0x0F9E8, //
    SMSG_SPLINE_SET_RUN_BACK_SPEED                   = 0x0E9C0, //
    SMSG_SPLINE_SET_SWIM_SPEED                       = 0x0B2C0, //
    SMSG_SPLINE_SET_WALK_SPEED                       = 0x03EA8, //
    SMSG_SPLINE_SET_SWIM_BACK_SPEED                  = 0x021C8, //
    SMSG_SPLINE_SET_TURN_RATE                        = 0x07EAC, //
    SMSG_SPLINE_MOVE_UNROOT                          = 0x1010B, //
    SMSG_SPLINE_MOVE_FEATHER_FALL                    = 0x1010C, //
    SMSG_SPLINE_MOVE_NORMAL_FALL                     = 0x1010D, //
    SMSG_SPLINE_MOVE_SET_HOVER                       = 0x1010E, //
    SMSG_SPLINE_MOVE_UNSET_HOVER                     = 0x1010F, //
    SMSG_SPLINE_MOVE_WATER_WALK                      = 0x061C0, //
    SMSG_SPLINE_MOVE_LAND_WALK                       = 0x0A7C8, //
    SMSG_SPLINE_MOVE_START_SWIM                      = 0x10112, //
    SMSG_SPLINE_MOVE_STOP_SWIM                       = 0x10113, //
    SMSG_SPLINE_MOVE_SET_RUN_MODE                    = 0x10114, //
    SMSG_SPLINE_MOVE_SET_WALK_MODE                   = 0x10115, //
    CMSG_GM_NUKE_ACCOUNT                             = 0x10116, //
    MSG_GM_DESTROY_CORPSE                            = 0x10117, //
    CMSG_GM_DESTROY_ONLINE_CORPSE                    = 0x10118, //
    CMSG_ACTIVATETAXIEXPRESS                         = 0x0E6E6, // 14333
    SMSG_SET_FACTION_ATWAR                           = 0x07ABE, // 14333
    SMSG_GAMETIMEBIAS_SET                            = 0x1011A, //
    CMSG_DEBUG_ACTIONS_START                         = 0x1011B, //
    CMSG_DEBUG_ACTIONS_STOP                          = 0x1011C, //
    CMSG_SET_FACTION_INACTIVE                        = 0x0FE33, // 14333
    CMSG_SET_WATCHED_FACTION                         = 0x03637, // 14333
    MSG_MOVE_TIME_SKIPPED                            = 0x025E4, //
    SMSG_SPLINE_MOVE_ROOT                            = 0x01E55, //
    CMSG_SET_EXPLORATION_ALL                         = 0x10120, //
    SMSG_INVALIDATE_PLAYER                           = 0x0A2FF, // 14333
    CMSG_RESET_INSTANCES                             = 0x0E22B, // 14333
    SMSG_INSTANCE_RESET                              = 0x0B6B3, // 14333
    SMSG_INSTANCE_RESET_FAILED                       = 0x0326B, // 14333
    SMSG_UPDATE_LAST_INSTANCE                        = 0x0AA32, // 14333
    MSG_RAID_TARGET_UPDATE                           = 0x0A5AC, //
    MSG_RAID_READY_CHECK                             = 0x0A63A, // 14333
    CMSG_LUA_USAGE                                   = 0x10122, //
    SMSG_PET_ACTION_SOUND                            = 0x062FB, // 14333
    SMSG_PET_DISMISS_SOUND                           = 0x03EF3, // 14333
    SMSG_GHOSTEE_GONE                                = 0x10123, //
    CMSG_GM_UPDATE_TICKET_STATUS                     = 0x10124, //
    SMSG_GM_TICKET_STATUS_UPDATE                     = 0x072C4, // 
    MSG_SET_DUNGEON_DIFFICULTY                       = 0x0A23E, // 14333 
    CMSG_GMSURVEY_SUBMIT                             = 0x0BEBB, // 14333
    SMSG_UPDATE_INSTANCE_OWNERSHIP                   = 0x07A2B, // 14333
    CMSG_IGNORE_KNOCKBACK_CHEAT                      = 0x10126, //
    SMSG_CHAT_PLAYER_AMBIGUOUS                       = 0x06AE8, //
    MSG_DELAY_GHOST_TELEPORT                         = 0x10127, //
    SMSG_SPELLINSTAKILLLOG                           = 0x062FE, // 14333
    SMSG_SPELL_UPDATE_CHAIN_TARGETS                  = 0x036A4, //
    CMSG_CHAT_FILTERED                               = 0x00D5D, //
    SMSG_EXPECTED_SPAM_RECORDS                       = 0x0AEB3, // 14333
    SMSG_SPELLSTEALLOG                               = 0x09F74, //
    CMSG_LOTTERY_QUERY_OBSOLETE                      = 0x10129, //
    SMSG_LOTTERY_QUERY_RESULT_OBSOLETE               = 0x1012A, //
    CMSG_BUY_LOTTERY_TICKET_OBSOLETE                 = 0x00336, //
    SMSG_LOTTERY_RESULT_OBSOLETE                     = 0x1012C, //
    SMSG_CHARACTER_PROFILE                           = 0x1012D, //
    SMSG_CHARACTER_PROFILE_REALM_CONNECTED           = 0x1012E, //
    SMSG_DEFENSE_MESSAGE                             = 0x0F6B6, // 14333
    SMSG_INSTANCE_DIFFICULTY                         = 0x0A55E, //
    MSG_GM_RESETINSTANCELIMIT                        = 0x1012F, //
    SMSG_MOTD                                        = 0x077C0, //
    SMSG_MOVE_SET_FLIGHT                             = 0x0C57F, //
    SMSG_MOVE_UNSET_FLIGHT                           = 0x0BDA0, //
    CMSG_MOVE_FLIGHT_ACK                             = 0x0A3C8, //
    MSG_MOVE_START_SWIM_CHEAT                        = 0x026C0, //
    MSG_MOVE_STOP_SWIM_CHEAT                         = 0x06988, //
    SMSG_MOVE_SET_CAN_FLY                            = 0x0BDA0, //
    SMSG_MOVE_UNSET_CAN_FLY                          = 0x03084, //
    CMSG_MOVE_SET_CAN_FLY_ACK                        = 0x0FCAC, //
    CMSG_MOVE_SET_FLY                                = 0x0E0E0, //
    CMSG_SOCKET_GEMS                                 = 0x026AB, // 14333
    CMSG_ARENA_TEAM_CREATE                           = 0x00509, //
    SMSG_ARENA_TEAM_COMMAND_RESULT                   = 0x08B45, // 14333
    CMSG_ARENA_TEAM_QUERY                            = 0x0F62E, // 14333
    SMSG_ARENA_TEAM_QUERY_RESPONSE                   = 0x0FE2F, // 14333
    CMSG_ARENA_TEAM_ROSTER                           = 0x07A66, // 14333
    SMSG_ARENA_TEAM_ROSTER                           = 0x0A276, // 14333
    CMSG_ARENA_TEAM_INVITE                           = 0x0AA3B, // 14333
    SMSG_ARENA_TEAM_INVITE                           = 0x0AAEA, // 14333
    CMSG_ARENA_TEAM_ACCEPT                           = 0x02EB7, // 14333
    CMSG_ARENA_TEAM_DECLINE                          = 0x0AEE7, // 14333
    CMSG_ARENA_TEAM_LEAVE                            = 0x03A66, // 14333
    CMSG_ARENA_TEAM_REMOVE                           = 0x0BEEF, // 14333
    CMSG_ARENA_TEAM_DISBAND                          = 0x0E2E3, // 14333
    CMSG_ARENA_TEAM_LEADER                           = 0x06E6B, // 14333
    SMSG_ARENA_TEAM_EVENT                            = 0x07273, // 14333
    CMSG_BATTLEMASTER_JOIN_ARENA                     = 0x00311, //
    MSG_MOVE_START_ASCEND                            = 0x0BDC0, //
    MSG_MOVE_STOP_ASCEND                             = 0x0FCA8, //
    SMSG_ARENA_TEAM_STATS                            = 0x02EBB, // 14333
    CMSG_LFG_JOIN                                    = 0x03EB2, // 14333
    CMSG_LFG_LEAVE                                   = 0x072A6, // 14333
    CMSG_SEARCH_LFG_JOIN                             = 0x061CC, //
    CMSG_SEARCH_LFG_LEAVE                            = 0x0FAEA, // 14333
    SMSG_UPDATE_LFG_LIST                             = 0x0768C, //
    SMSG_LFG_PROPOSAL_UPDATE                         = 0x032AC, //
    CMSG_LFG_PROPOSAL_RESULT                         = 0x0BAEA, // 14333
    SMSG_LFG_ROLE_CHECK_UPDATE                       = 0x026A3, // 14333
    SMSG_LFG_JOIN_RESULT                             = 0x0366A, // 14333
    SMSG_LFG_QUEUE_STATUS                            = 0x06E76, // 14333
    CMSG_SET_LFG_COMMENT                             = 0x0E676, // 14333
    SMSG_LFG_UPDATE_PLAYER                           = 0x07A27, // 14333
    SMSG_LFG_UPDATE_PARTY                            = 0x0666E, // 14333
    SMSG_LFG_UPDATE_LIST                             = 0x03880, //
    CMSG_LFG_SET_ROLES                               = 0x026F7, // 14333
    CMSG_LFG_SET_NEEDS                               = 0x10145, //
    CMSG_LFG_SET_BOOT_VOTE                           = 0x0A6FB, // 14333
    SMSG_LFG_BOOT_PROPOSAL_UPDATE                    = 0x079AC, // 
    CMSG_LFD_PLAYER_LOCK_INFO_REQUEST                = 0x00C76, //
    SMSG_LFG_PLAYER_INFO                             = 0x0E088, //
    CMSG_LFG_TELEPORT                                = 0x0B673, // 14333
    CMSG_LFD_PARTY_LOCK_INFO_REQUEST                 = 0x0B2FE, // 14333
    SMSG_LFG_PARTY_INFO                              = 0x0AEAA, // 14333
    SMSG_TITLE_EARNED                                = 0x0AEBA, // 14333
    CMSG_SET_TITLE                                   = 0x0627B, // 14333
    CMSG_CANCEL_MOUNT_AURA                           = 0x0FEBA, // 14333
    SMSG_ARENA_ERROR                                 = 0x0F2FE, // 14333
    MSG_INSPECT_ARENA_TEAMS                          = 0x072A3, // 14333
    SMSG_DEATH_RELEASE_LOC                           = 0x033C8, //
    CMSG_CANCEL_TEMP_ENCHANTMENT                     = 0x0A22E, // 14333
    SMSG_FORCED_DEATH_UPDATE                         = 0x0FFE8, //
    CMSG_CHEAT_SET_HONOR_CURRENCY                    = 0x1014D, //
    CMSG_CHEAT_SET_ARENA_CURRENCY                    = 0x1014E, //
    SMSG_INIT_CURRENCY                               = 0x0091C, //
    SMSG_UPDATE_CURRENCY                             = 0x0405E, //
    SMSG_UPDATE_CURRENCY_WEEK_LIMIT                  = 0x04C5C, //
    MSG_MOVE_SET_FLIGHT_SPEED_CHEAT                  = 0x1014F, //
    MSG_MOVE_SET_FLIGHT_SPEED                        = 0x0B088, //
    MSG_MOVE_SET_FLIGHT_BACK_SPEED_CHEAT             = 0x10150, //
    MSG_MOVE_SET_FLIGHT_BACK_SPEED                   = 0x0B484, //
    SMSG_FORCE_FLIGHT_SPEED_CHANGE                   = 0x0E5CC, //
    CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK               = 0x0A98C, //
    SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE              = 0x10153, //
    CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK          = 0x0FBC8, //
    SMSG_SPLINE_SET_FLIGHT_SPEED                     = 0x0E0C0, //
    SMSG_SPLINE_SET_FLIGHT_BACK_SPEED                = 0x0F2EC, //
    CMSG_MAELSTROM_INVALIDATE_CACHE                  = 0x10155, //
    SMSG_FLIGHT_SPLINE_SYNC                          = 0x0FEF2, // 14333
    CMSG_SET_TAXI_BENCHMARK_MODE                     = 0x07E3F, // 14333
    SMSG_REALM_SPLIT                                 = 0x0692C, // 14333
    CMSG_REALM_SPLIT                                 = 0x0B6E2, // 14333
    CMSG_MOVE_CHNG_TRANSPORT                         = 0x10158, //
    MSG_PARTY_ASSIGNMENT                             = 0x0A22A, // 14333
    SMSG_OFFER_PETITION_ERROR                        = 0x0267B, // 14333
    SMSG_TIME_SYNC_REQ                               = 0x0AA80, //
    CMSG_TIME_SYNC_RESP                              = 0x0A8AC, //
    CMSG_SEND_LOCAL_EVENT                            = 0x1015A, //
    CMSG_SEND_GENERAL_TRIGGER                        = 0x1015B, //
    CMSG_SEND_COMBAT_TRIGGER                         = 0x1015C, //
    CMSG_MAELSTROM_GM_SENT_MAIL                      = 0x1015D, //
    SMSG_RESET_FAILED_NOTIFY                         = 0x0BD5C, //
    SMSG_REAL_GROUP_UPDATE                           = 0x0A66F, // 14333
    SMSG_LFG_DISABLED                                = 0x0AEFF, // 14333
    CMSG_ACTIVE_PVP_CHEAT                            = 0x1015E, //
    CMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY                 = 0x1015F, //
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE        = 0x10160, //
    SMSG_CHEAT_DUMP_ITEMS_DEBUG_ONLY_RESPONSE_WRITE_FILE  = 0x10161, //
    SMSG_UPDATE_COMBO_POINTS                         = 0x0BE73, // 14333
    SMSG_VOICE_SESSION_ROSTER_UPDATE                 = 0x0F666, // 14333
    SMSG_VOICE_SESSION_LEAVE                         = 0x0EA27, // 14333
    SMSG_VOICE_SESSION_ADJUST_PRIORITY               = 0x10165, //
    CMSG_VOICE_SET_TALKER_MUTED_REQUEST              = 0x10166, //
    SMSG_VOICE_SET_TALKER_MUTED                      = 0x0B6A2, // 14333
    SMSG_INIT_EXTRA_AURA_INFO_OBSOLETE               = 0x10168, //
    SMSG_SET_EXTRA_AURA_INFO_OBSOLETE                = 0x10169, //
    SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE_OBSOLETE    = 0x1016A, //
    SMSG_CLEAR_EXTRA_AURA_INFO_OBSOLETE              = 0x1016B, //
    MSG_MOVE_START_DESCEND                           = 0x07880, //
    CMSG_IGNORE_REQUIREMENTS_CHEAT                   = 0x1016D, //
    SMSG_IGNORE_REQUIREMENTS_CHEAT                   = 0x07C84, //
    SMSG_SPELL_CHANCE_PROC_LOG                       = 0x1016E, //
    CMSG_MOVE_SET_RUN_SPEED                          = 0x1016F, //
    SMSG_DISMOUNT                                    = 0x0263B, // 14333
    MSG_MOVE_UPDATE_CAN_FLY                          = 0x025E0, //
    MSG_RAID_READY_CHECK_CONFIRM                     = 0x0AE76, // 14333
    CMSG_VOICE_SESSION_ENABLE                        = 0x0FEA4, //
    SMSG_VOICE_SESSION_ENABLE                        = 0x10170, //
    SMSG_VOICE_PARENTAL_CONTROLS                     = 0x0B6EA, // 14333
    CMSG_GM_WHISPER                                  = 0x10172, //
    SMSG_GM_MESSAGECHAT                              = 0x0A262, // 14333
    MSG_GM_GEARRATING                                = 0x10173, //
    CMSG_COMMENTATOR_ENABLE                          = 0x0366F, // 14333
    SMSG_COMMENTATOR_STATE_CHANGED                   = 0x0E0E4, //
    CMSG_COMMENTATOR_GET_MAP_INFO                    = 0x0E2F2, // 14333
    SMSG_COMMENTATOR_MAP_INFO                        = 0x0A4E8, //
    CMSG_COMMENTATOR_GET_PLAYER_INFO                 = 0x0BA7B, // 14333
    SMSG_COMMENTATOR_GET_PLAYER_INFO                 = 0x10177, //
    SMSG_COMMENTATOR_PLAYER_INFO                     = 0x0758C, //
    CMSG_COMMENTATOR_ENTER_INSTANCE                  = 0x0362F, // 14333
    CMSG_COMMENTATOR_EXIT_INSTANCE                   = 0x0E6F7, // 14333
    CMSG_COMMENTATOR_INSTANCE_COMMAND                = 0x072F7, // 14333
    SMSG_CLEAR_TARGET                                = 0x0A7AC, //
    CMSG_BOT_DETECTED                                = 0x0E757, //
    SMSG_CROSSED_INEBRIATION_THRESHOLD               = 0x026FF, // 14333
    CMSG_CHEAT_PLAYER_LOGIN                          = 0x1017D, //
    CMSG_CHEAT_PLAYER_LOOKUP                         = 0x1017E, //
    SMSG_CHEAT_PLAYER_LOOKUP                         = 0x1017F, //
    SMSG_KICK_REASON                                 = 0x0EAC8, //
    MSG_RAID_READY_CHECK_FINISHED                    = 0x0A0A0, //
    CMSG_COMPLAIN                                    = 0x0EA63, // 14333
    SMSG_COMPLAIN_RESULT                             = 0x070CC, //
    SMSG_FEATURE_SYSTEM_STATUS                       = 0x03DAC, //
    CMSG_GM_SHOW_COMPLAINTS                          = 0x10181, //
    CMSG_GM_UNSQUELCH                                = 0x10182, //
    CMSG_CHANNEL_SILENCE_VOICE                       = 0x00801, //
    CMSG_CHANNEL_SILENCE_ALL                         = 0x00021, //
    CMSG_CHANNEL_UNSILENCE_VOICE                     = 0x0002B, //
    CMSG_CHANNEL_UNSILENCE_ALL                       = 0x00840, //
    CMSG_TARGET_CAST                                 = 0x10183, //
    CMSG_TARGET_SCRIPT_CAST                          = 0x10184, //
    CMSG_CHANNEL_DISPLAY_LIST                        = 0x10185, //
    CMSG_SET_ACTIVE_VOICE_CHANNEL                    = 0x032A4, //
    CMSG_GET_CHANNEL_MEMBER_COUNT                    = 0x00009, //
    SMSG_CHANNEL_MEMBER_COUNT                        = 0x0FAF7, // 14333
    CMSG_CHANNEL_VOICE_ON                            = 0x05A98, //
    CMSG_CHANNEL_VOICE_OFF                           = 0x07A88, //
    CMSG_DEBUG_LIST_TARGETS                          = 0x10187, //
    SMSG_DEBUG_LIST_TARGETS                          = 0x10188, //
    SMSG_AVAILABLE_VOICE_CHANNEL                     = 0x066F3, // 14333
    CMSG_ADD_VOICE_IGNORE                            = 0x02AAE, // 14333
    CMSG_DEL_VOICE_IGNORE                            = 0x0BD7E, //
    CMSG_PARTY_SILENCE                               = 0x062EB, // 14333
    CMSG_PARTY_UNSILENCE                             = 0x0F637, // 14333
    MSG_NOTIFY_PARTY_SQUELCH                         = 0x0E8E8, //
    SMSG_COMSAT_RECONNECT_TRY                        = 0x07E7E, //
    SMSG_COMSAT_DISCONNECT                           = 0x02E57, //
    SMSG_COMSAT_CONNECT_FAIL                         = 0x0647E, //
    SMSG_VOICE_CHAT_STATUS                           = 0x02EAA, // 14333
    CMSG_REPORT_PVP_AFK                              = 0x06E22, // 14333
    SMSG_REPORT_PVP_AFK_RESULT                       = 0x078E8, //
    CMSG_GUILD_BANKER_ACTIVATE                       = 0x0FFC4, //
    CMSG_GUILD_BANK_QUERY_TAB                        = 0x0A623, // 14333
    SMSG_GUILD_BANK_LIST                             = 0x0A6A8, //
    CMSG_GUILD_BANK_SWAP_ITEMS                       = 0x0FAF2, // 14333
    CMSG_GUILD_BANK_BUY_TAB                          = 0x036B3, // 14333
    CMSG_GUILD_BANK_UPDATE_TAB                       = 0x0727B, // 14333
    CMSG_GUILD_BANK_DEPOSIT_MONEY                    = 0x02A2F, // 14333
    CMSG_GUILD_BANK_WITHDRAW_MONEY                   = 0x022EE, // 14333
    CMSG_GUILD_BANK_NOTE                             = 0x07680, //
    MSG_GUILD_BANK_LOG_QUERY                         = 0x072EA, // 14333
    CMSG_SET_CHANNEL_WATCH                           = 0x07FE0, //
    SMSG_USERLIST_ADD                                = 0x0B67F, // 14333
    SMSG_USERLIST_REMOVE                             = 0x0E2E6, // 14333
    SMSG_USERLIST_UPDATE                             = 0x0BAE7, // 14333
    CMSG_CLEAR_CHANNEL_WATCH                         = 0x03EA2, // 14333
    SMSG_INSPECT_TALENT                              = 0x0F8C0, //
    SMSG_GOGOGO_OBSOLETE                             = 0x10195, //
    SMSG_ECHO_PARTY_SQUELCH                          = 0x02A7A, // 14333
    CMSG_SET_TITLE_SUFFIX                            = 0x10196, //
    CMSG_SPELLCLICK                                  = 0x0F9A4, // 
    SMSG_LOOT_LIST                                   = 0x0B2AB, // 14333
    CMSG_GM_CHARACTER_RESTORE                        = 0x10198, //
    CMSG_GM_CHARACTER_SAVE                           = 0x10199, //
    SMSG_VOICESESSION_FULL                           = 0x0A456, //
    MSG_GUILD_PERMISSIONS                            = 0x0E22E, // 14333
    MSG_GUILD_BANK_MONEY_WITHDRAWN                   = 0x06CE4, //
    MSG_GUILD_EVENT_LOG_QUERY                        = 0x0AEBE, // 14333
    CMSG_MAELSTROM_RENAME_GUILD                      = 0x1019A, //
    CMSG_GET_MIRRORIMAGE_DATA                        = 0x0EEEA, // 14333
    SMSG_MIRRORIMAGE_DATA                            = 0x02A6B, // 14333
    SMSG_FORCE_DISPLAY_UPDATE                        = 0x022AE, // 14333
    SMSG_SPELL_CHANCE_RESIST_PUSHBACK                = 0x1019C, // 
    CMSG_IGNORE_DIMINISHING_RETURNS_CHEAT            = 0x1019D, //
    SMSG_IGNORE_DIMINISHING_RETURNS_CHEAT            = 0x0747E, //
    CMSG_KEEP_ALIVE                                  = 0x0E6BF, // 14333
    SMSG_RAID_READY_CHECK_ERROR                      = 0x0547E, //
    CMSG_OPT_OUT_OF_LOOT                             = 0x0BEA3, // 14333
    MSG_QUERY_GUILD_BANK_TEXT                        = 0x0A236, // 14333
    CMSG_SET_GUILD_BANK_TEXT                         = 0x06E26, // 14333
    CMSG_SET_GRANTABLE_LEVELS                        = 0x101A1, //
    CMSG_GRANT_LEVEL                                 = 0x03A2E, // 14333
    CMSG_REFER_A_FRIEND                              = 0x101A2, //
    MSG_GM_CHANGE_ARENA_RATING                       = 0x101A3, //
    CMSG_DECLINE_CHANNEL_INVITE                      = 0x0DF7F, //
    SMSG_GROUPACTION_THROTTLED                       = 0x101A5, //
    SMSG_OVERRIDE_LIGHT                              = 0x03A36, // 14333
    SMSG_TOTEM_CREATED                               = 0x02EAC, //
    CMSG_TOTEM_DESTROYED                             = 0x03EB7, // 14333
    CMSG_EXPIRE_RAID_INSTANCE                        = 0x101A7, //
    CMSG_NO_SPELL_VARIANCE                           = 0x101A8, //
    CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY            = 0x0A2FA, // 14333
    SMSG_QUESTGIVER_STATUS_MULTIPLE                  = 0x0F5C0, //
    CMSG_SET_PLAYER_DECLINED_NAMES                   = 0x03EE6, // 14333
    SMSG_SET_PLAYER_DECLINED_NAMES_RESULT            = 0x0BAAC, //
    CMSG_QUERY_SERVER_BUCK_DATA                      = 0x101AC, //
    CMSG_CLEAR_SERVER_BUCK_DATA                      = 0x101AD, //
    SMSG_SERVER_BUCK_DATA                            = 0x101AE, //
    SMSG_SEND_UNLEARN_SPELLS                         = 0x0AAE2, // 14333
    SMSG_PROPOSE_LEVEL_GRANT                         = 0x0B476, //
    CMSG_ACCEPT_LEVEL_GRANT                          = 0x0E2A2, // 14333
    SMSG_REFER_A_FRIEND_FAILURE                      = 0x066BF, // 14333
    SMSG_SPLINE_MOVE_SET_FLYING                      = 0x05D54, //
    SMSG_SPLINE_MOVE_UNSET_FLYING                    = 0x07688, //
    SMSG_SUMMON_CANCEL                               = 0x070A8, //
    CMSG_CHANGE_PERSONAL_ARENA_RATING                = 0x101B2, //
    CMSG_ALTER_APPEARANCE                            = 0x07EA3, // 14333
    SMSG_ENABLE_BARBER_SHOP                          = 0x0367A, // 14333
    SMSG_BARBER_SHOP_RESULT                          = 0x0FEEA, // 14333
    CMSG_CALENDAR_GET_CALENDAR                       = 0x02672, // 14333
    CMSG_CALENDAR_GET_EVENT                          = 0x0FE6E, // 14333
    CMSG_CALENDAR_GUILD_FILTER                       = 0x03E72, // 14333
    CMSG_CALENDAR_ARENA_TEAM                         = 0x0E9AC, //
    CMSG_CALENDAR_ADD_EVENT                          = 0x0EAA2, // 14333
    CMSG_CALENDAR_UPDATE_EVENT                       = 0x0723A, // 14333
    CMSG_CALENDAR_REMOVE_EVENT                       = 0x06C88, //
    CMSG_CALENDAR_COPY_EVENT                         = 0x0BF84, //
    CMSG_CALENDAR_EVENT_INVITE                       = 0x0EEB2, // 14333
    CMSG_CALENDAR_EVENT_RSVP                         = 0x06EA7, // 14333
    CMSG_CALENDAR_EVENT_REMOVE_INVITE                = 0x0AA7A, // 14333
    CMSG_CALENDAR_EVENT_STATUS                       = 0x0A26F, // 14333
    CMSG_CALENDAR_EVENT_MODERATOR_STATUS             = 0x06E37, // 14333
    SMSG_CALENDAR_SEND_CALENDAR                      = 0x0B0A4, //
    SMSG_CALENDAR_SEND_EVENT                         = 0x0FAA4, //
    SMSG_CALENDAR_FILTER_GUILD                       = 0x02FC4, //
    SMSG_CALENDAR_ARENA_TEAM                         = 0x021E0, //
    SMSG_CALENDAR_EVENT_INVITE                       = 0x0A5A0, //
    SMSG_CALENDAR_EVENT_INVITE_REMOVED               = 0x0A9E0, //
    SMSG_CALENDAR_EVENT_STATUS                       = 0x07EC0, //
    SMSG_CALENDAR_COMMAND_RESULT                     = 0x0BE2A, // 14333
    SMSG_CALENDAR_RAID_LOCKOUT_ADDED                 = 0x02AE0, //
    SMSG_CALENDAR_RAID_LOCKOUT_REMOVED               = 0x0FCE0, //
    SMSG_CALENDAR_EVENT_INVITE_ALERT                 = 0x0AFA8, //
    SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT         = 0x0FEE0, //
    SMSG_CALENDAR_EVENT_INVITE_STATUS_ALERT          = 0x0F7C8, //
    SMSG_CALENDAR_EVENT_REMOVED_ALERT                = 0x06288, //
    SMSG_CALENDAR_EVENT_UPDATED_ALERT                = 0x029C0, //
    SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT       = 0x0ABC8, //
    CMSG_CALENDAR_COMPLAIN                           = 0x01E75, //
    CMSG_CALENDAR_GET_NUM_PENDING                    = 0x0EFAC, //
    SMSG_CALENDAR_SEND_NUM_PENDING                   = 0x0A8E0, //
    CMSG_SAVE_DANCE                                  = 0x101C3, //
    SMSG_NOTIFY_DANCE                                = 0x02632, // 14333
    CMSG_PLAY_DANCE                                  = 0x0323B, // 14333
    SMSG_PLAY_DANCE                                  = 0x032B3, // 14333
    CMSG_LOAD_DANCES                                 = 0x101C4, //
    CMSG_STOP_DANCE                                  = 0x02EF3, // 14333
    SMSG_STOP_DANCE                                  = 0x072BF, // 14333
    CMSG_SYNC_DANCE                                  = 0x101C6, //
    CMSG_DANCE_QUERY                                 = 0x0A6BF, // 14333
    SMSG_DANCE_QUERY_RESPONSE                        = 0x03EFB, // 14333
    SMSG_INVALIDATE_DANCE                            = 0x022AA, // 14333
    CMSG_DELETE_DANCE                                = 0x101C8, //
    SMSG_LEARNED_DANCE_MOVES                         = 0x0A6EB, // 14333
    CMSG_LEARN_DANCE_MOVE                            = 0x101C9, //
    CMSG_UNLEARN_DANCE_MOVE                          = 0x101CA, //
    CMSG_SET_RUNE_COUNT                              = 0x101CB, //
    CMSG_SET_RUNE_COOLDOWN                           = 0x101CC, //
    MSG_MOVE_SET_PITCH_RATE_CHEAT                    = 0x101CD, //
    MSG_MOVE_SET_PITCH_RATE                          = 0x0ABA4, //
    SMSG_FORCE_PITCH_RATE_CHANGE                     = 0x101CE, //
    CMSG_FORCE_PITCH_RATE_CHANGE_ACK                 = 0x0E6C0, //
    SMSG_SPLINE_SET_PITCH_RATE                       = 0x070c4, //
    SMSG_MOVE_ABANDON_TRANSPORT                      = 0x101D0, //
    SMSG_CALENDAR_UPDATE_INVITE_LIST                 = 0x071A0, //
    SMSG_CALENDAR_UPDATE_INVITE_LIST2                = 0x0EDC4, //
    CMSG_UPDATE_MISSILE_TRAJECTORY                   = 0x00E54, //
    SMSG_UPDATE_ACCOUNT_DATA_COMPLETE                = 0x0B1CC, //
    SMSG_TRIGGER_MOVIE                               = 0x101D2, //
    CMSG_COMPLETE_MOVIE                              = 0x0F63F, // 14333
    CMSG_SET_GLYPH_SLOT                              = 0x101D4, //
    CMSG_SET_GLYPH                                   = 0x101D5, //
    SMSG_ACHIEVEMENT_EARNED                          = 0x0F5E4, //
    SMSG_DYNAMIC_DROP_ROLL_RESULT                    = 0x101D7, //
    SMSG_CRITERIA_UPDATE                             = 0x0AFC8, // 
    CMSG_QUERY_INSPECT_ACHIEVEMENTS                  = 0x032A7, // 14333
    SMSG_RESPOND_INSPECT_ACHIEVEMENTS                = 0x101DA, //
    CMSG_DISMISS_CONTROLLED_VEHICLE                  = 0x0E3C0, //
    CMSG_COMPLETE_ACHIEVEMENT_CHEAT                  = 0x101DC, //
    SMSG_COMPRESSED_RESPOND_INSPECT_ACHIEVEMENTS     = 0x09130, //
    SMSG_COMPRESSED_ACHIEVEMENT_DATA                 = 0x0C1B0, //
    SMSG_QUESTUPDATE_ADD_PVP_KILL                    = 0x078E0, //
    CMSG_SET_CRITERIA_CHEAT                          = 0x101DD, //
    SMSG_CALENDAR_UPDATE_INVITE_LIST3                = 0x0A2A0, //
    CMSG_UNITANIMTIER_CHEAT                          = 0x101DE, //
    CMSG_CHAR_CUSTOMIZE                              = 0x02A66, // 14333
    SMSG_CHAR_CUSTOMIZE                              = 0x02da4, //
    SMSG_PET_RENAMEABLE                              = 0x0B6C8, //
    CMSG_REQUEST_VEHICLE_EXIT                        = 0x0B3CC, //
    CMSG_REQUEST_PLAYER_VEHICLE_EXIT                 = 0x0208C, //
    CMSG_REQUEST_VEHICLE_PREV_SEAT                   = 0x02DE4, //
    CMSG_REQUEST_VEHICLE_NEXT_SEAT                   = 0x064E4, //
    CMSG_REQUEST_VEHICLE_SWITCH_SEAT                 = 0x0A8CC, //
    CMSG_PET_LEARN_TALENT                            = 0x0A7A0, //
    CMSG_PET_UNLEARN_TALENTS                         = 0x08F5D, //
    SMSG_SET_PHASE_SHIFT                             = 0x0044C, //
    SMSG_ALL_ACHIEVEMENT_DATA                        = 0x0400E, //
    CMSG_FORCE_SAY_CHEAT                             = 0x101E7, //
    SMSG_HEALTH_UPDATE                               = 0x02AA8, //
    SMSG_POWER_UPDATE                                = 0x065E8, //
    CMSG_GAMEOBJ_REPORT_USE                          = 0x023A0, //
    SMSG_HIGHEST_THREAT_UPDATE                       = 0x03F7E, //
    SMSG_THREAT_UPDATE                               = 0x0B480, //
    SMSG_THREAT_REMOVE                               = 0x07626, // 14333
    SMSG_THREAT_CLEAR                                = 0x03A76, // 14333
    SMSG_CONVERT_RUNE                                = 0x101E8, //
    SMSG_RESYNC_RUNES                                = 0x101E9, //
    SMSG_ADD_RUNE_POWER                              = 0x101EA, //
    CMSG_START_QUEST                                 = 0x00613, //
    CMSG_REMOVE_GLYPH                                = 0x101EC, //
    CMSG_DUMP_OBJECTS                                = 0x101ED, //
    SMSG_DUMP_OBJECTS_DATA                           = 0x101EE, //
    CMSG_DISMISS_CRITTER                             = 0x0B7CC, //
    SMSG_NOTIFY_DEST_LOC_SPELL_CAST                  = 0x03588, //
    CMSG_AUCTION_LIST_PENDING_SALES                  = 0x0EDEC, //
    SMSG_AUCTION_LIST_PENDING_SALES                  = 0x0367F, // 14333
    SMSG_MODIFY_COOLDOWN                             = 0x030CC, //
    SMSG_PET_UPDATE_COMBO_POINTS                     = 0x0A2E6, // 14333
    CMSG_ENABLETAXI                                  = 0x0328C, //
    SMSG_PRE_RESURRECT                               = 0x026EE, // 14333
    SMSG_AURA_UPDATE_ALL                             = 0x06AA3, // 14333
    SMSG_AURA_UPDATE                                 = 0x02A37, // 14333
    CMSG_FLOOD_GRACE_CHEAT                           = 0x101F2, //
    SMSG_SERVER_FIRST_ACHIEVEMENT                    = 0x0EE7F, // 14333
    SMSG_PET_LEARNED_SPELL                           = 0x0B3C4, // 
    SMSG_PET_REMOVED_SPELL                           = 0x0F28C, //
    CMSG_CHANGE_SEATS_ON_CONTROLLED_VEHICLE          = 0x0E988, //
    CMSG_HEARTH_AND_RESURRECT                        = 0x07E66, // 14333
    SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA        = 0x03380, //
    SMSG_CRITERIA_DELETED                            = 0x0AF84, //
    SMSG_ACHIEVEMENT_DELETED                         = 0x0E6A0, //
    CMSG_SERVER_INFO_QUERY                           = 0x101F6, //
    SMSG_SERVER_INFO_RESPONSE                        = 0x101F7, //
    CMSG_CHECK_LOGIN_CRITERIA                        = 0x101F8, //
    SMSG_SERVER_BUCK_DATA_START                      = 0x101F9, //
    CMSG_QUERY_VEHICLE_STATUS                        = 0x069A0, //
    SMSG_BATTLEGROUND_INFO_THROTTLED                 = 0x075C4, //
    SMSG_PLAYER_VEHICLE_DATA                         = 0x0A5A4, //
    CMSG_PLAYER_VEHICLE_ENTER                        = 0x0AEC8, //
    CMSG_EJECT_PASSENGER                             = 0x0F688, //
    SMSG_PET_GUIDS                                   = 0x0EE2F, // 14333
    SMSG_CLIENTCACHE_VERSION                         = 0x0A237, // 14333
    SMSG_ITEM_REFUND_INFO_RESPONSE                   = 0x0095E, // 
    CMSG_ITEM_REFUND_INFO                            = 0x031E0, //
    CMSG_ITEM_REFUND                                 = 0x062E8, //
    SMSG_ITEM_REFUND_RESULT                          = 0x0441E, // 
    CMSG_CORPSE_MAP_POSITION_QUERY                   = 0x023CC, //
    SMSG_CORPSE_MAP_POSITION_QUERY_RESPONSE          = 0x1020A, //
    CMSG_LFG_SET_ROLES_2                             = 0x1020B, //
    CMSG_CALENDAR_CONTEXT_EVENT_SIGNUP               = 0x0AEAC, //
    SMSG_CALENDAR_ACTION_PENDING                     = 0x07E8C, //
    SMSG_EQUIPMENT_SET_LIST                          = 0x0F1A8, //
    CMSG_EQUIPMENT_SET_SAVE                          = 0x0BFC0, //
    CMSG_UPDATE_PROJECTILE_POSITION                  = 0x0EF7F, //
    SMSG_SET_PROJECTILE_POSITION                     = 0x02C84, //
    SMSG_TALENTS_INFO                                = 0x0BABF, // 14333
    CMSG_LEARN_PREVIEW_TALENTS                       = 0x0FFAC, //
    CMSG_LEARN_PREVIEW_TALENTS_PET                   = 0x032FA, // 14333
    SMSG_ARENA_OPPONENT_UPDATE                       = 0x028CC, //
    SMSG_ARENA_TEAM_CHANGE_FAILED_QUEUED             = 0x0A22B, // 14333
    SMSG_MULTIPLE_PACKETS                            = 0x02A76, // 14333
    SMSG_FORCE_UNK1_SPEED_CHANGE                     = 0x10219, //
    CMSG_FORCE_UNK1_SPEED_CHANGE_ACK                 = 0x0F0C0, //
    SMSG_FORCE_UNK2_SPEED_CHANGE                     = 0x1021B, //
    CMSG_FORCE_UNK2_SPEED_CHANGE_ACK                 = 0x07DE8, //
    SMSG_MOVE_LEVITATING                             = 0x0B8AC, //
    SMSG_SPLINE_MOVE_UNKNOWN_1235                    = 0x1021E, //
    SMSG_SPLINE_MOVE_UNKNOWN_1236                    = 0x1022F, //
    CMSG_EQUIPMENT_SET_USE                           = 0x0E8A0, //
    SMSG_EQUIPMENT_SET_USE_RESULT                    = 0x076AC, //
    SMSG_UNKNOWN_1240                                = 0x0B8E0, //
    CMSG_CHAR_FACTION_CHANGE                         = 0x07636, // 14333
    SMSG_CHAR_FACTION_CHANGE                         = 0x023AC, //
    SMSG_BATTLEFIELD_MGR_ENTRY_INVITE                = 0x0D325, // 14333
    CMSG_BATTLEFIELD_MGR_ENTRY_INVITE_RESPONSE       = 0x00005, //
    SMSG_BATTLEFIELD_MGR_ENTERED                     = 0x01B41, // 14333
    SMSG_BATTLEFIELD_MGR_QUEUE_INVITE                = 0x05B03, // 14333
    CMSG_BATTLEFIELD_MGR_QUEUE_INVITE_RESPONSE       = 0x08108, //
    CMSG_BATTLEFIELD_MGR_QUEUE_REQUEST               = 0x0011D, //
    SMSG_BATTLEFIELD_MGR_QUEUE_REQUEST_RESPONSE      = 0x01F63, // 14333
    SMSG_BATTLEFIELD_MGR_EJECT_PENDING               = 0x09721, // 14333
    SMSG_BATTLEFIELD_MGR_EJECTED                     = 0x01F25, // 14333
    CMSG_BATTLEFIELD_MGR_EXIT_REQUEST                = 0x08580, //
    SMSG_BATTLEFIELD_MGR_STATE_CHANGE                = 0x00363, // 14333
    MSG_SET_RAID_DIFFICULTY                          = 0x0FA73, // 14333
    SMSG_TOGGLE_XP_GAIN                              = 0x07980, //
    SMSG_GMRESPONSE_DB_ERROR                         = 0x0E0A0, //
    SMSG_GMRESPONSE_RECEIVED                         = 0x033AC, //
    CMSG_GMRESPONSE_RESOLVE                          = 0x0363E, // 14333
    SMSG_GMRESPONSE_STATUS_UPDATE                    = 0x00101, //
    CMSG_WORLD_STATE_UI_TIMER_UPDATE                 = 0x06222, // 14333
    SMSG_WORLD_STATE_UI_TIMER_UPDATE                 = 0x05557, //
    CMSG_CHAR_RACE_CHANGE                            = 0x0B276, // 14333
    SMSG_TALENTS_INVOLUNTARILY_RESET                 = 0x02A84, //
    SMSG_UNKNOWN_1276                                = 0x00093, //
    SMSG_LOOT_SLOT_CHANGED                           = 0x02EFB, // 14333
    CMSG_READY_FOR_ACCOUNT_DATA_TIMES                = 0x0F226, // 14333
    CMSG_QUERY_QUESTS_COMPLETED                      = 0x0FE33, // 14333
    SMSG_QUERY_QUESTS_COMPLETED_RESPONSE             = 0x07AFE, // 14333
    CMSG_GM_REPORT_LAG                               = 0x0E2A6, // 14333
    SMSG_CORPSE_NOT_IN_INSTANCE                      = 0x0BAB7, // 14333
    CMSG_SET_ALLOW_LOW_LEVEL_RAID1                   = 0x035EC, //
    CMSG_SET_ALLOW_LOW_LEVEL_RAID2                   = 0x029C4, //
    SMSG_CAMERA_SHAKE                                = 0x1009E, //
    SMSG_UPDATE_ITEM_ENCHANTMENTS                    = 0x020E8, //
    SMSG_REDIRECT_CLIENT                             = 0x0201B, //
    CMSG_REDIRECTION_FAILED                          = 0x10007, //
    SMSG_UNKNOWN_1295                                = 0x10008, //
    CMSG_UNKNOWN_1296                                = 0x009A0, // 14333
    SMSG_FORCE_SEND_QUEUED_PACKETS                   = 0x00C10, // 14333
    CMSG_REDIRECTION_AUTH_PROOF                      = 0x00E4C, //
    SMSG_COMBAT_LOG_MULTIPLE                         = 0x033A8, //
    SMSG_LFG_OPEN_FROM_GOSSIP                        = 0x071EC, //
    SMSG_UNKNOWN_1302                                = 0x10010, //
    CMSG_UNKNOWN_1303                                = 0x06BE0, //
    SMSG_UNKNOWN_1304                                = 0x072E0, //
    CMSG_COMMENTATOR_SKIRMISH_QUEUE_COMMAND          = 0x07A76, // 14333
    SMSG_UNKNOWN_1308                                = 0x10011, //
    CMSG_TRANSFORM                                   = 0x04577, //
    SMSG_UNKNOWN_1310                                = 0x02E88, //
    SMSG_UNKNOWN_1311                                = 0x01E76, //
    SMSG_UNKNOWN_1312                                = 0x04D56, //
    SMSG_UNKNOWN_1314                                = 0x10256, //
    SMSG_UNKNOWN_1315                                = 0x10257, //
    SMSG_UNKNOWN_1316                                = 0x10258, //
    SMSG_UNKNOWN_1317                                = 0x10259, //
    CMSG_UNKNOWN_1320                                = 0x1025C, //
    SMSG_UNKNOWN_1329                                = 0x02D57, //
    SMSG_SEND_QUEUED_PACKETS                         = 0x10012, //
    CMSG_REDIRECT_AUTH_PROOF                         = 0x00100, //
    CMSG_AUTO_DECLINE_GUILD_INVITES                  = 0x08589, //
    CMSG_SET_PRIMARY_TALENT_TREE                     = 0x0B627, // 14333
    CMSG_GROUP_SET_ROLES                             = 0x08509, //
    CMSG_WORLD_LOGIN                                 = 0x04011, // 14333
    CMSG_RETURN_TO_GRAVEYARD                         = 0x0B8EB, // 14333
    CMSG_VIOLENCE_LEVEL                              = 0x08842, // 14333
    CMSG_LOG_DISCONNECT                              = 0x00920, // 14333
    MSG_CHECK_CONNECTION                             = 0x04F57, // 14333
};

/// Player state
enum SessionStatus
{
    STATUS_AUTHED = 0,                                      // Player authenticated (_player == NULL, m_playerRecentlyLogout = false or will be reset before handler call, m_GUID have garbage)
    STATUS_LOGGEDIN,                                        // Player in game (_player != NULL, m_GUID == _player->GetGUID(), inWorld())
    STATUS_TRANSFER,                                        // Player transferring to another map (_player != NULL, m_GUID == _player->GetGUID(), !inWorld())
    STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT,                    // _player!= NULL or _player == NULL && m_playerRecentlyLogout, m_GUID store last _player guid)
    STATUS_NEVER,                                           // Opcode not accepted from client (deprecated or server side only)
    STATUS_UNHANDLED,                                       // Opcode not handled yet
};

enum PacketProcessing
{
    PROCESS_INPLACE = 0,                                    //process packet whenever we receive it - mostly for non-handled or non-implemented packets
    PROCESS_THREADUNSAFE,                                   //packet is not thread-safe - process it in World::UpdateSessions()
    PROCESS_THREADSAFE                                      //packet is thread-safe - process it in Map::Update()
};

class WorldPacket;
class WorldSession;

typedef void(WorldSession::*pOpcodeHandler)(WorldPacket& recvPacket);

struct OpcodeHandler
{
    OpcodeHandler() {}
    OpcodeHandler(const char* _name, SessionStatus _status, PacketProcessing _processing, pOpcodeHandler _handler)
        : name(_name), status(_status), packetProcessing(_processing), handler(_handler) {}

    char const* name;
    SessionStatus status;
    PacketProcessing packetProcessing;
    pOpcodeHandler handler;
};

extern OpcodeHandler* opcodeTable[NUM_OPCODE_HANDLERS];
void InitOpcodes();

/// Lookup opcode name for human understandable logging
inline const char* LookupOpcodeName(Opcodes id)
{
    if (id < NUM_OPCODE_HANDLERS)
    {
        OpcodeHandler* handler = opcodeTable[uint32(id)];
        return handler ? handler->name : "UNKNOWN OPCODE";
    }
    else
        return "UNKNOWN OPCODE";
}
#endif
/// @}
